currency: boost retrieval speed when calling currency.NewCode()
thrasher-corp/gocryptotrader pull request #1014
Opened 2022-08-26 02:57 UTC by shazbert

# PR Description

* Implement map of currency.Item instead of slice
* Use upper case currency code string as key identifier 
* cleaned up some coderinos

This should have a good knock on affect to the speed of currency.NewPair functions as it was iterating over 3k items * 2 for each currency side and this was compounded across different routines.  

Fixes # (issue)

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration and
also consider improving test coverage whilst working on a certain feature or package.

- [ ] go test ./... -race
- [ ] golangci-lint run
- [ ] Test X

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally and on Github Actions/AppVeyor with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-08-29 02:02 UTC, gloriousCode requested changes
# :horse_racing: :dash: :dash:

2022-08-29 02:38 UTC, shazbert commented on currency/code_types.go
> +	Items          map[string][]*Item
Yeah you are correct. This is just to maintain the state as it was before. It was mainly due to the same currency codes but two different types either fiat or cryptocurrency. At its current state there is no way to pull them out like you suggested `Code{Item: stored[0]}`. But I didn't want to go down that path for this PR just yet.

2022-08-29 02:42 UTC, shazbert commented on currency/code_types.go
> +func (i *Item) copy() *Item {
It was just for code reduction in storage.go, I couldn't deference and then change role field, it's not really a big deal I can just remove it.

2022-08-29 02:47 UTC, shazbert commented on currency/code.go
> +	if ok {
If it fails to update, to stay in line with what was happening before we need to insert a new stored currency Item but with a different role.

2022-08-30 22:35 UTC, gloriousCode requested changes
Couple more small thingerinos

2022-08-30 22:35 UTC, gloriousCode commented on currency/code.go
> +	if ok {
Yeah I see now. Not worth having the append twice to minimise indenting

2022-08-30 22:35 UTC, gloriousCode commented on currency/code_types.go
> +func (i *Item) copy() *Item {
Thanks for the removal!

2022-08-30 22:35 UTC, gloriousCode commented on currency/code_types.go
> +	Items          map[string][]*Item
Thanks for the explanation, It'll be good for later then.

2022-08-30 22:35 UTC, gloriousCode commented on currency/code_test.go
> +	if ok {
rm this `if`, the above means this will always be true

2022-08-30 23:56 UTC, gloriousCode approved these changes
tACK! Thanks for making those changes :racehorse:

2022-08-31 00:45 UTC, thrasher- commented
tACK, quite a significant speed boost. Nice stuff!

```
PR:
goos: windows
goarch: amd64
pkg: github.com/thrasher-corp/gocryptotrader/currency
cpu: AMD Ryzen Threadripper 3970X 32-Core Processor
BenchmarkNewCode
BenchmarkNewCode-64
14170744	        77.24 ns/op	       8 B/op	       1 allocs/op

main:
goos: windows
goarch: amd64
pkg: github.com/thrasher-corp/gocryptotrader/currency
cpu: AMD Ryzen Threadripper 3970X 32-Core Processor
BenchmarkNewCode
BenchmarkNewCode-64 313797	      3364 ns/op	       8 B/op	       1 allocs/op

PR:
goos: linux
goarch: amd64
pkg: github.com/thrasher-corp/gocryptotrader/currency
cpu: AMD Ryzen Threadripper 3970X 32-Core Processor
BenchmarkNewCode
BenchmarkNewCode-64    	13845956	        84.42 ns/op	       8 B/op	       1 allocs/op

main:
goos: linux
goarch: amd64
pkg: github.com/thrasher-corp/gocryptotrader/currency
cpu: AMD Ryzen Threadripper 3970X 32-Core Processor
BenchmarkNewCode
BenchmarkNewCode-64    	  310576	      3759 ns/op	       8 B/op	       1 allocs/op

```

2022-08-31 00:45 UTC, thrasher- approved these changes

2022-08-31 00:45 UTC, merged