orders: filter options return on validate get orders request
thrasher-corp/gocryptotrader pull request #1055
Opened 2022-10-10 03:18 UTC by shazbert

# PR Description

After testing recent PR #1054. This attempts to standardize response filtering to requests across all wrapper functions as there were a few missing:

- BTCMarkets GetOrderHistory
- BTSE GetOrderHistory
- FTX GetOrderHistory
- FTX GetActiveOrders
- LBank GetActiveOrders
- LBank GetOrderHistory
- OKGroup GetOrderHistory
- OKGroup GetActiveOrders

master
```
go run ./... getorders --asset=futures --exchange='ftx' --pair=xrp-perp --start="2022-09-10 11:39:09" --end="2022-09-10 11:40:09"
{
 "orders": [
  {
   "exchange": "ftx",
   "id": "189009320677",
   "client_order_id": "web-t384J1WY-1665362274101",
   "base_currency": "XRP",
   "quote_currency": "PERP",
   "asset_type": "futures",
   "order_side": "BUY",
   "order_type": "LIMIT",
   "creation_time": "2022-10-10 00:38:04 +0000",
   "status": "OPEN",
   "price": 0.11,
   "amount": 90,
   "open_volume": 90
  }
 ]
}
```

this brancherino:

```
go run ./... getorders --asset=futures --exchange='ftx' --pair=xrp-perp --start="2022-09-10 11:39:09" --end="2022-09-10 11:40:09"
{}
go run ./... getorders --asset=futures --exchange='ftx' --pair=xrp-perp
{
 "orders": [
  {
   "exchange": "ftx",
   "id": "189009320677",
   "client_order_id": "web-t384J1WY-1665362274101",
   "base_currency": "XRP",
   "quote_currency": "PERP",
   "asset_type": "futures",
   "order_side": "BUY",
   "order_type": "LIMIT",
   "creation_time": "2022-10-10 00:38:04 +0000",
   "status": "OPEN",
   "price": 0.11,
   "amount": 90,
   "open_volume": 90
  }
 ]
}
```

**Opened in draft for review commentary and design as I skipped over some caveats in some exchanges which I will need to test and implement.**

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration and
also consider improving test coverage whilst working on a certain feature or package.

- [ ] go test ./... -race
- [ ] golangci-lint run
- [ ] Test X

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally and on Github Actions/AppVeyor with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-10-11 00:37 UTC, gloriousCode requested changes
Nice! This is just a quick review of the easy nits.

2022-10-11 00:37 UTC, gloriousCode commented on exchanges/btcmarkets/btcmarkets_wrapper.go
> +	err := req.Validate()
Test lacks type and will fail with proper credentials

2022-10-11 00:37 UTC, gloriousCode commented on exchanges/btse/btse_wrapper.go
> +	err := getOrdersRequest.Validate()
Test lacks side and will fail with proper credentials

2022-10-11 00:37 UTC, gloriousCode commented on exchanges/bybit/bybit_wrapper.go
> +	err := req.Validate()
Test lacks side  & type and will fail with proper credentials

2022-10-11 00:37 UTC, gloriousCode commented on exchanges/coinbasepro/coinbasepro_wrapper.go
> +	err := req.Validate()
Test lacks side and will fail with proper credentials

2022-10-11 00:37 UTC, gloriousCode commented on exchanges/coinut/coinut_wrapper.go
> +	err := req.Validate()
Test lacks side and will fail with proper credentials

2022-10-11 00:37 UTC, gloriousCode commented on exchanges/exmo/exmo_wrapper.go
> +	err := req.Validate()
Test lacks side and will fail with proper credentials

2022-10-11 00:37 UTC, gloriousCode commented on exchanges/ftx/ftx_wrapper.go
> +	err := request.Validate()
Test lacks side & type and will fail with proper credentials

2022-10-11 00:37 UTC, gloriousCode commented on exchanges/gateio/gateio_wrapper.go
> +	err := req.Validate()
Test lacks side and will fail with proper credentials

2022-10-11 00:37 UTC, gloriousCode commented on exchanges/hitbtc/hitbtc_wrapper.go
> +	err := req.Validate()
Test lacks side and will fail with proper credentials

2022-10-11 00:37 UTC, gloriousCode commented on exchanges/huobi/huobi_wrapper.go
> +	err := req.Validate()
Test lacks side and will fail with proper credentials

2022-10-11 00:37 UTC, gloriousCode commented on exchanges/itbit/itbit_wrapper.go
> +	err := req.Validate()
Test lacks side and will fail with proper credentials

2022-10-11 00:37 UTC, gloriousCode commented on exchanges/kraken/kraken_wrapper.go
> +	err := getOrdersRequest.Validate()
Test lacks side and will fail with proper credentials

2022-10-11 00:37 UTC, gloriousCode commented on exchanges/lbank/lbank_wrapper.go
> +	err := getOrdersRequest.Validate()
Test lacks type and will fail with proper credentials

2022-10-11 00:37 UTC, gloriousCode commented on exchanges/lbank/lbank_wrapper.go
> +	err := getOrdersRequest.Validate()
Could you add a test for this?

2022-10-11 00:37 UTC, gloriousCode commented on exchanges/yobit/yobit_wrapper.go
> +	err := req.Validate()
Test lacks side and will fail with proper credentials

2022-10-11 00:37 UTC, gloriousCode commented on exchanges/ftx/ftx_wrapper.go
> +	err := getOrdersRequest.Validate()
Anyside and anytype pass validation, however, they do not translate well to actually make a request. We should not populate the FTX request with those fields when any

2022-10-11 00:37 UTC, gloriousCode commented on exchanges/order/order_test.go
> +	if !shinyAndClean[0].Pair.Equal(btcltc) {
I think we could make this a little better. Perhaps a `for` to ensure all returned items are filtered appropriately. Or perhaps orderID checks

2022-10-11 00:37 UTC, gloriousCode commented on exchanges/order/orders.go
> +	FilterOrdersByType(&filtered, g.Type)
Having all of these requests are likely to have consequeces. See the implementation of this function with the following:

```go
if AnyType == orderType || len(*orders) == 0 {
		return
	}

	target := 0
	for i := range *orders {
		if (*orders)[i].Type == orderType {
			(*orders)[target] = (*orders)[i]
			target++
		}
	}
```
If you provide anything other than `ANY`, then the filter _must_ match, even if its `unknowntype` and therefore, we will filter any orders that do not populate that data in their API response. My next review will focus on the concequences. A simple fix would be to allow `FilterOrdersByType` and `FilterOrdersBySide` to always accept unpopulated fields, or for `GetOrdersRequest` to have an additional field which will allow non-populated fields to be returned

2022-10-19 22:29 UTC, gloriousCode requested changes
Thanks for making all those changes! Couple more things, but I'm happy with how you've handled it all

2022-10-19 22:29 UTC, gloriousCode commented on exchanges/bybit/bybit_test.go
>  	_, err = b.GetActiveOrders(context.Background(), &getOrdersRequestSpot)
Please update the remaining `order.GetOrdersRequest` scenarios to have `Side` and `Type`

2022-10-19 22:29 UTC, gloriousCode commented on exchanges/ftx/ftx_test.go
>  	_, err := f.GetActiveOrders(context.Background(), &orderReq)
I love the use of the validator checks. Could you please add another scenario for `ImmediateOrCancel` to test the expected error?

2022-10-19 22:29 UTC, gloriousCode commented on exchanges/ftx/ftx_test.go
>  	_, err := f.GetOrderHistory(context.Background(), &orderReq)
I love the use of the validator checks. Could you please add another scenario for `ImmediateOrCancel` to test the expected error? Along with a side of `MissingData` or some other invalid option

2022-10-20 00:14 UTC, gloriousCode approved these changes
tACK! Thanks for making those changes. Verified filtering via rpc as well

2022-10-24 02:17 UTC, thrasher- approved these changes
tACK, a more comprehensive solution which catches the previous gotcha!

2022-10-24 02:28 UTC, merged