exchanges: Remove OKGroup
thrasher-corp/gocryptotrader pull request #1103
Opened 2022-12-16 02:13 UTC by gloriousCode

# PR Description

With OKx using v5 and OKCoin International using V3 (with no plans for a v5 at present), there's no need for an okgroup that shares data across the same endpoints. This moves all of okgroup's functions to okcoin international and removes some of the old jank that I used to code with 4 years ago :eyes: 

This isn't a re-assessment of the whole okcoin API though, things like extra coverage hasn't been added, but I can add it if desired so we have a strong base

## How has this been tested
- [x] go test ./... -race
- [x] golangci-lint run

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally and on Github Actions/AppVeyor with my changes

2022-12-19 06:08 UTC, thrasher- requested changes
Thanks for simplifying this after the OKX merge! First pass, just some minor "whilst we're here things" as I'm not expecting a full API upgrade for this PR

2022-12-21 03:44 UTC, shazbert requested changes
Looks way better!

Some strange issue with the amount of tradeable currencies come back; 7? This endpoint seems to have all of them so maybe we can just update to this: `https://www.okcoin.com/api/v3/otc/rfq/instruments` maybe?

Nice work.

2022-12-21 03:44 UTC, shazbert commented on exchanges/okcoin/okcoin.go
> +	}
```go
requestURL := getWithdrawalHistory
if currency != "" {
		requestURL += "/" + currency
}
```

And the rest on this file.

2022-12-21 03:44 UTC, shazbert commented on exchanges/okcoin/okcoin.go
> +	}
Can drop this switch case as its default is handled in the if statement above,

2022-12-21 03:44 UTC, shazbert commented on exchanges/okcoin/okcoin.go
> +func formatParameters(request interface{}) string {
Suggestion: I would return an error.

2022-12-21 03:44 UTC, shazbert commented on exchanges/okcoin/okcoin_websocket.go
> +		c := currency.NewPairWithDelimiter(f[0], f[1], delimiterDash)
🔥

2022-12-21 03:44 UTC, shazbert commented on exchanges/okcoin/okcoin.go
> +		Result       bool   `json:"result,string,omitempty"`
Drop omit empty

2022-12-22 02:28 UTC, shazbert approved these changes
tACK good stuff!

2022-12-22 23:27 UTC, thrasher- approved these changes
tACK, thank you for making those changes!

2022-12-22 23:27 UTC, merged