engine: Adds shutdown and unload all exchanges when engine is stopped
thrasher-corp/gocryptotrader pull request #1112
Opened 2023-01-16 03:02 UTC by shazbert

# PR Description

Force all exchanges to shutdown websocket and rest connections/resources when the engine shuts down.
* This exposes some implementation issues when handling routines and potential leaks instead of having to use RPC to remove an exchange and add an exchange. 

This issue attempts to rectify incorrect implementation arising from #1058 specfically [this nit](https://github.com/thrasher-corp/gocryptotrader/pull/1058#discussion_r1065165422)

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration and
also consider improving test coverage whilst working on a certain feature or package.

- [ ] go test ./... -race
- [ ] golangci-lint run
- [ ] Test X

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally and on Github Actions/AppVeyor with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2023-01-16 23:13 UTC, gloriousCode requested changes

2023-01-16 23:13 UTC, gloriousCode commented on engine/exchange_manager.go
> +func (m *ExchangeManager) Shutdown() error {
Depending on context, this function does introduce new issues.
- With websocket shutdown now being included, depending when shutdown is called, causes issues which block the shutdown of the application. Consider the following snippets and their timestamps:
```
[INFO]  | LOG |  17/01/2023 10:00:20  | Captured interrupt, shutdown requested.
```

```
[ERROR] | PORTFOLIO |  17/01/2023 10:00:33  | Error encountered retrieving exchange account info for COINUT. Error COINUT websocket connection: timeout waiting for response with signature: 3785467
[WARN]  | WEBSOCKET |  17/01/2023 10:00:36  | Binance exchange backlog in websocket processing detected
[WARN]  | WEBSOCKET |  17/01/2023 10:00:52  | Okx exchange backlog in websocket processing detected
[WARN]  | WEBSOCKET |  17/01/2023 10:01:03  | ZB exchange backlog in websocket processing detected
[WARN]  | WEBSOCKET |  17/01/2023 10:01:21  | Bybit exchange backlog in websocket processing detected
[WARN]  | WEBSOCKET |  17/01/2023 10:01:47  | HitBTC exchange backlog in websocket processing detected
[WARN]  | WEBSOCKET |  17/01/2023 10:02:45  | CoinbasePro exchange backlog in websocket processing detected
[WARN]  | WEBSOCKET |  17/01/2023 10:02:48  | Huobi exchange backlog in websocket processing detected
[WARN]  | WEBSOCKET |  17/01/2023 10:02:50  | Bitstamp exchange backlog in websocket processing detected
[WARN]  | WEBSOCKET |  17/01/2023 10:03:09  | Bithumb exchange backlog in websocket processing detected
[WARN]  | WEBSOCKET |  17/01/2023 10:03:20  | Bitstamp websocket has been disconnected. Reason: read tcp 192.168.1.13:54344->35.156.126.7:443: use of closed network connection
[WARN]  | EXCHANGE |  17/01/2023 10:03:23  | Bitstamp BTC/USD spot orderbook has zero bid price, filtering.
[ERROR] | WEBSOCKET |  17/01/2023 10:03:23  | Bitstamp cannot start websocket connection monitor connection monitor is already running
[WARN]  | WEBSOCKET |  17/01/2023 10:03:23  | Bitstamp exchange backlog in websocket processing detected
[WARN]  | WEBSOCKET |  17/01/2023 10:03:37  | GateIO exchange backlog in websocket processing detected
[ERROR] | WEBSOCKET |  17/01/2023 10:03:40  | Bithumb cannot start websocket connection monitor connection monitor is already running
[WARN]  | WEBSOCKET |  17/01/2023 10:03:42  | Bithumb exchange backlog in websocket processing detected
[WARN]  | WEBSOCKET |  17/01/2023 10:03:53  | Bitstamp websocket has been disconnected. Reason: read tcp 192.168.1.13:54365->18.194.85.184:443: use of closed network connection
[WARN]  | EXCHANGE |  17/01/2023 10:03:55  | Bitstamp BTC/USD spot orderbook has zero bid price, filtering.
[ERROR] | WEBSOCKET |  17/01/2023 10:03:55  | Bitstamp cannot start websocket connection monitor connection monitor is already running
[WARN]  | WEBSOCKET |  17/01/2023 10:03:55  | Bitstamp exchange backlog in websocket processing detected
[WARN]  | WEBSOCKET |  17/01/2023 10:04:07  | GateIO websocket has been disconnected. Reason: read tcp 192.168.1.13:54340->18.177.40.176:443: use of closed network connection
[ERROR] | WEBSOCKET |  17/01/2023 10:04:09  | GateIO cannot start websocket connection monitor connection monitor is already running
[WARN]  | WEBSOCKET |  17/01/2023 10:04:11  | GateIO exchange backlog in websocket processing detected
[ERROR] | WEBSOCKET |  17/01/2023 10:04:14  | Bithumb cannot start websocket connection monitor connection monitor is already running
[WARN]  | WEBSOCKET |  17/01/2023 10:04:15  | Bithumb exchange backlog in websocket processing detected
[ERROR] | WEBSOCKET |  17/01/2023 10:04:17  | GateIO subscription failure: GateIO websocket connection: timeout waiting for response with signature: 169499117
[WARN]  | WEBSOCKET |  17/01/2023 10:04:25  | Bitstamp websocket has been disconnected. Reason: read tcp 192.168.1.13:54370->18.194.85.184:443: use of closed network connection
[WARN]  | EXCHANGE |  17/01/2023 10:04:27  | Bitstamp BTC/USD spot orderbook has zero bid price, filtering.
[ERROR] | WEBSOCKET |  17/01/2023 10:04:27  | Bitstamp cannot start websocket connection monitor connection monitor is already running
[WARN]  | WEBSOCKET |  17/01/2023 10:04:27  | Bitstamp exchange backlog in websocket processing detected
[WARN]  | WEBSOCKET |  17/01/2023 10:04:29  | COINUT websocket has been disconnected. Reason: websocket: close 1006 (abnormal closure): unexpected EOF
[ERROR] | WEBSOCKET |  17/01/2023 10:04:31  | COINUT cannot start websocket connection monitor connection monitor is already running
[WARN]  | WEBSOCKET |  17/01/2023 10:04:41  | GateIO websocket has been disconnected. Reason: read tcp 192.168.1.13:54373->43.206.6.17:443: use of closed network connection
[ERROR] | WEBSOCKET |  17/01/2023 10:04:42  | GateIO cannot start websocket connection monitor connection monitor is already running
[WARN]  | WEBSOCKET |  17/01/2023 10:04:43  | BTC Markets exchange backlog in websocket processing detected
[WARN]  | WEBSOCKET |  17/01/2023 10:04:43  | GateIO exchange backlog in websocket processing detected
[ERROR] | WEBSOCKET |  17/01/2023 10:04:48  | Bithumb cannot start websocket connection monitor connection monitor is already running
[WARN]  | WEBSOCKET |  17/01/2023 10:04:49  | Bithumb exchange backlog in websocket processing detected
[WARN]  | WEBSOCKET |  17/01/2023 10:04:57  | Bitstamp websocket has been disconnected. Reason: read tcp 192.168.1.13:54375->18.197.135.115:443: use of closed network connection
[ERROR] | WEBSOCKET |  17/01/2023 10:04:57  | GateIO subscription failure: GateIO websocket connection: timeout waiting for response with signature: 149277907, GateIO websocket connection: timeout waiting for response with signature: 189667856
[WARN]  | EXCHANGE |  17/01/2023 10:04:59  | Bitstamp BTC/USD spot orderbook has zero bid price, filtering.
```

I had to forcefully quit the application after 10 minutes

2023-01-16 23:13 UTC, gloriousCode commented on engine/exchange_manager.go
> +func (m *ExchangeManager) Shutdown() error {
- If you do time the application shutdown correctly, you get some extra verbosity that I think we could probably do without:
```
[WARN]  | WEBSOCKET |  17/01/2023 09:59:01  | ZB websocket has been disconnected. Reason: read tcp 192.168.1.13:54249->172.67.31.157:443: use of closed network connection
[INFO]  | EXCHANGE |  17/01/2023 09:59:01  | ZB exchange unloaded successfully.
[WARN]  | WEBSOCKET |  17/01/2023 09:59:01  | GateIO websocket has been disconnected. Reason: read tcp 192.168.1.13:54259->18.177.40.176:443: use of closed network connection
[INFO]  | EXCHANGE |  17/01/2023 09:59:01  | GateIO exchange unloaded successfully.
[WARN]  | WEBSOCKET |  17/01/2023 09:59:01  | Okx websocket has been disconnected. Reason: read tcp 192.168.1.13:54246->104.18.2.151:8443: use of closed network connection
[INFO]  | EXCHANGE |  17/01/2023 09:59:01  | Okx exchange unloaded successfully.
[INFO]  | EXCHANGE |  17/01/2023 09:59:01  | Lbank exchange unloaded successfully.
[INFO]  | EXCHANGE |  17/01/2023 09:59:01  | BTSE exchange unloaded successfully.
[WARN]  | WEBSOCKET |  17/01/2023 09:59:01  | BTC Markets websocket has been disconnected. Reason: read tcp 192.168.1.13:54248->172.64.150.138:443: use of closed network connection
[INFO]  | EXCHANGE |  17/01/2023 09:59:01  | BTC Markets exchange unloaded successfully.
[WARN]  | WEBSOCKET |  17/01/2023 09:59:01  | Gemini websocket has been disconnected. Reason: read tcp 192.168.1.13:54255->18.211.85.240:443: use of closed network connection
[INFO]  | EXCHANGE |  17/01/2023 09:59:01  | Gemini exchange unloaded successfully.
[INFO]  | EXCHANGE |  17/01/2023 09:59:01  | LocalBitcoins exchange unloaded successfully.
[INFO]  | EXCHANGE |  17/01/2023 09:59:01  | Yobit exchange unloaded successfully.
[WARN]  | WEBSOCKET |  17/01/2023 09:59:01  | Poloniex websocket has been disconnected. Reason: read tcp 192.168.1.13:54253->104.16.116.135:443: use of closed network connection
[INFO]  | EXCHANGE |  17/01/2023 09:59:01  | Poloniex exchange unloaded successfully.
[INFO]  | EXCHANGE |  17/01/2023 09:59:01  | ITBIT exchange unloaded successfully.
[WARN]  | WEBSOCKET |  17/01/2023 09:59:01  | Binanceus websocket has been disconnected. Reason: read tcp 192.168.1.13:54267->34.238.66.24:9443: use of closed network connection
[INFO]  | EXCHANGE |  17/01/2023 09:59:01  | Binanceus exchange unloaded successfully.
[WARN]  | WEBSOCKET |  17/01/2023 09:59:01  | Huobi websocket has been disconnected. Reason: read tcp 192.168.1.13:54250->104.16.230.188:443: use of closed network connection
[INFO]  | EXCHANGE |  17/01/2023 09:59:01  | Huobi exchange unloaded successfully.
[WARN]  | WEBSOCKET |  17/01/2023 09:59:01  | Bitstamp websocket has been disconnected. Reason: read tcp 192.168.1.13:54265->18.197.135.115:443: use of closed network connection
[INFO]  | EXCHANGE |  17/01/2023 09:59:01  | Bitstamp exchange unloaded successfully.
[WARN]  | WEBSOCKET |  17/01/2023 09:59:01  | Binance websocket has been disconnected. Reason: read tcp 192.168.1.13:54260->54.199.160.150:9443: use of closed network connection
[ERROR] | LOG |  17/01/2023 09:59:01  | HitBTC failed to get cryptocurrency deposit address for DASH. Err: HitBTC unsuccessful HTTP status code: 403 raw response: {"error":{"code":1003,"message":"Action is forbidden for this API key"}}
[INFO]  | EXCHANGE |  17/01/2023 09:59:01  | Binance exchange unloaded successfully.
[WARN]  | WEBSOCKET |  17/01/2023 09:59:01  | CoinbasePro websocket has been disconnected. Reason: read tcp 192.168.1.13:54245->104.18.8.210:443: use of closed network connection
[INFO]  | EXCHANGE |  17/01/2023 09:59:01  | CoinbasePro exchange unloaded successfully.
[WARN]  | WEBSOCKET |  17/01/2023 09:59:01  | Bitfinex websocket has been disconnected. Reason: read tcp 192.168.1.13:54261->104.16.173.181:443: use of closed network connection
[WARN]  | WEBSOCKET |  17/01/2023 09:59:01  | Bitfinex websocket has been disconnected. Reason: read tcp 192.168.1.13:54270->104.16.175.181:443: use of closed network connection
[INFO]  | EXCHANGE |  17/01/2023 09:59:01  | Bitfinex exchange unloaded successfully.
[WARN]  | WEBSOCKET |  17/01/2023 09:59:01  | OKCOIN International websocket has been disconnected. Reason: read tcp 192.168.1.13:54264->104.18.158.225:8443: use of closed network connection
[INFO]  | EXCHANGE |  17/01/2023 09:59:01  | OKCOIN International exchange unloaded successfully.
[WARN]  | WEBSOCKET |  17/01/2023 09:59:01  | Bitmex websocket has been disconnected. Reason: read tcp 192.168.1.13:54254->172.64.146.66:443: use of closed network connection
[INFO]  | EXCHANGE |  17/01/2023 09:59:01  | Bitmex exchange unloaded successfully.
[ERROR] | WEBSOCKET |  17/01/2023 09:59:01  | Bithumb cannot start websocket connection monitor connection monitor is already running
[INFO]  | LOG |  17/01/2023 09:59:01  | Exiting
```

2023-01-16 23:13 UTC, gloriousCode commented on engine/exchange_manager.go
> +func (m *ExchangeManager) Shutdown() error {
- I would consider the introduction of asynchronous processing due the time it can take to shutdown a websocket

2023-01-16 23:13 UTC, gloriousCode commented on engine/exchange_manager.go
> +func (m *ExchangeManager) Shutdown() error {
The reason I brought up context was that when shutting down the application, we really don't actually need to wait for the websocket to shut down correctly. Only when shutting down our own exchange manager, so you may wish to introduce a new function, or introduce a _force_ flag or something along those lines

2023-02-17 04:19 UTC, gloriousCode reviewed
Thanks for making your changes! It has highlighted that BinanceUS is having some difficulties shutting down. When I figure it out, I'll leave a diff.

I have managed to make GCT completely stuck though and had to kill the process. Once BinanceUS is sorted, I'll recheck against it to see if that was the culprit or if there's something more going on in the shutdown implementation

2023-03-09 00:10 UTC, gloriousCode requested changes
tACK! Thanks for making those changes. While I can sometimes get BinanceUS to be overwhelmed by orderbook sync, I think that's its own thing to look at later as the shutdown does work

You just need to fix the spulling linter

2023-03-09 02:09 UTC, gloriousCode approved these changes
Thanks for fixing all that spelling 😎

2023-04-02 01:30 UTC, thrasher- commented on engine/exchange_manager.go
> +	timer := time.NewTimer(time.Second * 10)
```suggestion
	timer := time.NewTimer(time.Second * 10)
```

Would be nice to see this configurable instead of a magic number

2023-04-03 23:37 UTC, gloriousCode commented on engine/exchange_manager.go
> +func (m *ExchangeManager) Shutdown(shutdownTimeout time.Duration) error {
I suspect you're going to need to do some more validation
```
fatal error: concurrent map iteration and map write
[DEBUG] | WEBSOCKET | 04/04/2023 09:36:20 | GateIO websocket: trafficMonitor shutdown message received

goroutine 137 [running]:
github.com/thrasher-corp/gocryptotrader/engine.(*ExchangeManager).GetExchanges(0x14000592060)
	/Users/scottg/go/src/github.com/thrasher-corporation/gocryptotrader/engine/exchange_manager.go:98 +0x1a4
github.com/thrasher-corp/gocryptotrader/engine.(*syncManager).worker(0x1400057a000)
	/Users/scottg/go/src/github.com/thrasher-corporation/gocryptotrader/engine/sync_manager.go:476 +0x70
created by github.com/thrasher-corp/gocryptotrader/engine.(*syncManager).Start
	/Users/scottg/go/src/github.com/thrasher-corporation/gocryptotrader/engine/sync_manager.go:233 +0x4a0

goroutine 1 [runnable]:
github.com/thrasher-corp/gocryptotrader/currency.(*BaseCodes).GetFullCurrencyData(0x101c90288)
	/Users/scottg/go/src/github.com/thrasher-corporation/gocryptotrader/currency/code.go:94 +0x128
github.com/thrasher-corp/gocryptotrader/currency.(*Storage).WriteCurrencyDataToFile(0x101c90240, {0x140000d9440, 0x2b}, 0x1)
	/Users/scottg/go/src/github.com/thrasher-corporation/gocryptotrader/currency/storage.go:392 +0x58
github.com/thrasher-corp/gocryptotrader/currency.(*Storage).Shutdown(0x101c90240)
	/Users/scottg/go/src/github.com/thrasher-corporation/gocryptotrader/currency/storage.go:774 +0x10c
github.com/thrasher-corp/gocryptotrader/currency.ShutdownStorageUpdater(...)
	/Users/scottg/go/src/github.com/thrasher-corporation/gocryptotrader/currency/currency.go:94
github.com/thrasher-corp/gocryptotrader/engine.(*Engine).Stop(0x140000d7440)
	/Users/scottg/go/src/github.com/thrasher-corporation/gocryptotrader/engine/engine.go:721 +0xb4c
main.main()
	/Users/scottg/go/src/github.com/thrasher-corporation/gocryptotrader/main.go:155 +0x1474
```

2023-04-04 23:17 UTC, gloriousCode reviewed
Thanks for fixing up those pesky read/writes. These are only minor things

2023-04-05 00:14 UTC, gloriousCode approved these changes
tACK!

2023-04-05 02:01 UTC, thrasher- requested changes
Minor changes, tACK after those are done. Good stuff!

2023-04-05 03:07 UTC, merged