stream: set connection monitor delay.
thrasher-corp/gocryptotrader pull request #1120
Opened 2023-01-25 14:46 UTC by dnldd

# PR Description

- this fixes a bug where the connection monitor delay config value does not get set to the websocket on intialization.

Fixes # (issue)

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration and
also consider improving test coverage whilst working on a certain feature or package.

- [ ] go test ./... -race
- [ ] golangci-lint run
- [ ] Test X

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally and on Github Actions/AppVeyor with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2023-01-26 22:29 UTC, gloriousCode approved these changes
😅 Lovely fix. Thanks for that

2023-01-27 09:54 UTC, dnldd commented
Noted, will work that in this weekend.

2023-01-29 20:59 UTC, shazbert requested changes
Thank you! 🚀 Tested and it works and everything has been set. Just two minor nits.

2023-01-29 20:59 UTC, shazbert commented on config/config_types.go
> +	defaultConnectionMinitorDelay        = time.Second * 2
Minitor -> Monitor

2023-01-29 20:59 UTC, shazbert commented on config/config.go
> +	if c.ConnectionMonitorDelay == 0 || c.ConnectionMonitorDelay < 0 {
```go
if c.ConnectionMonitorDelay <= 0 {
```

2023-01-30 00:02 UTC, gloriousCode requested changes
Thank you for expanding your PR! One potential suggestion from me

2023-01-30 01:27 UTC, shazbert commented on config/config_types.go
> +	defaultConnectionMinitorDelay        = time.Second * 2
Probably need to include websocket: `config.DefaultWebsocketConnectionMonitorDelay`

2023-01-30 21:04 UTC, gloriousCode approved these changes
tACK! Thanks for making those changes

2023-01-30 21:20 UTC, shazbert approved these changes
Changes ACK. thanks 🖖

2023-01-30 22:21 UTC, thrasher- approved these changes
Thank you for your first contribution/fix @dnldd !

2023-01-30 22:21 UTC, merged