Linter fix
thrasher-corp/gocryptotrader pull request #1169
Opened 2023-04-12 16:02 UTC by samuael

This pull request contains several fixes to the gocryptotrader codebase, including a fix for a linter issue, suppressing some linter issues by adding a linter directive, removing unnecessary linter directives, and changing some variable names to constants.

Fixes # (issue)

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as the item is complete.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested

- [X] go test ./... -race
- [X] golangci-lint run
- [ ] Test X

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally and on Github Actions/AppVeyor with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-04-12 22:20 UTC, gloriousCode requested changes
Always nice to see you get more familiar with our codebase 🎉 
You'll just need to be more specific with your nolints

2023-04-12 22:20 UTC, gloriousCode commented on exchanges/bitfinex/bitfinex_test.go
> +func runAuth(t *testing.T) { //nolint
Please be more specific with your nolint usage. Here is an example from our codebase:
`//nolint:forcetypeassert // Not necessary from a pool`
we specify what we are nolinting and we provide a comment on why we are nolinting

2023-04-12 22:20 UTC, gloriousCode commented on currency/forexprovider/fixer.io/fixer_test.go
> +func setup(t *testing.T) { //nolint
Please be more specific with your nolint usage. Here is an example from our codebase:
`//nolint:forcetypeassert // Not necessary from a pool`
we specify what we are nolinting and we provide a comment on why we are nolinting

2023-04-12 22:20 UTC, gloriousCode commented on database/repository/audit/audit_test.go
> +func writeAudit(t *testing.T) { //nolint
Please be more specific with your nolint usage. Here is an example from our codebase:
`//nolint:forcetypeassert // Not necessary from a pool`
we specify what we are nolinting and we provide a comment on why we are nolinting

2023-04-12 22:20 UTC, gloriousCode commented on database/repository/audit/audit_test.go
> +func readHelper(t *testing.T) { //nolint
Please be more specific with your nolint usage. Here is an example from our codebase:
`//nolint:forcetypeassert // Not necessary from a pool`
we specify what we are nolinting and we provide a comment on why we are nolinting

2023-04-12 22:20 UTC, gloriousCode commented on database/repository/withdraw/withdraw_test.go
> +func withdrawHelper(t *testing.T) { //nolint
Please be more specific with your nolint usage. Here is an example from our codebase:
`//nolint:forcetypeassert // Not necessary from a pool`
we specify what we are nolinting and we provide a comment on why we are nolinting

2023-04-12 22:20 UTC, gloriousCode commented on engine/database_connection_test.go
> +func CreateDatabase(t *testing.T) { //nolint
Please be more specific with your nolint usage. Here is an example from our codebase:
`//nolint:forcetypeassert // Not necessary from a pool`
we specify what we are nolinting and we provide a comment on why we are nolinting

2023-04-12 22:20 UTC, gloriousCode commented on exchanges/bittrex/bittrex_test.go
> +func WithdrawCryptocurrencyFunds(t *testing.T) { //nolint
Please be more specific with your nolint usage. Here is an example from our codebase:
`//nolint:forcetypeassert // Not necessary from a pool`
we specify what we are nolinting and we provide a comment on why we are nolinting

2023-04-12 22:20 UTC, gloriousCode commented on exchanges/hitbtc/hitbtc_test.go
> +func setupWsAuth(t *testing.T) { //nolint
Please be more specific with your nolint usage. Here is an example from our codebase:
`//nolint:forcetypeassert // Not necessary from a pool`
we specify what we are nolinting and we provide a comment on why we are nolinting

2023-04-12 22:20 UTC, gloriousCode commented on exchanges/kline/kline_test.go
> +		if tt1.Unix() == tt2.Unix() || (tt1.Unix() > tt2.Unix() && tt1.Unix() < tt3.Unix()) { //nolint
Please be more specific with your nolint usage. Here is an example from our codebase:
`//nolint:forcetypeassert // Not necessary from a pool`
we specify what we are nolinting and we provide a comment on why we are nolinting

2023-04-12 22:20 UTC, gloriousCode commented on exchanges/kline/kline_test.go
> +		if tt1 >= tt2 && tt1 <= tt3 { //nolint
Please be more specific with your nolint usage. Here is an example from our codebase:
`//nolint:forcetypeassert // Not necessary from a pool`
we specify what we are nolinting and we provide a comment on why we are nolinting

2023-04-12 22:20 UTC, gloriousCode commented on exchanges/stream/buffer/buffer_test.go
> +		for range ch { //nolint
Please be more specific with your nolint usage. Here is an example from our codebase:
`//nolint:forcetypeassert // Not necessary from a pool`
we specify what we are nolinting and we provide a comment on why we are nolinting

2023-04-12 22:20 UTC, gloriousCode commented on exchanges/zb/zb_test.go
> +func setupWsAuth(t *testing.T) { //nolint
Please be more specific with your nolint usage. Here is an example from our codebase:
`//nolint:forcetypeassert // Not necessary from a pool`
we specify what we are nolinting and we provide a comment on why we are nolinting

2023-04-12 22:59 UTC, shazbert requested changes
Thanks for the changes! Are you getting these linter issues from the most recent version? If so, can you please bump all versions for GitHub actions like `linter.yml` and else ware?

2023-04-12 23:20 UTC, samuael commented
Yes, I found these issues after upgrading my linter. golangci-lint v1.52.2 with go1.20.2.

Okay sir I will update the .github/workflows/linter.yml file with my next commit. After few minutes

2023-04-13 23:03 UTC, shazbert requested changes
Appveyor is complaining :

<img width="708" alt="image" src="https://user-images.githubusercontent.com/9391715/231901247-475df632-0423-47ec-ab9e-7bb92d26ea5e.png">


Could you please bump the versions for golanci-lint across the code base.

2023-04-14 02:28 UTC, shazbert approved these changes
This is lovely. Thanks! 👍

2023-04-14 05:05 UTC, gloriousCode approved these changes
tACK! Thanks for making those changes

2023-04-27 00:13 UTC, thrasher- approved these changes
Nice work @samuael !

2023-04-27 00:13 UTC, merged

2023-04-28 00:17 UTC, samuael commented
Thank you, sir.
and I want to give a big Thanks to @shazbert  and @gloriousCode for your help on this PR.