OKX: Fix GetAvailableTransferChains bug
thrasher-corp/gocryptotrader pull request #1177
Opened 2023-05-01 02:18 UTC by shazbert

# PR Description

Noticed issue when testing #1174. This PR does not return chain when withdraw/deposit chain functionality is not enabled for currency.

```
[ERROR] | LOG | 01/05/2023 10:01:56 | Okx failed to get cryptocurrency deposit address for USDT [chain USDT-zkSync Lite]. Err: specified chain USDT-zkSync Lite not found
```

Fixes # (issue)

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration and
also consider improving test coverage whilst working on a certain feature or package.

- [ ] go test ./... -race
- [ ] golangci-lint run
- [ ] Test X

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally and on Github Actions/AppVeyor with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-05-01 03:17 UTC, gloriousCode requested changes
OK excuse me, this works. One highly important change

2023-05-01 03:17 UTC, gloriousCode commented on exchanges/okx/okx_wrapper.go
> +			(!currencyChains[x].CanDeposit && !currencyChains[x].CanWithdraw) {
```suggestion
		if (!cryptocurrency.IsEmpty() && !strings.EqualFold(cryptocurrency.String(), currencyChains[x].Currency)) ||
			(!currencyChains[x].CanDeposit && !currencyChains[x].CanWithdraw) {
```

2023-05-01 03:42 UTC, gloriousCode commented on exchanges/okx/okx_wrapper.go
> +			(!currencyChains[x].CanDeposit && !currencyChains[x].CanWithdraw) {
`[ERROR] | LOG | 01/05/2023 13:37:54 | Okx failed to get cryptocurrency deposit address for BTC [chain BTC-Lightning]. Err: specified chain BTC-Lightning not found`

```suggestion
		if (!cryptocurrency.IsEmpty() && !strings.EqualFold(cryptocurrency.String(), currencyChains[x].Currency)) ||
			(!currencyChains[x].CanDeposit && !currencyChains[x].CanWithdraw) ||
			!currencyChains[x].MainNet {
```

2023-05-01 04:21 UTC, thrasher- commented
nACK [4345f57](https://github.com/thrasher-corp/gocryptotrader/pull/1177/commits/4345f57ce0e984f562ec576aeebc09407a1d2544), this defeats the purpose of getting the "Available transfer chains" for a specified currency. Using something like USDT will now return an empty result. Instead, if a lightning chain is detected, it will need to use this endpoint: https://www.okx.com/docs-v5/en/#rest-api-funding-lightning-deposits which thankfully only occurs for BTC.

2023-05-01 05:08 UTC, thrasher- approved these changes
tACK, thanks for addressing the nit!

2023-05-02 22:24 UTC, gloriousCode requested changes
There is still technically an issue here:
`[ERROR] | LOG | 03/05/2023 07:48:05 | Okx failed to get cryptocurrency deposit address for BETH. Err: deposit address with the specified currency code and chain not found`
It does have a chain, but it does not allow deposits and withdrawals. Would require more extensive tweaking to not have an error displayed for this specific usecase which I don't think this PR needs to address.

So just the unmarshalling fix for me please.

2023-05-08 06:02 UTC, gloriousCode approved these changes
tACK! Thank you shazbert cow 🐄

2023-05-08 06:09 UTC, merged