orders: Add AdjustBaseAmount
thrasher-corp/gocryptotrader pull request #1181
Opened 2023-05-03 01:43 UTC by shazbert

The `AdjustBaseAmount` method alerts if non-fatal change occurs exchange side
This also adjusts BTCM and adds in price to response. 

Fixes # (issue)

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration and
also consider improving test coverage whilst working on a certain feature or package.

- [ ] go test ./... -race
- [ ] golangci-lint run
- [ ] Test X

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally and on Github Actions/AppVeyor with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-05-04 01:21 UTC, gloriousCode commented on exchanges/btcmarkets/btcmarkets_wrapper.go
> +	}
This is incompatible with targetAmount field:
<img width="1369" alt="image" src="https://user-images.githubusercontent.com/9261323/236085633-54ab0fdb-49e3-4716-9e81-27b8a1286671.png">

<img width="1369" alt="image" src="https://user-images.githubusercontent.com/9261323/236085773-cbaa06bf-979f-49b6-8874-2f5574c46185.png">

I would argue returning an error after an order has successfully submitted is not good. It means the order manager/CMD user won't know about it, even if it was successful

2023-05-08 06:25 UTC, gloriousCode requested changes
Can't believe you're forcing me to buy your LTC bags via this PR. Just two minor things

2023-05-08 06:25 UTC, gloriousCode commented on exchanges/order/orders.go
> +	log.Warnf(log.ExchangeSys, "exchange %v has adjusted requested base amount from %v to %v",
for orderID %v ?

2023-05-08 06:25 UTC, gloriousCode commented on exchanges/order/orders.go
> +	log.Warnf(log.ExchangeSys, "exchange %v has adjusted requested quote amount from %v to %v",
Please include orderID. Less important would be asset and pair depending on exchange

2023-05-09 04:15 UTC, gloriousCode approved these changes
[In reference to this](https://github.com/thrasher-corp/gocryptotrader/pull/1181#discussion_r1187067522) I will get you to add asset and currency when the usage of this is expanded and different assets have different order endpoints and orderIDs
tACK!

2023-05-12 03:03 UTC, thrasher- requested changes
Some minor nits, then good to merge!

2023-05-12 03:03 UTC, thrasher- commented on exchanges/order/orders.go
> +	log.Warnf(log.ExchangeSys, "Exchange %s: has adjusted OrderID: %v requested base amount from %v to %v",
Just need to swap the order of s.OrderID and s.Exchange

2023-05-12 03:03 UTC, thrasher- commented on exchanges/order/orders.go
> +	log.Warnf(log.ExchangeSys, "Exchange %s: has adjusted OrderID: %v requested quote amount from %v to %v",
Same goes for here

2023-05-12 03:03 UTC, thrasher- commented on exchanges/btcmarkets/btcmarkets_wrapper.go
> +			log.Errorf(log.ExchangeSys, "Exchange %s: OrderID: %s Base Amount Conversion Error: %s\n", b.Name, submitResp.OrderID, err)
```suggestion
			log.Errorf(log.ExchangeSys, "Exchange %s: OrderID: %s base amount conversion error: %s\n", b.Name, submitResp.OrderID, err)
```

2023-05-12 03:03 UTC, thrasher- commented on exchanges/btcmarkets/btcmarkets_wrapper.go
> +			log.Errorf(log.ExchangeSys, "Exchange %s: OrderID: %s Quote Amount Conversion Error: %s\n", b.Name, submitResp.OrderID, err)
```suggestion
			log.Errorf(log.ExchangeSys, "Exchange %s: OrderID: %s quote amount conversion error: %s\n", b.Name, submitResp.OrderID, err)
```

2023-05-12 03:16 UTC, thrasher- approved these changes
Thanks for making those changes!

2023-05-12 03:37 UTC, gloriousCode approved these changes

2023-05-12 04:06 UTC, merged