hitbtc: fix and optimise tradable pairs and tickers fetching
thrasher-corp/gocryptotrader pull request #1184
Opened 2023-05-03 05:46 UTC by shazbert

# PR Description

Fixes issue storing tradable pairs, fetching tickers and matching to available. 

Fixes # (issue)

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration and
also consider improving test coverage whilst working on a certain feature or package.

- [ ] go test ./... -race
- [ ] golangci-lint run
- [ ] Test X

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally and on Github Actions/AppVeyor with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-05-04 02:13 UTC, gloriousCode approved these changes
tACK!
What a frustrating change: `quote := strings.Replace(symbols[x].ID, symbols[x].BaseCurrency, "", 1)`

2023-05-08 06:35 UTC, thrasher- requested changes
Just some minor changes, the pair display of "USD" vs "USDT" was a funny one!

2023-05-08 06:35 UTC, thrasher- commented on exchanges/hitbtc/hitbtc_test.go
> +	_, err = h.UpdateTicker(context.Background(), currency.NewPair(currency.BTC, currency.USD), asset.Spot)
```suggestion
	_, err = h.UpdateTicker(context.Background(), pairs[0], asset.Spot)
```

2023-05-08 06:35 UTC, thrasher- commented on exchanges/hitbtc/hitbtc_test.go
> +	_, err = h.FetchTicker(context.Background(), currency.NewPair(currency.XRP, currency.USDT), asset.Spot)
```suggestion
	_, err = h.FetchTicker(context.Background(), pairs[1], asset.Spot)
```

2023-05-08 06:35 UTC, thrasher- commented on exchanges/hitbtc/hitbtc_test.go
> +	_, err = h.UpdateTicker(context.Background(), currency.NewPair(currency.BTC, currency.USD), asset.Spot)
Might as well use `pairs` whilst we've got it 😄

2023-05-08 06:35 UTC, thrasher- commented on exchanges/hitbtc/hitbtc_wrapper.go
> +		quote := strings.Replace(symbols[x].ID, symbols[x].BaseCurrency, "", 1)
```
func TestFetchTradablePairs(t *testing.T) {
	if _, err := h.FetchTradablePairs(context.Background(), asset.Spot); err != nil {
		t.Fatal(err)
	}
}
```

2023-05-09 00:09 UTC, thrasher- approved these changes

2023-05-09 00:09 UTC, merged