Fill go test
thrasher-corp/gocryptotrader pull request #1223
Opened 2023-06-11 02:41 UTC by romanornr

# PR fill package unit tests 

Included unit tests for the fill package 

F
## Checklist

- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [ x] My changes generate no new warnings
- [ x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally and on Github Actions/AppVeyor with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-06-12 23:11 UTC, gloriousCode requested changes
Lovely, thank you

2023-06-12 23:11 UTC, gloriousCode commented on exchanges/fill/fill_test.go
> +	//}
Please remove

2023-06-12 23:11 UTC, gloriousCode commented on exchanges/fill/fill_test.go
> +	if !errors.Is(err, ErrFeedDisabled) {
```suggestion
	err := fill.Update(testData)
	if !errors.Is(err, ErrFeedDisabled) {
```

2023-06-12 23:34 UTC, shazbert approved these changes
Thanks for the update! ACK once request changes are complete.
![dragon-ball-z-dbz](https://github.com/thrasher-corp/gocryptotrader/assets/9391715/e6102831-d508-4f11-9cef-c7802a139116)

2023-06-13 23:11 UTC, shazbert approved these changes
Approved 👍 thanks @romanornr 

![ccb](https://github.com/thrasher-corp/gocryptotrader/assets/9391715/f8c2308f-ce65-427d-bfa8-7237c504e970)

2023-06-13 23:13 UTC, gloriousCode approved these changes
t
A
C
K
!

2023-06-13 23:42 UTC, thrasher- requested changes
https://github.com/thrasher-corp/gocryptotrader/actions/runs/5260188795/jobs/9506753225#step:7:247 these tests need addressing since this change and then after that this looks good to merge

2023-08-09 01:35 UTC, shazbert requested changes
Thanks for the update some minor nits.

2023-08-09 01:35 UTC, shazbert commented on exchanges/fill/fill_test.go
> +	}
RM as this will block above if there is no reader to the unbuffered channel.

2023-08-09 01:35 UTC, shazbert commented on exchanges/fill/fill_test.go
> +
rm line

2023-08-09 01:35 UTC, shazbert commented on exchanges/fill/fill_test.go
> +
rm

2023-08-09 01:35 UTC, shazbert commented on exchanges/fill/fill_test.go
> +	}
rm as this will block above with unbuffered chan if an attempt is made to send.

2023-08-09 01:35 UTC, shazbert commented on exchanges/fill/fill_test.go
> +
rm

2023-08-09 01:35 UTC, shazbert commented on exchanges/gateio/gateio_test.go
> +	g.Websocket.Trade.Setup(g.Name, true, g.Websocket.DataHandler)
```diff
diff --git a/exchanges/gateio/gateio_test.go b/exchanges/gateio/gateio_test.go
index 87c97bb08..b354940b3 100644
--- a/exchanges/gateio/gateio_test.go
+++ b/exchanges/gateio/gateio_test.go
@@ -54,6 +54,8 @@ func TestMain(m *testing.M) {
        if err != nil {
                log.Fatal("GateIO setup error", err)
        }
+       g.Websocket.Trade.Setup(g.Name, true, g.Websocket.DataHandler)
+       g.Websocket.Fills.Setup(true, g.Websocket.DataHandler)
        request.MaxRequestJobs = 200
        g.Run(context.Background())
        getFirstTradablePairOfAssets()
@@ -2588,8 +2590,6 @@ const wsTradePushDataJSON = `{    "time": 1606292218,     "channel": "spot.trades",       "ev

 func TestWsTradePushData(t *testing.T) {
        t.Parallel()
-       g.SetTradeFeedStatus(true)
-       g.Websocket.Trade.Setup(g.Name, true, g.Websocket.DataHandler)
        if err := g.wsHandleData([]byte(wsTradePushDataJSON)); err != nil {
                t.Errorf("%s websocket trade push data error: %v", g.Name, err)
        }
@@ -2642,7 +2642,7 @@ const wsUserTradePushDataJSON = `{"time": 1605176741,     "channel": "spot.usertrade

 func TestWsUserTradesPushDataJSON(t *testing.T) {
        t.Parallel()
-       g.Websocket.Fills.Setup(true, g.Websocket.DataHandler)
+
        if err := g.wsHandleData([]byte(wsUserTradePushDataJSON)); err != nil {
                t.Errorf("%s websocket users trade push data error: %v", g.Name, err)
        }
@@ -2698,7 +2698,7 @@ const wsFuturesTradesPushDataJSON = `{"channel": "futures.trades","event": "upda
 func TestFuturesTrades(t *testing.T) {
        t.Parallel()
        g.SetTradeFeedStatus(true)
-       g.Websocket.Trade.Setup(g.Name, true, g.Websocket.DataHandler)
+
        if err := g.wsHandleFuturesData([]byte(wsFuturesTradesPushDataJSON), asset.Futures); err != nil {
                t.Errorf("%s websocket push data error: %v", g.Name, err)
        }
@@ -2728,7 +2728,7 @@ const wsFuturesUsertradesPushDataJSON = `{"time": 1543205083,     "channel": "future

 func TestFuturesUserTrades(t *testing.T) {
        t.Parallel()
-       g.Websocket.Fills.Setup(true, g.Websocket.DataHandler)
+
        if err := g.wsHandleFuturesData([]byte(wsFuturesUsertradesPushDataJSON), asset.Futures); err != nil {
                t.Errorf("%s websocket futures user trades push data error: %v", g.Name, err)
        }
```

2023-08-09 01:35 UTC, shazbert commented on exchanges/gateio/gateio_wrapper.go
> +		TradeFeed:              g.Features.Enabled.TradeFeed,
This seems like fills is not set anywhere else in the code base? Suggestion: In stream.WebsocketSetup change Features from being a pointer to websocket capabilities, pass in the &g.Features and in the Setup call, apply it behind the scenes.

2023-08-10 01:18 UTC, shazbert requested changes
Thanks for the changes, one issue for gateio.

2023-08-10 01:18 UTC, shazbert commented on exchanges/gateio/gateio_wrapper.go
> +		TradeFeed:              g.Features.Enabled.TradeFeed,
Not being generated in subs if trade saving is false. There is also no subscriptions it seems for auth websocket but out of scope. 

```diff
diff --git a/exchanges/gateio/gateio_websocket.go b/exchanges/gateio/gateio_websocket.go
index c15c21645..2a339b657 100644
--- a/exchanges/gateio/gateio_websocket.go
+++ b/exchanges/gateio/gateio_websocket.go
@@ -668,7 +668,7 @@ func (g *Gateio) GenerateDefaultSubscriptions() ([]stream.ChannelSubscription, e
                                params["interval"] = kline.HundredMilliseconds
                        }
                        if spotTradesChannel == channelsToSubscribe[i] {
-                               if !g.IsSaveTradeDataEnabled() {
+                               if !g.IsTradeFeedEnabled() {
                                        continue
                                }
                        }
```

2023-08-10 01:37 UTC, shazbert approved these changes
Thank ser! 🖖

2023-08-10 02:33 UTC, merged