Okx: Fix Instrument unmarshal
thrasher-corp/gocryptotrader pull request #1225
Opened 2023-06-12 11:21 UTC by gbjk

This fixes: `json: invalid use of ,string struct tag, trying to unmarshal "" into float64` when TwapSz or other fields are empty, which happened briefly today.

As a DriveBy it also simplifies the exposed Instrument type to native types only.

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [ ] Bug fix (non-breaking change which fixes an issue)

## How has this been tested
- [ ] go test ./... -race
- [ ] golangci-lint run
- [ ] TestInstrument

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally and on Github Actions/AppVeyor with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-06-12 23:30 UTC, gloriousCode approved these changes
tACK! Thanks for a solution to the issue. As discussed, we have PR #1192 which contains a new type to handle the float conversions, but this is a good interim solution before such a type is applied to all of OKx's types.

2023-06-12 23:55 UTC, shazbert requested changes
Thanks heaps! Just a couple of nits.

2023-06-12 23:55 UTC, shazbert commented on exchanges/okx/okx_test.go
> +func TestInstrument(t *testing.T) {
Missing one field
```diff
diff --git a/exchanges/okx/okx_test.go b/exchanges/okx/okx_test.go
index abcce5404..2507a4c98 100644
--- a/exchanges/okx/okx_test.go
+++ b/exchanges/okx/okx_test.go
@@ -3136,4 +3136,90 @@ func TestInstrument(t *testing.T) {
        if err != nil {
                t.Error(err)
        }
+
+       if i.Alias != "" {
+               t.Error("expected empty alias")
+       }
+       if i.BaseCurrency != "" {
+               t.Error("expected empty base currency")
+       }
+       if i.Category != "1" {
+               t.Error("expected 1 category")
+       }
+       if i.ContractMultiplier != "1" {
+               t.Error("expected 1 contract multiplier")
+       }
+       if i.ContractType != "linear" {
+               t.Error("expected linear contract type")
+       }
+       if i.ContractValue != "0.0001" {
+
+               t.Error("expected 0.0001 contract value")
+       }
+       if i.ContractValueCurrency != currency.BTC.String() {
+               t.Error("expected BTC contract value currency")
+       }
+       if !i.ExpTime.IsZero() {
+               t.Error("expected empty expiry time")
+       }
+       if i.InstrumentFamily != "BTC-USDC" {
+               t.Error("expected BTC-USDC instrument family")
+       }
+       if i.InstrumentID != "BTC-USDC-SWAP" {
+               t.Error("expected BTC-USDC-SWAP instrument ID")
+       }
+       if i.InstrumentType != asset.PerpetualSwap {
+               t.Error("expected SWAP instrument type")
+       }
+       if i.MaxLeverage != 125 {
+               t.Error("expected 125 leverage")
+       }
+       if i.ListTime.UnixMilli() != 1666076190000 {
+               t.Error("expected 1666076190000 listing time")
+       }
+       if i.LotSize != 1 {
+               t.Error("expected 1 lot size")
+       }
+       if i.MaxSpotIcebergSize != 100000000.0000000000000000 {
+               t.Error("expected 100000000.0000000000000000 max iceberg order size")
+       }
+       if i.MaxQuantityOfSpotLimitOrder != 100000000 {
+               t.Error("expected 100000000 max limit order size")
+       }
+       if i.MaxQuantityOfMarketLimitOrder != 85000 {
+               t.Error("expected 85000 max market order size")
+       }
+       if i.MaxStopSize != 85000 {
+               t.Error("expected 85000 max stop order size")
+       }
+       if i.MaxTriggerSize != 100000000.0000000000000000 {
+               t.Error("expected 100000000.0000000000000000 max trigger order size")
+       }
+       if i.MaxQuantityOfSpotTwapLimitOrder != 0 {
+               t.Error("expected empty max TWAP size")
+       }
+       if i.MinimumOrderSize != 1 {
+               t.Error("expected 1 min size")
+       }
+       if i.OptionType != "" {
+               t.Error("expected empty option type")
+       }
+       if i.QuoteCurrency != "" {
+               t.Error("expected empty quote currency")
+       }
+       if i.SettlementCurrency != currency.USDC.String() {
+               t.Error("expected USDC settlement currency")
+       }
+       if i.State != "live" {
+               t.Error("expected live state")
+       }
+       if i.StrikePrice != "" {
+               t.Error("expected empty strike price")
+       }
+       if i.TickSize != 0.1 {
+               t.Error("expected 0.1 tick size")
+       }
+       if i.Underlying != "BTC-USDC" {
+               t.Error("expected BTC-USDC underlying")
+       }
 }
diff --git a/exchanges/okx/okx_types.go b/exchanges/okx/okx_types.go
index c78e7e458..3fe2cedde 100644
--- a/exchanges/okx/okx_types.go
+++ b/exchanges/okx/okx_types.go
@@ -275,6 +275,7 @@ type InstrumentsFetchParams struct {
 // Instrument  representing an instrument with open contract.
 type Instrument struct {
        InstrumentType                  asset.Item `json:"instType"`
+       InstrumentFamily                string     `json:"instFamily"`
        InstrumentID                    string     `json:"instId"`
        Underlying                      string     `json:"uly"`
        Category                        string     `json:"category"`

```

2023-06-12 23:55 UTC, shazbert commented on exchanges/okx/okx_type_convert.go
> +
rm line

2023-06-13 01:33 UTC, gbjk commented on exchanges/okx/okx_type_convert.go
> +
✅

2023-06-13 01:33 UTC, gbjk commented on exchanges/okx/okx_test.go
> +func TestInstrument(t *testing.T) {
✅

2023-06-13 04:28 UTC, thrasher- approved these changes
Thanks @gbjk !

2023-06-13 04:47 UTC, shazbert approved these changes
Thanks! 🖖

2023-06-13 05:27 UTC, merged