okx: REST orderbook depth fix
thrasher-corp/gocryptotrader pull request #1228
Opened 2023-06-14 07:11 UTC by gloriousCode

# PR Description
While looking at something completely different I was concerned at how OKx only had 1 entry in its orderbook when on REST. I assumed it was a bad pair, but websocket returns many more results...

Turns out OKx's default depth is **one**: [source](https://www.okx.com/docs-v5/en/#rest-api-market-data-get-order-book)

## Type of change
- [x] Typo fix 

## How has this been tested
- `TestGetOrderBookDepth`

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally and on Github Actions/AppVeyor with my changes

2023-06-14 23:07 UTC, shazbert requested changes
Nice catch 🦅

2023-06-14 23:07 UTC, shazbert commented on exchanges/okx/okx_wrapper.go
> +	orderbookNew, err = ok.GetOrderBookDepth(ctx, instrumentID, 100)
Might as well max it out to `400`

2023-06-15 00:01 UTC, thrasher- approved these changes
Nice!

2023-06-15 00:06 UTC, shazbert approved these changes
tACK! thanks

2023-06-15 00:19 UTC, merged