engine: Adds new helper functions for default exchange deployment.
thrasher-corp/gocryptotrader pull request #1243
Opened 2023-06-27 04:47 UTC by shazbert

# PR Description

De-couples switch case and adds helper function to generate a new value defaulted exchange which can be used straight away for external usage for potential external usages. 

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration and
also consider improving test coverage whilst working on a certain feature or package.

- [x] go test ./... -race
- [ ] golangci-lint run
- [ ] Test X

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally and on Github Actions/AppVeyor with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2023-06-27 23:17 UTC, gloriousCode requested changes

2023-07-20 00:57 UTC, shazbert commented
#1245

2023-10-04 00:41 UTC, gloriousCode requested changes
Thanks for addressing those (much) earlier nits! Just the most pedantic thing from me 💪

2023-10-04 00:41 UTC, gloriousCode commented on engine/helpers.go
> +func GetDefaultExchangeByName(ctx context.Context, name string) (exchange.IBotExchange, error) {
`CreateDefaultExchangeByName`/`NewExchangeByNameWithDefaults` or something since you're not really getting

2023-10-04 01:20 UTC, gloriousCode approved these changes
tACK!

2023-10-04 01:56 UTC, merged