okx: Add fee fields for USDC pairs
thrasher-corp/gocryptotrader pull request #1244
Opened 2023-06-27 23:21 UTC by shazbert

# PR Description

Add missing fee fields for USDC pairs.

Fixes # (issue)

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration and
also consider improving test coverage whilst working on a certain feature or package.

- [ ] go test ./... -race
- [ ] golangci-lint run
- [ ] Test X

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally and on Github Actions/AppVeyor with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-06-28 02:56 UTC, thrasher- requested changes

2023-06-28 02:56 UTC, thrasher- commented on exchanges/okx/okx.go
> +				fee = responses[0].FeeRateMakerUSDT.Float64()
Please also add in support for USDC based on the supplied quote pair and then this is tACK!

2023-06-29 07:07 UTC, gloriousCode approved these changes
tACK for its stated purpose. Though its hardcoded for spot and pairs like BTC-USDC-230929 won't work (but are supported by the API), but that can be an adventure for another day

2023-06-29 07:07 UTC, gloriousCode commented on exchanges/okx/okx.go
> +			} else if fee = responses[0].FeeRateMaker.Float64(); fee == 0 {
I missed the setting in the if statement and couldn't see how fee was being set for LTC-ETH for too long 😭

2023-06-29 07:18 UTC, thrasher- approved these changes
Thanks for making those changes!

2023-06-29 07:19 UTC, merged