common: remove `SimpleTimeFormat` const for time package layout const `DateTime`.
thrasher-corp/gocryptotrader pull request #1246
Opened 2023-07-03 00:56 UTC by shazbert

# PR Description

Also bumps [appveyor windows image](https://www.appveyor.com/docs/windows-images-software/#golang). 🙏 

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration and
also consider improving test coverage whilst working on a certain feature or package.

- [ ] go test ./... -race
- [ ] golangci-lint run
- [ ] Test X

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally and on Github Actions/AppVeyor with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-07-03 01:11 UTC, thrasher- commented on .appveyor.yml
> +stack: go 1.20.3
Revert as it's not used as suggested, but please add a note to change the PATH at https://github.com/thrasher-corp/gocryptotrader/blob/master/.appveyor.yml#L39 instead

2023-07-03 03:53 UTC, thrasher- requested changes
Nice! Looks like there's these ones remaining too:

<img width="249" alt="image" src="https://github.com/thrasher-corp/gocryptotrader/assets/4685270/ac69395f-2226-49b1-912e-f8d79cc795c9">

2023-07-05 06:43 UTC, thrasher- approved these changes
tACK, now that the upstream AppVeyor issue has been resolved: https://github.com/appveyor/ci/issues/3884#issuecomment-1621035858

2023-07-06 01:17 UTC, merged

2023-07-11 11:44 UTC, gbjk commented
@shazbert Need to bump go to 1.20 in [go.mod](https://github.com/thrasher-corp/gocryptotrader/blob/master/go.mod#L3)