bitfinex: fix subscribing issue caused by formatting
thrasher-corp/gocryptotrader pull request #1276
Opened 2023-07-21 02:41 UTC by shazbert

# PR Description

Changes formatting so subscribe works for websocket.

Fixes # (issue)

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration and
also consider improving test coverage whilst working on a certain feature or package.

- [ ] go test ./... -race
- [ ] golangci-lint run
- [ ] Test X

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally and on Github Actions/AppVeyor with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-07-21 05:49 UTC, gloriousCode requested changes
It works!

2023-07-24 00:26 UTC, shazbert commented on exchanges/bitfinex/bitfinex_websocket.go
> +					params["symbol"] = enabledPairs[k].Format(currency.EMPTYFORMAT).Upper().String()
Had no impact on allocation or speed, but it was a visual improvement, scoped it locally.

2023-07-24 03:17 UTC, thrasher- approved these changes
tACK

2023-07-24 03:18 UTC, gloriousCode approved these changes
tAcK1!

2023-07-24 03:26 UTC, merged