Kraken: Fix GetActiveOrders AssetType and CancelOrder wrappers
thrasher-corp/gocryptotrader pull request #1287
Opened 2023-07-29 05:54 UTC by thrasher-

# PR Description

Sets `AssetType` when using `GetActiveOrders` which ensures any methods like DeriveCancel have their asset type set properly. Also adds a default asset type check to CancelOrder.

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## How has this been tested

- [x] go test ./... -race
- [x] golangci-lint run
- [x] REST call

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally and on Github Actions/AppVeyor with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2023-07-30 23:27 UTC, gloriousCode requested changes
Thank you! Could I request one more asset assignment? The func `GetOrderInfo` is missing asset type on the returned order too

2023-07-31 02:09 UTC, shazbert approved these changes
Thank you sir tACK. Opened, checked, cancelled and re-checked. 👍

2023-07-31 02:09 UTC, shazbert commented on exchanges/kraken/kraken_wrapper.go
> +				AssetType:       asset.Spot,
Something I noticed but doesn't stop merge. 

Status is `Unknown` raw response has `open`

Raw response: 

```
{"error":[],"result":{"open":{"ODGFZI-E4GA6-VTPRDR":{"refid":null,"userref":0,"status":"open","opentm":1690768649.226174,"starttm":0,"expiretm":0,"descr":{"pair":"XBTUSDT","type":"buy","ordertype":"limit","price":"10000.0","price2":"0","leverage":"none","order":"buy 0.00010000 XBTUSDT @ limit 10000.0","close":""},"vol":"0.00010000","vol_exec":"0.00000000","cost":"0.00000","fee":"0.00000","price":"0.00000","stopprice":"0.00000","limitprice":"0.00000","misc":"","oflags":"fciq"}}}}
```
type:

```
[{ImmediateOrCancel:false HiddenOrder:false FillOrKill:false PostOnly:false ReduceOnly:false Leverage:0 Price:10000 Amount:0.0001 LimitPriceUpper:0 LimitPriceLower:0 TriggerPrice:0 AverageExecutedPrice:0 QuoteAmount:0 ExecutedAmount:0 RemainingAmount:0.0001 Cost:0 CostAsset: Fee:0 FeeAsset: Exchange:Kraken InternalOrderID:00000000-0000-0000-0000-000000000000 OrderID:ODGFZI-E4GA6-VTPRDR ClientOrderID: AccountID: ClientID: WalletAddress: Type:LIMIT Side:BUY Status:UNKNOWN AssetType:spot Date:2023-07-31 11:57:29.226174116 +1000 AEST CloseTime:0001-01-01 00:00:00 +0000 UTC LastUpdated:0001-01-01 00:00:00 +0000 UTC Pair:XBT_USDT Trades:[]}]
```

2023-08-01 02:48 UTC, shazbert approved these changes
ch ACK!

2023-08-01 03:06 UTC, merged