sync_manager: Update replaced with WebsocketUpdate
thrasher-corp/gocryptotrader pull request #1300
Opened 2023-08-04 03:26 UTC by Beadko

# PR Description

As per the request in PR #1229, the Update was replaced with WebsocketUpdate

Fixes # (issue)

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration and
also consider improving test coverage whilst working on a certain feature or package.

- [ ] go test ./... -race
- [x] golangci-lint run
- [ ] Test X

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally and on Github Actions/AppVeyor with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-08-04 04:55 UTC, shazbert requested changes
Just one nit. Then looks good to go.

2023-08-04 04:55 UTC, shazbert commented on engine/sync_manager_test.go
>  func TestSyncManagerUpdate(t *testing.T) {
TestSyncManagerUpdate -> TestSyncManagerWebsocketUpdate

2023-08-04 05:19 UTC, Beadko commented on engine/sync_manager_test.go
>  func TestSyncManagerUpdate(t *testing.T) {
done :white_check_mark:

2023-08-04 05:20 UTC, shazbert commented on engine/sync_manager_test.go
>  func TestSyncManagerUpdate(t *testing.T) {
🎉

2023-08-04 05:36 UTC, shazbert approved these changes
Changes ACK! Thanks Bea. 🚀

2023-08-06 23:49 UTC, thrasher- requested changes
Just one nit and then this LGTG

2023-08-06 23:49 UTC, thrasher- commented on engine/sync_manager.go
>  // Update notifies the syncManager to change the last updated time for a exchange asset pair
```suggestion
// WebsocketUpdate notifies the syncManager to change the last updated time for a exchange asset pair
```

2023-08-07 06:39 UTC, shazbert approved these changes
ch ACK!

2023-08-07 06:39 UTC, thrasher- commented
Nit fixed!

2023-08-07 06:40 UTC, merged