cli: render orderbooks like an exchange
thrasher-corp/gocryptotrader pull request #1348
Opened 2023-09-11 23:51 UTC by gloriousCode

# PR Description
I have difficulty looking at the CLI way of rendering orderbooks and checking them against exchanges to find faults in our books. So I've added an option to allow it to render like an exchange

From CLI use:
`go run . --it  orderbook getorderbookstream --exchange="binance" --pair="btc-usdt" --asset="spot" --depthlimit=25 --exchangestyle=true`

https://github.com/thrasher-corp/gocryptotrader/assets/9261323/92b2df0c-d926-43e5-9a13-1e5a0c60cd81

Fixes: my eyes

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How has this been tested
- [x] go test ./... -race
- [x] golangci-lint run

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally and on Github Actions/AppVeyor with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-09-12 02:03 UTC, shazbert requested changes
<img width="568" alt="image" src="https://github.com/thrasher-corp/gocryptotrader/assets/9391715/5208b0e9-daaa-4644-be59-d8e8dc5f2126">
Lovely

2023-09-12 02:15 UTC, gloriousCode commented on cmd/gctcli/orderbook.go
> +		depthLimit, err = strconv.ParseInt(c.Args().Get(4), 10, 64)
Are you passing in the field? Can you please provide more info?

2023-09-12 02:20 UTC, shazbert commented on cmd/gctcli/orderbook.go
> +		depthLimit, err = strconv.ParseInt(c.Args().Get(4), 10, 64)
```
go run ./... orderbook getorderbook --exchange=okx --pair='btc-usdt' --asset=spot
2023/09/12 12:00:19 strconv.ParseBool: parsing "": invalid syntax
exit status 1
```

2023-09-12 02:25 UTC, gloriousCode commented on cmd/gctcli/orderbook.go
> +		depthLimit, err = strconv.ParseInt(c.Args().Get(4), 10, 64)
The command does not suggest that the field is optional, but it is logical to add that as a feature. I will infer that that is what you are requesting. I appreciate some of this extra information and request that you provide more in future.

2023-09-12 02:32 UTC, shazbert commented on cmd/gctcli/orderbook.go
> +		depthLimit, err = strconv.ParseInt(c.Args().Get(4), 10, 64)
> The command does not suggest that the field is optional

Sorry I saw they had default values and thought they were. 🤷 
```
   --exchangestyle     renders the books like on an exchange website (default: false)
   --depthlimit value  limit how deep the book rendering is, max 100 - only works if exchangestyle is true (default: 0)
```

>  I appreciate some of this extra information and request that you provide more in future.
Sure thing 👍

2023-09-12 02:42 UTC, gloriousCode commented on cmd/gctcli/orderbook.go
> +		depthLimit, err = strconv.ParseInt(c.Args().Get(4), 10, 64)
😭 I cannot change those, but it didn't make sense that they weren't optional before. It has been addressed

2023-09-13 03:24 UTC, shazbert approved these changes
Tested ACK. Thanks for the changes.

2023-09-14 00:10 UTC, thrasher- approved these changes
So pretty, tACK!

<img width="587" alt="image" src="https://github.com/thrasher-corp/gocryptotrader/assets/4685270/19748f15-9d4c-4f05-a9c2-7e44aa2c4522">

2023-09-14 00:10 UTC, merged