requester: purge max request jobs
thrasher-corp/gocryptotrader pull request #1379
Opened 2023-10-23 22:41 UTC by shazbert

# PR Description

* Removes friction point while tracking how many HTTP outbound jobs are run in parallel. This is generally not needed because of the rate limiting systems in place and allows you to spawn pending routines which will queue and exceed this amount especially in the confines of rolling window data on start-up (e.g. fee synchronisation).

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration and
also consider improving test coverage whilst working on a certain feature or package.

- [ ] go test ./... -race
- [ ] golangci-lint run
- [ ] Test X

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally and on Github Actions/AppVeyor with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-01-19 01:45 UTC, gloriousCode requested changes
I think it is reasonable for a user to be able to set their own limits/manage request frequency. I don't think the current system of throwing away the request is the best way of handling it. I can see room for improvement for such a system to manage burstiness, but if that ever happens - PRs welcome
So in that sense, I'm comfortable with the removal of this system

2024-01-19 01:45 UTC, gloriousCode commented on exchanges/bybit/bybit_live_test.go
>  	"testing"
Please remove in mock test

2024-01-19 01:45 UTC, gloriousCode commented on exchanges/binance/binance_mock_test.go
Please remove in live test

2024-01-19 03:18 UTC, gloriousCode approved these changes
tACK m8

2024-01-21 04:50 UTC, thrasher- approved these changes
tACK. This was originally intended to cap a person from spamming thousands of go routines and subsequent requests by accident but most of the important exchanges support a rate limiter now. I'd still say we should have some kind of limit on the ones which don't but can be addressed in a separate PR.

2024-01-22 01:48 UTC, merged