Gateio: Add function GetHistoricalFundingRates
thrasher-corp/gocryptotrader pull request #1385
Opened 2023-11-03 00:00 UTC by shazbert

# PR Description

Based off branch #1339 

Adds function in gateio `GetHistoricalFundingRates`

Fixes # (issue)

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration and
also consider improving test coverage whilst working on a certain feature or package.

- [ ] go test ./... -race
- [ ] golangci-lint run
- [ ] Test X

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally and on Github Actions/AppVeyor with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-11-07 02:15 UTC, gloriousCode requested changes
Thanks for expanding things

2023-11-07 02:15 UTC, gloriousCode commented on exchanges/gateio/gateio_wrapper.go
> +	records, err := g.GetFutureFundingRates(ctx, r.PaymentCurrency.String(), fPair, 0 /*Defaults to returning maximum records*/)
I get 100 back with `0`, and 1000 back when setting it. Could be a case by case basis, but better to put in the limit

2023-11-20 04:53 UTC, shazbert commented on exchanges/gateio/gateio_test.go
> +		t.Fatalf("received: %v, expected: %v", err, common.ErrStartAfterEnd)
Fine, I guess I will have to then.

2023-11-21 05:09 UTC, gloriousCode approved these changes
tACK! TySB

2023-11-21 23:44 UTC, thrasher- approved these changes
tACK, looking good!
<img width="984" alt="image" src="https://github.com/thrasher-corp/gocryptotrader/assets/4685270/217c5fb3-ac0c-4073-ba65-c277d91749b7">

2023-11-21 23:52 UTC, merged