Engine: Fix panic when exchange errors
thrasher-corp/gocryptotrader pull request #1400
Opened 2023-11-16 06:52 UTC by gbjk

BTSE is currently failing startup.
This fix simply prevents that from panicing.

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [x] Bug fix (non-breaking change which fixes an issue)

- [x] go test ./... -race
- [x] golangci-lint run

2023-11-17 02:46 UTC, gloriousCode requested changes
I think I'd prefer a more thorough fix. BTSE actually cannot run at all because of this error, its not about this one helper test.

BTSE has added some jank surrounding the currency PIT. We build a currency using {{base}} {{quote}} and not from {{symbol}} which misses the issue and ends up creating a duplicate, preventing BTSE from being setup

[So I would propose this fix](https://gist.github.com/gloriousCode/4effc0594b1f0b465549b550ecd72ee6). Yes, its annoying to need to do specific code like this and you are free to improve it, but this will allow BTSE to actually start as an exchange. You can test this by trying to retrieve the ticker for PIT-USD vs M_PIT-USD and see that BTSE will return an error for PIT-USD (it will also 301 when you try to view it on the site)

With the diff applied, the helper test works, but I also don't have a problem with your fix, its just too narrow

2023-11-17 04:12 UTC, gbjk commented
Yep; I'm working on BTSE.

I still recommend we fix this issue separately/atomically.
We don't want it reverted or confused with the BTSE issue, and it's a standalone issue with the engine test.

2023-11-19 21:48 UTC, gloriousCode approved these changes
tACK! Big fan of not panicking

2023-11-19 22:44 UTC, shazbert approved these changes
LGTM! ACK

2023-11-19 22:44 UTC, shazbert commented on engine/helpers_test.go
> +	_, err := NewExchangeByNameWithDefaults(context.Background(), "moarunlikelymeow")
🐈

2023-11-21 01:46 UTC, thrasher- approved these changes
Thanks @gbjk !

2023-11-21 01:47 UTC, merged