gateio: fix unmarshal bug and update fields
thrasher-corp/gocryptotrader pull request #1404
Opened 2023-11-23 00:37 UTC by shazbert

# PR Description

fix unmarshal bug and update fields

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration and
also consider improving test coverage whilst working on a certain feature or package.

- [ ] go test ./... -race
- [ ] golangci-lint run
- [ ] Test X

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally and on Github Actions/AppVeyor with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-11-24 05:54 UTC, shazbert commented
Problem with market deployment.

2024-02-06 00:04 UTC, gloriousCode requested changes
Only minor things right now

2024-02-06 03:42 UTC, shazbert commented on exchanges/gateio/gateio_wrapper.go
> +					ExecutionNote:        futuresOrders[x].Text,
Yeah this is strange when you don't supply a client order id it comes back `"text":"api",` or front end. When you do it returns the client order ID like expected I will purge this.

2024-02-28 01:38 UTC, gloriousCode commented on exchanges/gateio/gateio_wrapper.go
> +				var pair currency.Pair
Thanks for making those changes! I'm happy with the PR overall, just waiting on this

2024-02-28 04:58 UTC, gloriousCode commented
Happy with changes, just need exchange_wrapper_standards addressing: https://github.com/thrasher-corp/gocryptotrader/actions/runs/8074480255/job/22059833368?pr=1404#step:9:292
For Kucoin, the &order.Submit needs leverage there since you now require it to be sent
For gateio, GetActiveOrders now requires a pair, but the error is not something exchange_wrapper_standards can access. Is there a better error to select?

2024-03-01 04:43 UTC, gloriousCode approved these changes
# 🌯  🌞 
tACK!

2024-03-04 07:01 UTC, thrasher- requested changes
Lovely! Some minor nitters

2024-03-06 02:06 UTC, thrasher- approved these changes
Thanks for making those changes

2024-03-06 02:06 UTC, merged