request/nonce: update to stop two consecutive mutex lock calls.
thrasher-corp/gocryptotrader pull request #1506
Opened 2024-03-20 01:03 UTC by shazbert

# PR Description

Requires #1486 

Attempts to improve flow when deriving a nonce. 

Fixes # (issue)

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration and
also consider improving test coverage whilst working on a certain feature or package.

- [ ] go test ./... -race
- [ ] golangci-lint run
- [ ] Test X

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally and on Github Actions with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-03-24 23:11 UTC, gloriousCode requested changes
The double lock only appears to occur on the first time a request nonce is used. Which is once per exchange

2024-04-10 05:51 UTC, gloriousCode approved these changes
tACK! Thanks for improving things for my 💩 💻

2024-04-10 05:51 UTC, gloriousCode commented on exchanges/request/request_test.go
> +func BenchmarkGetNonce(b *testing.B) {
Thanks for making it more performant than `master`:
```
BenchmarkGetNonce-10    	14245105	        83.73 ns/op
```

2024-04-12 06:49 UTC, thrasher- approved these changes
tACK, nice simplification🌞

2024-04-12 06:54 UTC, merged