Bugfix/bitstamp add missing fields
thrasher-corp/gocryptotrader pull request #1510
Opened 2024-03-30 06:55 UTC by Beadko

# PR Description

Issues picked up during PR#1423 but were considered out of scope. In addition, the main error checks changed from assert to require.

Fixes # (issue)

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration and
also consider improving test coverage whilst working on a certain feature or package.

- [x] go test ./... -race
- [x] golangci-lint run
- [x] Test Bitstamp_test

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally and on Github Actions with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-03-30 07:01 UTC, Beadko commented on exchanges/bitstamp/bitstamp_test.go
> +			assert.Equal(t, "BTC/USD", res.Market, "Market should match")
One comment was regarding the Currency is not set for []Order type. Bitstamp open orders for markets do not include currency in the response so I have added "Market" which was missing

2024-04-10 05:43 UTC, gloriousCode requested changes
Nice work Beadko!

2024-04-10 13:47 UTC, Beadko commented on exchanges/bitstamp/bitstamp_test.go
> -	assert.NoError(t, err, "GetFee should not error")
Added

2024-04-12 01:17 UTC, gloriousCode requested changes
Just one really minor thing 😄

2024-04-12 01:17 UTC, gloriousCode commented on exchanges/bitstamp/bitstamp_test.go
> +	}
```suggestion
	if !mockTests {
    		sharedtestvalues.SkipTestIfCredentialsUnset(t, b)
	}
	fee, err := b.GetFee(context.Background(), feeBuilder)
```

2024-04-14 07:15 UTC, Beadko commented on exchanges/bitstamp/bitstamp_test.go
> +	}
done :)

2024-04-14 22:02 UTC, gloriousCode approved these changes
tACK! Thanks beadko!

2024-04-14 23:24 UTC, shazbert requested changes
One thing from me everything else looks good. Nice work.

2024-04-14 23:24 UTC, shazbert commented on exchanges/bitstamp/bitstamp_types.go
> +	Status          string
missing json tag

2024-05-05 09:45 UTC, Beadko commented on exchanges/bitstamp/bitstamp_types.go
> +	Status          string
oops,  added now.

2024-05-05 23:33 UTC, shazbert approved these changes
Thanks Bea! changes tack.

2024-05-06 01:05 UTC, thrasher- approved these changes
tACK mock tests on and off (unauth). Thanks @Beadko !

2024-05-06 01:05 UTC, merged