gateio: update FuturesAccount struct
thrasher-corp/gocryptotrader pull request #1532
Opened 2024-05-03 00:24 UTC by shazbert

# PR Description

Updates struct to include all fields and converts string fields that hold a float to types.Number for easier conversion. 

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration and
also consider improving test coverage whilst working on a certain feature or package.

- [ ] go test ./... -race
- [ ] golangci-lint run
- [ ] Test X

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally and on Github Actions with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-05-21 06:15 UTC, shazbert commented
Got an update to the fee struct coming through. PAUSE. 🙏

2024-05-21 06:21 UTC, shazbert commented
It is now pushed you can all relax and get back to reviewing this massive PR. 👍

2024-06-11 01:31 UTC, gloriousCode requested changes
Looks like there are a few more structs that could be changed to use Time. `WsOrderbookTickerData.UpdateTimeMS`, `WsCandlesticks.Timestamp`, `WsResponse.Time` etc etc etc but otherwise this is fine 🔥 🐶

2024-06-14 01:03 UTC, thrasher- approved these changes
Once the remaining time vars which @gloriousCode mentioned are resolved, this looks good to go!

2024-06-14 01:05 UTC, thrasher- commented on exchanges/gateio/gateio_convert.go
> +		return fmt.Errorf("cannot unmarshal %T into GateioTime", val)
```suggestion
		return fmt.Errorf("cannot unmarshal %T into Time", val)
```

2024-06-14 01:44 UTC, thrasher- approved these changes
Changes ACK, thanks!

2024-06-14 01:50 UTC, gloriousCode approved these changes
Shazbert, thank you for taking the `Time` for these fixes. tACK

2024-06-14 01:54 UTC, merged