currency: Making PairsAdd Variadic
thrasher-corp/gocryptotrader pull request #1566
Opened 2024-06-11 05:51 UTC by cranktakular

# PR Description

Alters the Add method on currency.Pairs to accept an arbitrary amount of Pair objects as input, to enable mass-scale safe adding of pairs without breaking code that currently uses this function.

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [x] New feature (non-breaking change which adds functionality)

## How has this been tested

- [x] go test ./... -race
- [x] golangci-lint run
- [x] Test X

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally and on Github Actions with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2024-06-14 01:13 UTC, shazbert requested changes
This is much betterer! Thank you 🫡

2024-06-14 01:13 UTC, shazbert commented on currency/pairs_test.go
> +	}
There's a non zero chance of append not allocating a separate slice and you get weird effects and spooky ghosts 👻. Here's a test for it:

```diff
diff --git a/currency/pairs_test.go b/currency/pairs_test.go
index 33d3fa411..1eaa494f6 100644
--- a/currency/pairs_test.go
+++ b/currency/pairs_test.go
@@ -3,6 +3,7 @@ package currency
 import (
        "encoding/json"
        "errors"
+       "fmt"
        "testing"

        "github.com/stretchr/testify/assert"
@@ -282,6 +283,43 @@ func TestAdd(t *testing.T) {
        if len(pairs) != 6 {
                t.Error("TestAdd unexpected result")
        }
+
+       pairsWithExtraBaggage := make(Pairs, 0, len(pairs)+3)
+       pairsWithExtraBaggage = append(pairsWithExtraBaggage, pairs...)
+
+       brain := NewPair(BRAIN, USD)
+       withBrain := pairsWithExtraBaggage.Add(NewPair(BTC, LTC), brain)
+       if len(pairs) != 6 {
+               t.Error("TestAdd unexpected result")
+       }
+
+       assert.Equal(t, brain, withBrain[len(withBrain)-1])
+
+       badger := NewPair(BADGER, USD)
+       withBadger := pairsWithExtraBaggage.Add(NewPair(BTC, LTC), badger)
+       if len(pairs) != 6 {
+               t.Error("TestAdd unexpected result")
+       }
+
+       assert.Equal(t, badger, withBadger[len(withBadger)-1])
+
+       babyDoge := NewPair(BABYDOGE, USD)
+       withBabyDoge := pairsWithExtraBaggage.Add(NewPair(BTC, LTC), babyDoge)
+       if len(pairs) != 6 {
+               t.Error("TestAdd unexpected result")
+       }
+
+       assert.Equal(t, babyDoge, withBabyDoge[len(withBabyDoge)-1])
+
+       // check bleed back
+
+       assert.Equal(t, brain, withBrain[len(withBrain)-1])
+       assert.Equal(t, badger, withBadger[len(withBadger)-1])
+
+       fmt.Println(withBadger)
+       fmt.Println(withBrain)
+       fmt.Println(withBabyDoge)
+       fmt.Println(pairsWithExtraBaggage)
 }
```

slices.Clone call before or make(Pairs, 0, len(p) + len(Pairs) then copy original acrost.

2024-06-18 03:21 UTC, cranktakular commented
Implementation overhaul risks breaking uses of this function, but as far as I can tell I didn't cause any new issues.

2024-06-19 23:14 UTC, shazbert requested changes
Thanks for improving things well done, added a suggestion.

2024-06-19 23:14 UTC, shazbert commented on currency/pairs.go
> +	p2 := make(Pairs, len(pairs))
suggestion: Can consolidate your idea a little bit more. Let me know if this works.

```go
merge := append(slices.Clone(p), pairs...)
var filterInt int
for x := len(p); x < len(merge); x++ {
	if !merge[:len(p)+filterInt].Contains(merge[x], true) {
		merge[len(p)+filterInt] = merge[x]
		filterInt++
	}
}
return merge[:len(p)+filterInt]
```

2024-06-26 22:40 UTC, shazbert requested changes
Thanks for the changes! Just some nits on the most recent commit.

2024-06-26 22:40 UTC, shazbert commented on exchanges/sharedtestvalues/sharedtestvalues.go
> +	enabledPairs.Add(cp...)
```go
availPairs = availPairs.Add(cp...)
enabledPairs = enabledPairs.Add(cp...)
```

2024-06-26 22:40 UTC, shazbert commented on exchanges/subscription/subscription.go
> +	s.Pairs.Add(pairs...)
s.Pairs = s.Pairs.Add(pairs...)

2024-07-02 23:12 UTC, shazbert requested changes
One thing left over then looks good to go.

```diff
diff --git a/backtester/funding/trackingcurrencies/trackingcurrencies_test.go b/backtester/funding/trackingcurrencies/trackingcurrencies_test.go
index 751089154..b3f187562 100644
--- a/backtester/funding/trackingcurrencies/trackingcurrencies_test.go
+++ b/backtester/funding/trackingcurrencies/trackingcurrencies_test.go
@@ -53,12 +53,8 @@ func TestCreateUSDTrackingPairs(t *testing.T) {
        cp3 := currency.NewPair(currency.LTC, currency.BTC)
        exchB := exch.GetBase()
        eba := exchB.CurrencyPairs.Pairs[a]
-       eba.Available = eba.Available.Add(cp)
-       eba.Enabled = eba.Enabled.Add(cp)
-       eba.Available = eba.Available.Add(cp2)
-       eba.Enabled = eba.Enabled.Add(cp2)
-       eba.Available = eba.Available.Add(cp3)
-       eba.Enabled = eba.Enabled.Add(cp3)
+       eba.Available = eba.Available.Add(cp, cp2, cp3)
+       eba.Enabled = eba.Enabled.Add(cp, cp2, cp3)
        eba.AssetEnabled = convert.BoolPtr(true)

        err = em.Add(exch)
```

2024-07-09 23:55 UTC, shazbert approved these changes
Thank you sir, well done!

2024-07-10 00:22 UTC, gloriousCode approved these changes
`Pairs.Add(t, ACK)`

2024-07-12 04:35 UTC, thrasher- approved these changes
Nice work @cranktakular !

2024-07-12 04:36 UTC, merged