common: add error context
thrasher-corp/gocryptotrader pull request #1567
Opened 2024-06-14 03:05 UTC by shazbert

# PR Description

Adds verbose output to error using runtime package information. 

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration and
also consider improving test coverage whilst working on a certain feature or package.

- [ ] go test ./... -race
- [ ] golangci-lint run
- [ ] Test X

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally and on Github Actions with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-06-18 00:20 UTC, gloriousCode requested changes
I nice little helper for when developing things, but I wouldn't really want to see this around in main codebase

2024-06-18 00:20 UTC, gloriousCode commented on common/common_test.go
> +	}
Please don't make this test fail due to the line numbers. Almost any changes to this file will cause this to fail. Just check that it's a number if you must do something with it.

2024-07-10 01:45 UTC, gloriousCode requested changes
Thanks for updating those tests 🌈

2024-07-23 01:55 UTC, gloriousCode approved these changes
ACK changes 🌈 
[Interesting](https://github.com/thrasher-corp/gocryptotrader/actions/runs/9951504826/job/27491117129?pr=1567#step:10:288) [races](https://github.com/thrasher-corp/gocryptotrader/actions/runs/9951504826/job/27491117516?pr=1567#step:10:2411)!

2024-07-28 23:24 UTC, shazbert commented
Opted to not introduce code that is not integrated into library and never will be. Will open a PR to assign at the logger level if the the caller functionality is needed.

2024-07-28 23:24 UTC, closed without merging