Gateio: Add unified account fetching
thrasher-corp/gocryptotrader pull request #1573
Opened 2024-07-01 23:13 UTC by shazbert

# PR Description

Adds unified account fetching. This is just a mapping implementation, I don't have unified account enabled so I am not going to attempt to add this to the wrapper just yet, until I get an account that supports it. But it at least gives people the option to use it. 

Can close if testing requirements need to be done this is just cherry picked from another branch. 

Fixes # (issue)

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration and
also consider improving test coverage whilst working on a certain feature or package.

- [🙅] go test ./... -race 
- [🙅] golangci-lint run
- [🙅] Test X

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally and on Github Actions with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-07-10 00:38 UTC, gloriousCode requested changes
Maybe by 2035 exchanges will catch up to FTX and support unified margin by default

2024-07-10 00:38 UTC, gloriousCode commented on exchanges/gateio/gateio_types.go
> +	TotalLiab      types.Number `json:"total_liab"`
Liab->Liabilities for the struct

2024-07-10 00:38 UTC, gloriousCode commented on exchanges/gateio/gateio_types.go
> +	SpotInUse      types.Number `json:"spot_in_use"`
Missing `funding` and `funding_version`, example json doesn't have it, but you can 🚓

2024-07-10 00:38 UTC, gloriousCode commented on exchanges/gateio/gateio_types.go
> +	SpotHedge                  bool                             `json:"spot_hedge"`
Liab->Liabilities.

2024-07-10 00:38 UTC, gloriousCode commented on exchanges/gateio/gateio.go
> +	return &response, g.SendAuthenticatedHTTPRequest(ctx, exchange.RestSpot, spotPrivateEPL, http.MethodGet, "unified/accounts", params, nil, &response)
Put path with others

2024-07-10 00:38 UTC, gloriousCode commented on exchanges/gateio/gateio_types.go
> +type UnifiedUserAccount struct {
Missing `use_funding`, missing `refresh_time`

2024-07-22 04:23 UTC, gloriousCode approved these changes
[ticky tACKY](https://www.youtube.com/watch?v=hNmTAxMLCZg)

2024-07-23 03:19 UTC, thrasher- approved these changes
All fields match docs, utACK 👍

2024-07-23 03:21 UTC, merged