Subscriptions: Fix subscription.Clone Params and Pairs
thrasher-corp/gocryptotrader pull request #1582
Opened 2024-07-17 07:55 UTC by gbjk

Fixes Clone() affecting the original and not the clone for Pairs and Params.
That actually meant it would pass tests, and kinda work, but not in the way expected, and definitely not thread safe on the original parent

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

2024-07-17 22:07 UTC, gloriousCode requested changes
A little whoopsie that went unnoticed 🌈

2024-07-17 22:07 UTC, gloriousCode commented on exchanges/subscription/subscription.go
>  		QualifiedChannel: s.QualifiedChannel,
```suggestion

```
Removes the double-assign and potentially what allowed us to get confused

2024-07-17 22:09 UTC, gloriousCode commented on exchanges/subscription/subscription.go
>  		Pairs:            s.Pairs,
```suggestion
```
Removes the double-assign and potentially what allowed us to get confused.
Do the same for `Params` too

2024-07-18 01:40 UTC, gloriousCode approved these changes
tACK!

2024-07-18 23:33 UTC, shazbert approved these changes
Nice fix! tACK.

2024-07-18 23:33 UTC, shazbert commented on exchanges/subscription/subscription.go
> -	s.Params = maps.Clone(s.Params)
😬

2024-07-19 00:36 UTC, thrasher- approved these changes
Nice gotcha fix + additional test coverage

2024-07-19 00:36 UTC, merged