orders/gateio: Add extraction method `GetTradeAmount` order.Submit struct
thrasher-corp/gocryptotrader pull request #1584
Opened 2024-07-19 06:00 UTC by shazbert

# PR Description

I had both values populated for Amount and QuoteAmount and when it detected base amount it kept base amount. So this reduces a fat finger chance.  😆 

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration and
also consider improving test coverage whilst working on a certain feature or package.

- [ ] go test ./... -race
- [ ] golangci-lint run
- [ ] Test X

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally and on Github Actions with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-07-22 04:18 UTC, gloriousCode requested changes
https://www.youtube.com/watch?v=4o6vBpI5158
WHOOPS

2024-07-22 04:18 UTC, gloriousCode commented on exchanges/order/orders.go
> +func (s *Submit) GetTradeAmount(tr protocol.TradingRequirements) float64 {
Unless you have experienced this against other exchanges, this function looks like it should be localised to gateIO rather than part of the submit

2024-07-22 04:27 UTC, gloriousCode approved these changes
I have changed my tune, those specific rules are set at the wrapper level already

2024-07-23 04:29 UTC, thrasher- approved these changes
Nice little helper method!

2024-07-23 04:30 UTC, merged