Bybit: Fix UpdateAccountInfo coin balance issue, improve GetWalletBalance and enhance test coverage
thrasher-corp/gocryptotrader pull request #1588
Opened 2024-07-24 05:38 UTC by thrasher-

# PR Description

Thanks to Lord Romano for identifying this issue! This PR addresses a coin balance problem in UpdateAccountInfo, improves GetWalletBalance fields, enhances test coverage and makes Bybit use the new test exchange helpers.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How has this been tested

- [x] go test ./... -race
- [x] golangci-lint run

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally and on Github Actions with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2024-07-24 23:19 UTC, gloriousCode requested changes
Thanks! Endpoints worked, but I have no money there so its an empty range 😭 
All API properties accounted for. Just one massive showstopper in line with CrowdStrike

2024-07-24 23:19 UTC, gloriousCode commented on exchanges/bybit/bybit_types.go
> +			UnrealisedPnl           types.Number  `json:"unrealisedPnl"`
```suggestion
			UnrealisedPNL           types.Number  `json:"unrealisedPnl"`
```
Huge issue, but puts it in line with everything else

2024-07-24 23:59 UTC, gloriousCode approved these changes
[tACK!](https://www.youtube.com/watch?v=lA-UBd6w9Yo)

2024-07-25 23:47 UTC, shazbert approved these changes
tACK!

2024-07-29 02:36 UTC, merged