gateio: Add websocket request functions for futures trading (btc and usdt margined)
thrasher-corp/gocryptotrader pull request #1603
Opened 2024-08-06 05:11 UTC by shazbert

# PR Description

* Adds functions for trading using websocket connection. 
* Correctly routes outbound requests through available connection dependant on asset settlement 

#### Requires dependency #1598

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration and
also consider improving test coverage whilst working on a certain feature or package.

- [ ] go test ./... -race
- [ ] golangci-lint run
- [ ] Test X

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally and on Github Actions with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-12-31 00:12 UTC, gloriousCode requested changes
Nice stuff. Haven't done a test run yet. Will look into testnet usage

2024-12-31 01:16 UTC, shazbert commented on exchanges/gateio/gateio_wrapper.go
> +		return resp, nil
I also set resp.Date twice here. I am sure that must be for efficiency reasons.

2024-12-31 01:18 UTC, shazbert commented on exchanges/gateio/gateio_test.go
> +		{`{"channel":"futures.orders","event":"update","time":1541505434,"time_ms":1541505434123,"result":[{"contract":"BTC_USD","create_time":1628736847,"create_time_ms":1628736847325,"fill_price":40000.4
Yeah I got no idea from memory will test it out again. 👀

2024-12-31 01:18 UTC, shazbert commented on exchanges/request/request.go
> +	if !verbose {
Bless you

2025-01-02 04:08 UTC, shazbert commented on exchanges/gateio/gateio_wrapper.go
> +		return resp, nil
Hopefully addressed this comment [here](https://github.com/thrasher-corp/gocryptotrader/pull/1603/commits/033893018f147dc34378a3e2d1b16ac7af63719d)

2025-02-21 01:02 UTC, gloriousCode requested changes
I tested everything except submitorders because I'm not spending my fart tokens on fees, thank you

2025-02-21 03:04 UTC, shazbert commented on exchanges/gateio/gateio_wrapper.go
> +		return nil, errNoResponseReceived
Happy for suggestions, it should error way before this, and it it's only there to ensure it doesn't panic if the endpoint goes weird.

2025-02-21 03:42 UTC, shazbert commented on exchanges/gateio/gateio_wrapper.go
> +		}
I will add in the test for this

2025-02-28 01:15 UTC, gloriousCode commented on exchanges/gateio/gateio_wrapper.go
> +		return nil, errNoResponseReceived
You must be pulling my leg 😄 `common.ErrNoResponse` or `common.ErrNoResults`

2025-02-28 01:20 UTC, shazbert commented on exchanges/gateio/gateio_wrapper.go
> +		return nil, errNoResponseReceived
I thought you wanted a completely different error coming from lower down or it rephrased differently 😭

2025-02-28 01:21 UTC, gloriousCode commented on exchanges/gateio/gateio_wrapper.go
> +		out = append(out, &order.SubmitResponse{
mkr and tkr fee _may_ be useful for example

2025-03-03 00:09 UTC, gloriousCode approved these changes
tACK thanks for listening when my verbose is enabled

2025-03-03 08:10 UTC, gbjk commented on exchanges/gateio/gateio_types.go
> +	StpAct       string        `json:"stp_act,omitempty"`
Can we expand `StpAct` please?

2025-03-03 08:13 UTC, gbjk commented on exchanges/gateio/gateio_websocket.go
> +			// response.
Nit: Think this is implicit
```suggestion
```

2025-03-03 08:19 UTC, gbjk commented on exchanges/gateio/gateio_websocket.go
> +	endResponse := responses[len(responses)-1]
Think we can be clearer about this.
```suggestion
	// responses may include an ack resp, which we skip
	resp := responses[len(responses)-1]
```
However, might we want to assert len(responses) <= 2 ?

2025-03-03 08:21 UTC, gbjk commented on exchanges/gateio/gateio_websocket_request_futures.go
> +	errInvalidSide                = errors.New("invalid side")
Shouldn't we use `order.ErrSideIsInvalid` ?

2025-03-03 22:24 UTC, shazbert commented on exchanges/exchange.go
> +func (*Base) WebsocketSubmitOrder(context.Context, *order.Submit) (*order.SubmitResponse, error) {
When we start to move over to to the other interface functions for example `ModifyOrder` are we going to have the same convention `ModifyWebsocketOrder` or should Websocket be tacked on the end instead for all of these functions? So its `ModifyOrderWebsocket`, `CancelOrderWebsocket` etc.

2025-03-03 23:16 UTC, shazbert commented on exchanges/gateio/gateio_test.go
> +			order: []byte(`{"left":"0","update_time":"1735720637","amount":"0.0001","create_time":"1735720637","price":"0","finish_as":"filled","time_in_force":"ioc","currency_pair":"BTC_USDT","type":"market"
Its actually a subset of the json returned because I was lazy at filling out the struct itself. So I have consolidated the tests and unmarshalled into one slice so I can test your nit [here](https://github.com/thrasher-corp/gocryptotrader/pull/1603#discussion_r1976998833).

2025-03-04 02:13 UTC, gbjk commented on exchanges/exchange.go
> +func (*Base) WebsocketSubmitOrder(context.Context, *order.Submit) (*order.SubmitResponse, error) {
Good question. In isolation "WebsocketPlaceOrder" sounds wrong, but in the context of others it's not so clear.
Actually, what feels right here is:
* An interface of order methods
* An exchange itself can satisfy that
* It's websocket can also satisfy that, as an embedded thing, so Gateio's Websocket would be it's own type embedding a websocket pointer.
* Then everything can do g.Websocket.SubmitOrder()

That feels cute, but OOS, right?

If so, leave it, and we can sniff it later.

2025-03-04 03:26 UTC, shazbert commented on exchanges/exchange.go
> +func (*Base) WebsocketSubmitOrder(context.Context, *order.Submit) (*order.SubmitResponse, error) {
Yeah sounds good. The challenge we might come across later is how does that translate to the interface for IBotExchange. So when we call exch.SubmitOrder(...) is fine, but do we then need to get Websocket first, handle error and then ws.SubmitOrder(...). Which is slightly clunky. 

Yeah can leave it for now if that's okay?

2025-03-04 05:54 UTC, gbjk requested changes
Think my biggest thing here is about the derive funcs taking arrays when we're going to always ignore [1:].
Otherwise I think this would be an approval with nits 🙂

2025-03-04 05:54 UTC, gbjk commented on exchanges/gateio/gateio_types.go
> +	StpAct       string        `json:"stp_act,omitempty"`
Jesus. That needed expanding! Thanks!

2025-03-04 05:54 UTC, gbjk commented on exchanges/gateio/gateio_websocket.go
> +	endResponse := responses[len(responses)-1]
Sounds good 👍

2025-03-04 05:54 UTC, gbjk commented on exchanges/gateio/gateio_test.go
> +				[]byte(`{"left":"1","update_time":"1735784755","amount":"1","create_time":"1735784755","price":"100","finish_as":"open","time_in_force":"gtc","currency_pair":"GT_USDT","type":"limit","account":"s
To be clear: I was suggesting this goes into `testdata/wsFuturesOrders.json` or something, and then use `os.ReadFile` and iterate it, and then use index to switch what you're expecting.

No big deal, but I like to avoid (larger) chunks of json in go test files.
Also faster to toggle json expansion quickly on them when they're in a file containing just json objects.
I'd probably put the Spot ones in there as well, and iterate the whole thing in one test, since they feel convergent

2025-03-04 05:54 UTC, gbjk commented on exchanges/gateio/gateio_wrapper.go
> +func (g *Gateio) deriveSpotWebsocketOrderResponses(responses []WebsocketOrderResponse) ([]*order.SubmitResponse, error) {
I'm not clear why we're receiving and returning a slice when we're going to ignore `[1:]` on lines L2621 and 2594.

Seems to me like it should be deriveResponse, accepting a singe OrderResponse, and we should pass got[0] into it, and probably error on len(got) > 1.
Am I missing something?

2025-03-04 05:54 UTC, gbjk commented on exchanges/gateio/gateio_wrapper.go
> +		// the base currency the base currency amount is used.
This comment feels superfluous, because we're not doing anything related to that logic here.
```suggestion
```

Also / otherwise: I'm not sure what about this was market order related :)
Would also amount to just `Buy in Quote currency, Sell in Base`

2025-03-04 05:54 UTC, gbjk commented on exchanges/interfaces.go
> +	// WebsocketSubmitOrder submits an order via the websocket connection
Nit: This feels unnecessary
```suggestion
```

2025-03-04 05:54 UTC, gbjk commented on exchanges/order/order_types.go
> +	Purchased float64
```suggestion
	Purchased float64 	// Buy in Quote currency, Sell in Base
```

2025-03-04 06:01 UTC, gbjk commented on exchanges/exchange.go
> +func (*Base) WebsocketSubmitOrder(context.Context, *order.Submit) (*order.SubmitResponse, error) {
Agreed. OOS.

Good point. Safety versus convenience of using `e.GetWebsocket().SubmitOrder()` vs handling the error from `GetWebsocket()` I suppose.

Though actually, I think this might be the first time a `NilGuard` on `*Websocket` would work very nicely inside the interface implementing funcs.

2025-03-05 03:14 UTC, gbjk requested changes
I've now reviewed everything, but I felt snow-blind towards the end.
I'll need to revisit it once more.

Once again, great work.

Pretty sure we all know, but just to highlight the overlap with #1786 and trying to get convergence between what they're both achieving.

The biggest change request here is to pass asset in funcs, and not try to derive it.
Failing that, derive it consistently, and handle unexpected conditions with Quote.

I think we're creating some really long names with gateio_websocket_request_*.
Specifically: Github defaults to hiding the important part of those names in the file browser on the left side when doing reviews, which makes it really hard.
I'd recommend `gateio_websocket_request_futures.go` becomes `ws_request_futures.go`.
I'm generally very much in favour of (slowly?) migrating from stuttered prefixes of `gateio/gateio_*` to just `gateio/*`
And I think that gives `gateio.go` a more meaningful name like `requests.go` or `rest.go` or something 🤷

2025-03-05 03:14 UTC, gbjk commented on exchanges/gateio/gateio_websocket_request_futures_test.go
> +	require.NoError(t, err)
```suggestion
	out.Contract, err = currency.NewPairWithDelimiter(currency.BTC, currency.USDT, "_")
```

2025-03-05 03:14 UTC, gbjk commented on exchanges/gateio/gateio_websocket_request_futures_test.go
> +	require.NoError(t, err)
```suggestion
	out.Contract, err = currency.NewPairWithDelimiter(currency.BTC, currency.USD, "_")
```

2025-03-05 03:14 UTC, gbjk commented on exchanges/gateio/gateio_websocket_request_futures_test.go
> +	pair, err := currency.NewPairFromString("BTC_USDT")
And by this point I think it should be a var or something.

2025-03-05 03:14 UTC, gbjk commented on exchanges/gateio/gateio_wrapper.go
> +func (g *Gateio) deriveFuturesWebsocketOrderResponses(responses []WebsocketFuturesOrderResponse) ([]*order.SubmitResponse, error) {
Can we make them pointers? Cos then we can range them on `for _, r := range responses`
```suggestion
func (g *Gateio) deriveFuturesWebsocketOrderResponses(responses []*WebsocketFuturesOrderResponse) ([]*order.SubmitResponse, error) {
```

2025-03-11 02:11 UTC, shazbert commented on exchanges/gateio/gateio_wrapper.go
> +func (g *Gateio) deriveSpotWebsocketOrderResponses(responses []WebsocketOrderResponse) ([]*order.SubmitResponse, error) {
It was due to batch orders which I had together in a branch which I have split that out into another PR. I will do the suggestion of having a function for `deriveResponse`

2025-03-11 23:10 UTC, shazbert commented on exchanges/gateio/gateio_websocket.go
> +	if inbound.Header.Status != "200" {
Seems to be only 200, 201 or 202 is not in their websocket implementation docs or something I have come across in trading it the endpoint. 

Re: `IsSucess` there is a few places around the code base that has status codes, okx, request package itself, so it could use some love, I would prefer it to be in a different PR if possible.

2025-03-12 03:14 UTC, shazbert commented
@gbjk Havent done the file name changes yet waiting on review so that if your other PR gets merged first I can easily merge it then I will change it over or vice versa.

2025-03-21 03:37 UTC, gbjk commented on exchanges/order/order_types.go
> +	Purchased float64
I'm fine with whatever it is, so long as the comment is clear 👍 
Just to check: Does it actually *need* to be directional?
Could Purchased always be in Base and Cost always be in Quote, regardless of side?

2025-03-21 03:42 UTC, gbjk approved these changes
Code LGTM 🎉 
Good work 👍

2025-03-31 00:48 UTC, gloriousCode requested changes
Only minor things I found

2025-03-31 00:48 UTC, gloriousCode commented on exchanges/gateio/gateio_websocket_request_futures.go
> +}
This is a bit weird in the sense that gateio does not have support for these asset types until https://github.com/thrasher-corp/gocryptotrader/pull/1786 is merged.
That said, I didn't recognise it in previous PRs where the following snippet was introduced. So I'll say you're okay
```
// Futures connection - BTC margined
	err = g.Websocket.SetupNewConnection(&stream.ConnectionSetup{
		URL:                  futuresWebsocketBtcURL,
		ResponseCheckTimeout: exch.WebsocketResponseCheckTimeout,
		ResponseMaxLimit:     exch.WebsocketResponseMaxLimit,
		Handler: func(ctx context.Context, incoming []byte) error {
			return g.WsHandleFuturesData(ctx, incoming, asset.Futures)
		},
		Subscriber:               g.FuturesSubscribe,
		Unsubscriber:             g.FuturesUnsubscribe,
		GenerateSubscriptions:    func() (subscription.List, error) { return g.GenerateFuturesDefaultSubscriptions(currency.BTC) },
		Connector:                g.WsFuturesConnect,
		MessageFilter:            asset.CoinMarginedFutures,
		BespokeGenerateMessageID: g.GenerateWebsocketMessageID,
	})
```

2025-03-31 04:16 UTC, gloriousCode approved these changes
tACK! May the sun shine on your PNL

2025-04-01 02:55 UTC, gbjk commented on exchanges/gateio/gateio_websocket_request_types.go
> +	Asset     asset.Item    `json:"-"` // Excluded from payload; used internally to determine routing
🐒 Pedantic monkey says that the first part of this sentence is self-evident
Commenting to say *why* is great though.
```suggestion
	Contract  currency.Pair `json:"-"` // Only used internally for routing
	Asset     asset.Item    `json:"-"` // Only used internally for routing
```

2025-04-02 02:54 UTC, gbjk approved these changes

2025-04-11 05:03 UTC, gloriousCode approved these changes
Confirming access to websocket package from external sources
<img width="363" alt="image" src="https://github.com/user-attachments/assets/74f4e509-185e-4bf8-b2ce-92710c9b77c9" />
A learning experience 🌟 🌈

2025-04-11 05:39 UTC, thrasher- requested changes
Only minor things:

Test coverage looks good on all request order methods you've added, plus the handling of order responses. We could look into putting the many variant ones into JSON files, but not going to nit them on this PR since it's already big and you've waited long enough for this to be merged!

Nice work!

2025-04-11 05:39 UTC, thrasher- commented on README.md
> +| [azhang](https://github.com/azhang) | 2 |
Can revert these changes since they're duplicates, then won't have to worry about it anymore once #1885 is merged

2025-04-11 05:39 UTC, thrasher- commented on cmd/documentation/exchange_templates/exchange_websocket_readme.tmpl
> +	e.Websocket = websocket.NewManager()
Thank you for appeasing my OCD, can sleep well tonight 😆

2025-04-11 05:39 UTC, thrasher- commented on exchanges/gateio/gateio_websocket_request_futures.go
> +	params := struct {
Noticing that your params everywhere else are using a reference instead of here

2025-04-11 05:47 UTC, shazbert commented on cmd/documentation/exchange_templates/exchange_websocket_readme.tmpl
> +	e.Websocket = websocket.NewManager()
🚀

2025-04-11 06:31 UTC, gbjk approved these changes
LGTM 🎉

2025-04-11 06:31 UTC, gbjk commented on exchanges/gateio/gateio_websocket_request_futures.go
>  	}{Contract: contract, Side: side}
🥃  It's kinda weird to have this `wsCancelAllFuturesOrders` type just anonymously hidden here, and also in other examples around here.

Just saying.
![kermit](https://us.tonies.com/cdn/shop/files/Tonies-PDP-Assets-kermit-single.jpg?v=1734730750&width=3000)

2025-04-11 06:47 UTC, merged

2025-04-18 04:01 UTC, gbjk commented on exchanges/gateio/gateio_wrapper.go
> +		a, err := getAssetFromFuturesPair(s.Pair)
I think we missed this; We have s.Asset, so we should use that.
We're going to validate it anyway inside `WebsocketFuturesSubmitOrders` against the contract.