CI/build: Update Go version, linters and fix minor issues
thrasher-corp/gocryptotrader pull request #1612
Opened 2024-08-15 01:19 UTC by thrasher-

# PR Description

Bumps the CI and toolchain go versions to 1.23, golangci-lint to v1.60.1 and fixes issues along the way. Also rids some VS code analysis issues like non-used writes and nilness tautological conditions.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How has this been tested

- [x] go test ./... -race
- [x] golangci-lint run

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally and on Github Actions with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2024-08-15 03:56 UTC, shazbert requested changes
Nice🔥

2024-08-15 03:56 UTC, shazbert commented on backtester/funding/funding_test.go
>  	quoteCopy.pairedWith = &baseCopy
`quoteCopy` can be removed as its  not being used

2024-08-15 03:56 UTC, shazbert commented on cmd/gen_otp/otp_gen.go
> +				log.Printf("Failed to read input. Err: %s", err)
add `\n`

2024-08-15 06:19 UTC, shazbert approved these changes
tACK. Lookin' schmick.

2024-08-16 00:44 UTC, gloriousCode approved these changes
tACK, found some good ones in there

2024-08-16 07:41 UTC, merged