common/gateio: add thread-safe counter
thrasher-corp/gocryptotrader pull request #1615
Opened 2024-08-16 02:11 UTC by shazbert

# PR Description

* GenerateMessageID does not ensure atomicity, this update adds a basic counter for routines that require low cost message matching signatures. 
* Gateio is converted.
* NOTE: The overhead of GenerateMessageID is quite high

Fixes # (issue)

* Signature collisions

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration and
also consider improving test coverage whilst working on a certain feature or package.

- [ ] go test ./... -race
- [ ] golangci-lint run
- [ ] Test X

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally and on Github Actions with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-08-16 03:10 UTC, gloriousCode requested changes
Only one request, this is fine 🐶

2024-08-16 03:10 UTC, gloriousCode commented on common/common.go
> +	// Handle overflow by resetting the counter to 1 if it becomes negative
Had thoughts of suggesting uint64 instead, but there are many unknowns and I doubt anyone is going to subscribe to WIF more 9,223,372,036,854,775,807 times on GateIO in a single session

2024-08-16 03:40 UTC, gloriousCode approved these changes
tACK!

# 🌞 
```
[DEBUG] | WEBSOCKET | 16/08/2024 13:37:42 | GateIO websocket connection: sending message [{"time":1723779462,"id":1,"channel":"spot.tickers","event":"subscribe","payload":["BTC_USDT"]}]
[DEBUG] | WEBSOCKET | 16/08/2024 13:37:42 | GateIO websocket connection: message received: {"time":1723779462,"time_ms":1723779462323,"id":1,"conn_id":"1b73153490cc89f8","trace_id":"daa79b26d14a54b172e11012230c1c78","channel":"spot.tickers","event":"subscribe","payload":["BTC_USDT"],"result":{"status":"success"},"requestId":"daa79b26d14a54b172e11012230c1c78"}
[DEBUG] | WEBSOCKET | 16/08/2024 13:37:42 | GateIO websocket connection: sending message [{"time":1723779462,"id":2,"channel":"spot.candlesticks","event":"subscribe","payload":["5m","BTC_USDT"]}]
[DEBUG] | WEBSOCKET | 16/08/2024 13:37:42 | GateIO websocket connection: message received: {"time":1723779462,"time_ms":1723779462670,"id":2,"conn_id":"1b73153490cc89f8","trace_id":"daa79b26d14a54b172e11012230c1c78","channel":"spot.candlesticks","event":"subscribe","payload":["5m","BTC_USDT"],"result":{"status":"success"},"requestId":"daa79b26d14a54b172e11012230c1c78"}
[DEBUG] | WEBSOCKET | 16/08/2024 13:37:42 | GateIO websocket connection: sending message [{"time":1723779462,"id":3,"channel":"spot.book_ticker","event":"subscribe","payload":["BTC_USDT"]}]
[DEBUG] | WEBSOCKET | 16/08/2024 13:37:43 | GateIO websocket connection: message received: {"time":1723779463,"time_ms":1723779463017,"id":3,"conn_id":"1b73153490cc89f8","trace_id":"daa79b26d14a54b172e11012230c1c78","channel":"spot.book_ticker","event":"subscribe","payload":["BTC_USDT"],"result":{"status":"success"},"requestId":"daa79b26d14a54b172e11012230c1c78"}
```

2024-08-19 00:55 UTC, thrasher- requested changes
Rather than deviating from the websocket GenerateMessageID helper and rolling out exchange specific counters, I'd opt for the ability to override the default behavior so it still remains unified but configurable

2024-08-23 05:08 UTC, thrasher- approved these changes
Thanks for making those changes 🌞  tACK:
![image](https://github.com/user-attachments/assets/886971e6-2e1e-4a21-b686-9fc04d1d0d85)

2024-08-23 05:14 UTC, thrasher- requested changes
Just realised after tACK'ing that this requires test coverage and then should be good to go

2024-08-24 02:17 UTC, thrasher- approved these changes
Changes ACK, thanks!

2024-08-24 02:18 UTC, merged