Gemini: Add subscription configuration
thrasher-corp/gocryptotrader pull request #1625
Opened 2024-08-21 01:36 UTC by gbjk

### Gemini
* Add Subscription configuration
* Upgrade test configuration

## Type of change

- [x] New feature (non-breaking change which adds functionality)

2024-08-27 22:23 UTC, shazbert approved these changes
tACK.

2024-08-27 22:23 UTC, shazbert commented on exchanges/gemini/gemini_websocket.go
> +		return "1d"
😆

2024-12-05 02:17 UTC, gloriousCode approved these changes
tACK! I don't know why I went to the effort to re-verify on Gemini with no auth sub support 😭

2024-12-05 03:59 UTC, shazbert requested changes
Could you please add in this change:

```diff
diff --git a/exchanges/gemini/gemini_websocket.go b/exchanges/gemini/gemini_websocket.go
index a738c2856..cecf8bba1 100644
--- a/exchanges/gemini/gemini_websocket.go
+++ b/exchanges/gemini/gemini_websocket.go
@@ -169,6 +169,7 @@ func (g *Gemini) WsAuth(ctx context.Context, dialer *websocket.Dialer) error {
        if err != nil {
                return fmt.Errorf("%v Websocket connection %v error. Error %v", g.Name, endpoint, err)
        }
+       g.Websocket.Wg.Add(1)
        go g.wsFunnelConnectionData(g.Websocket.AuthConn)
        return nil
 }
```

To resolve #1738

2024-12-05 04:31 UTC, gbjk commented
> Could you please add in this change To resolve #1738

Fixed https://github.com/gbjk/gocryptotrader/commit/487516628

2024-12-05 04:43 UTC, shazbert approved these changes
Thank you very much!

2024-12-05 05:14 UTC, thrasher- approved these changes
tACK, thanks @shazbert for the additional fix!

2024-12-06 02:13 UTC, merged