bybit: enable multiconnection handling across websocket endpoints
thrasher-corp/gocryptotrader pull request #1670
Opened 2024-10-09 01:15 UTC by shazbert

# PR Description

* Expand websocket handling to concurrently allow processing for CoinMarginedFutures, USDTMarginedFutures, USDCMarginedFutures, Options. 
* Implement dedicated connection for private data.

NOTE: This is a nice size PR for just functionality expansion, I will build outbound request functions for trading on top of this in a future PR. Here's the dependency: #1603

Fixes # 

* 🐛 DOGEUSDT wasn't being processed correctly so used `MatchSymbolWithAvailablePairs` because there was no delimiter.

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration and
also consider improving test coverage whilst working on a certain feature or package.

- [ ] go test ./... -race
- [ ] golangci-lint run
- [ ] Test X

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally and on Github Actions with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2025-04-29 00:13 UTC, gloriousCode requested changes
Nice work shazbert, I'm quite happy with a lot of the work

2025-04-29 00:13 UTC, gloriousCode commented on exchanges/bybit/bybit_websocket.go
> +	return currency.EMPTYPAIR, 0, err
```go
	for _, a := range assets {
		cp, err := by.MatchSymbolWithAvailablePairs(symbol, a, hasPotentialDelimiter(a))
		if err != nil {
			return currency.EMPTYPAIR, 0, err
		}
		return cp, a, nil
	}
	return currency.EMPTYPAIR, 0, nil
```
I think its an improvement to readability to not try funny business with err handling and such

2025-04-29 00:13 UTC, gloriousCode commented on exchanges/bybit/bybit_websocket.go
> +			Pairs:   currency.Pairs{currency.EMPTYPAIR}, // This is a placeholder, the actual pair is not required for these channels
Is pairs required to be filled? Have you tried not sending pairs?

2025-05-30 02:33 UTC, shazbert commented on exchanges/bybit/bybit_websocket.go
> +		if id, err := jsonparser.GetString(respRaw, "data", "[0]", "orderId"); err == nil {
Nice catch this was actually updated to that in the request PR built on this. 🚀 I will roll that update here.

2025-05-30 03:07 UTC, shazbert commented on exchanges/bybit/bybit_websocket.go
> +			// therefore the code doesn't wait for the response to check whether the subscription is successful or not.
Going to be RM'd anyway

2025-06-06 10:42 UTC, gbjk approved these changes
Good work 👍 

I'm generally unhappy with needing to do any of this, but I can see the constraints, and if we spend more time hacking out anything better right now we might as well spend that time on the already open branches.

I've downgraded everything to nitpicks from change requests because this is high priority, and you can fix them later. None of them introduce bugs or regressions.

2025-06-06 10:42 UTC, gbjk commented on docs/ADD_NEW_EXCHANGE.md
> +- `disable` to ensure correct disabling of pair(s) and associated unsubscriptions.
🐒 This monkey thinks `unsubscription` isn't a real word, and "disabling X and associated subscriptions" is the same as "disabling [...] subscriptions"
```suggestion
- `disable` to ensure correct disabling of pair(s) and associated subscriptions.
```

2025-06-06 10:42 UTC, gbjk commented on exchanges/gateio/gateio.go
> +	messageIDSeq  common.Counter
🐒 For GateIO, can't we just use uuid.UUID V7. Particularly [google's implementation](https://pkg.go.dev/github.com/google/uuid#NewV7)

2025-06-06 10:42 UTC, gbjk commented on exchange/websocket/connection.go
> +	requestIDGenerator   func() int64
🐒  I think if we're touching this, we should change to string.
Most sane APIs would support a uuid, and uuid v7 is sequential. `uuid.Must(uuid.NewV7)`
```suggestion
	requestIDGenerator   func() string
```
Optionally I'd guess to allow errors. I don't have a generator I'd want to use that'd return an error, though.

2025-06-06 10:42 UTC, gbjk commented on exchanges/bybit/bybit.go
> +	messageIDSeq common.Counter
🐒 For Bybit, can't we just use uuid.UUID V7. Particularly [google's implementation (https://pkg.go.dev/github.com/google/uuid#NewV7)
Docs say it's just a string.

2025-06-06 10:42 UTC, gbjk commented on exchanges/bybit/bybit_websocket.go
> +func (by *Bybit) submitSubscriptionNonTemplate(ctx context.Context, conn websocket.Connection, a asset.Item, operation string, channelsToSubscribe subscription.List) error {
🐒 I'm not wild about needing to do this, but it'll get us further faster we just take this step first.
However even in the short term, I think `NonTemplate` is better as `NoTemplate` or `WithoutTemplate`.
But I'd argue for just `submitSimpleSubscription` or `submitDirectSubscription`

2025-06-06 10:42 UTC, gbjk commented on exchanges/bybit/bybit_websocket.go
> +		}
🦍 Signatures are the same, so optionally could use this pattern.
`op` can move out of the for loop, obviously.
```suggestion
		op := by.Websocket.AddSubscriptions
		if operation == "unsubscribe" {
			op = by.Websocket.RemoveSubscriptions
		}
		if err := op(conn, payload.associatedSubs...); err != nil {
			return err
		}
```

2025-06-06 10:42 UTC, gbjk commented on exchanges/bybit/bybit_websocket.go
> +func (by *Bybit) handleSubscriptionsNonTemplate(conn websocket.Connection, assetType asset.Item, operation string, channelsToSubscribe subscription.List) ([]SubscriptionArgument, error) {
🐒 This isn't actually handling anything.
```suggestion
func (by *Bybit) directSubscriptionPayload(conn websocket.Connection, assetType asset.Item, operation string, channelsToSubscribe subscription.List) ([]SubscriptionArgument, error) {
```

2025-06-06 10:42 UTC, gbjk commented on exchanges/bybit/bybit_websocket.go
> +			arg.Arguments = append(arg.Arguments, fmt.Sprintf("%s.%d.%s", s.Channel, 50, pair.Format(pairFormat).String()))
🐒 pairFormat.Format appears to do this in one go.
Also think get can get away with pairFmt
🌴 This monkey lives in multiple trees below too.
```suggestion
			arg.Arguments = append(arg.Arguments, fmt.Sprintf("%s.%d.%s", s.Channel, 50, pairFmt.Format(pair)))
```

2025-06-06 10:42 UTC, gbjk commented on exchanges/bybit/bybit_test.go
> +	"Execution":        `{"id": "592324803b2785-26fa-4214-9963-bdd4727f07be", "topic": "execution", "creationTime": 1672364174455, "data": [ { "category": "linear", "symbol": "XRPUSDT", "execFee": "0.00
🐒   Can this not use the FixtureToDataHandler pattern?
We're already using it in bybit_test

2025-06-06 10:42 UTC, gbjk commented on exchanges/bybit/bybit_test.go
> +	require.Empty(t, authsubs)
🐒 🌴 
```suggestion
	require.NoError(t, err, "generateAuthSubscriptions must not error")
	require.Empty(t, authsubs, "generateAuthSubscriptions must not return subs")
```

2025-06-06 10:42 UTC, gbjk commented on exchanges/bybit/bybit_test.go
> +	require.NotEmpty(t, authsubs)
And throughout.
```suggestion
	require.NoError(t, err, "generateAuthSubscriptions must not error")
	require.Empty(t, authsubs, "generateAuthSubscriptions must not return subs")
```

2025-06-06 10:42 UTC, gbjk commented on exchanges/bybit/bybit_test.go
> +	require.Equal(t, asset.USDTMarginedFutures, o[0].AssetType)
🐒  Also here; Can this not use the FixtureToDataHandler pattern?

2025-06-16 05:43 UTC, shazbert commented on exchange/websocket/connection.go
> +	requestIDGenerator   func() int64
Good suggestion, I think I might make a separate PR for this, because this will impact GenerateMessageID signature as well, I would probably opt for `defaultGenerateMessageID` to be v7 for searchability and `ClientOrderID` field setting. There is a tiny overhead associated with v7 but it's minute, so keeping it as a baseline would be perfect. The current default is just using `rand.Int` and has the potential to have collisions anyway. 

For GateIO/bybit the counter is used mainly for request response matching and the counters don't seem to be tracked or are reset on each new connection and they don't come back in fills/order history. So if possible would like to keep them as is and then refresh them if needed in that separate PR?

Thoughts? @thrasher- @gbjk

2025-06-17 00:10 UTC, shazbert commented on exchanges/bybit/bybit_test.go
> +	require.Equal(t, asset.USDTMarginedFutures, o[0].AssetType)
[removed and consolidated in](https://github.com/thrasher-corp/gocryptotrader/pull/1670/commits/49930d2190a74540225f1d89737ac66039fa6cc7)

2025-06-17 00:10 UTC, shazbert commented on exchanges/bybit/bybit_test.go
> +	"Execution":        `{"id": "592324803b2785-26fa-4214-9963-bdd4727f07be", "topic": "execution", "creationTime": 1672364174455, "data": [ { "category": "linear", "symbol": "XRPUSDT", "execFee": "0.00
https://github.com/thrasher-corp/gocryptotrader/pull/1670/commits/49930d2190a74540225f1d89737ac66039fa6cc7

2025-06-17 00:14 UTC, shazbert commented
> I'm generally unhappy with needing to do any of this

![image](https://github.com/user-attachments/assets/fd4eacf7-e971-4145-aa2f-bc39cb0424aa)

2025-06-22 03:18 UTC, gbjk commented on exchange/websocket/connection.go
> +	requestIDGenerator   func() int64
Agreed to slide this to later.

2025-06-22 03:41 UTC, gbjk approved these changes
All good.
Only wildlife to see. 🐒 🦍

2025-06-22 03:41 UTC, gbjk commented on exchanges/gateio/gateio.go
> +	messageIDSeq  common.Counter
Agreed to slide this to later following [this reply](https://github.com/thrasher-corp/gocryptotrader/pull/1670#discussion_r2149088220)

2025-06-22 03:41 UTC, gbjk commented on exchanges/bybit/bybit_test.go
> +		}
🥃 🗻  This feels like a generic problem.
Wondering if we can text/template the content easily, and introduce a middleware:
```
FixtureToDataHandler(t, "foo.json", testexch.WrapFixture(b.wsHandleAuthenticatedData), testexch.FixtureVars{
    "optionsPair": optionsTradablePair,
}
```
and then in the fixture json:
```
{{ .vars.optionsPair.String }}
```

2025-06-22 03:41 UTC, gbjk commented on exchanges/bybit/bybit_test.go
> +	require.Len(t, b.Websocket.DataHandler, 6, "Should see correct number of private messages")
```suggestion
	require.Len(t, b.Websocket.DataHandler, 6, "Should see correct number of messages")
```

2025-06-22 03:41 UTC, gbjk commented on exchanges/bybit/bybit_test.go
> +			assert.Equal(t, int64(41), v[0].RiskID, "RiskID should match")
🦍  The wording I've used so far is "X should be correct".
"match" feels overloaded, because of times we actually mean that some function or method called match returned true, etc.
Don't have to action, I'm just being pedantic/consistent.

2025-06-22 03:41 UTC, gbjk commented on exchanges/bybit/bybit_test.go
> +			t.Errorf("Unexpected data type received: %T", v)
```suggestion
			t.Errorf("Unexpected data received: %v", v)
```

2025-06-23 01:23 UTC, shazbert commented on exchanges/bybit/bybit_test.go
> +			assert.Equal(t, int64(41), v[0].RiskID, "RiskID should match")
https://github.com/thrasher-corp/gocryptotrader/pull/1670/commits/e6f4a93426fa1da4a321b9342aa7f2e1d3de15c3

2025-06-23 01:25 UTC, shazbert commented on exchanges/bybit/bybit_test.go
> +		}
Yeah that would be cool to do, can do this in another PR.

2025-06-23 04:55 UTC, gbjk approved these changes

2025-06-24 05:50 UTC, cranktakular requested changes
Got some changes I want.

On top of those comments about specific places, some more general things:
* When running all exchange tests, I got an error in okx I didn't get on master (line 333, TestGetBlockTrade, "0 is not positive%!"). Find out whether that was caused by your changes, or if it's just intermittent.
* Potentially OOS, but consider writing detailed test functions to get more coverage out of GenerateInverseDefaultSubscriptions, InverseUnsubscribe, GenerateLinearDefaultSubscriptions, LinearUnsubscribe, GenerateOptionsDefaultSubscriptions, OptionUnsubscribe, Unsubscribe, and Setup.
* Potentially OOS, but I saw some room for more coverage in handleSubscriptions, handleSpotSubscription, wsHandleData, wsProcessWalletPushData, wsProcessOrder, wsProcessExecution, wsProcessLeverageTokenTicker, wsProcessPublicTicker, GetWalletBalance, and UpdateAccountInfo.
* I also saw some coverage shortfalls that I think are in scope. Within the functions wsHandleAuthenticatedData, wsProcessOrder, wsProcessPublicTicker, submitDirectSubscription, directSubscriptionPayload, getPairFromCategory, WsConnect, and WebsocketAuthenticatedConnection.

2025-06-24 05:50 UTC, cranktakular commented on exchanges/bybit/bybit_wrapper.go
> -	wsRunningEndpoint, err := by.API.Endpoints.GetURL(exchange.WebsocketSpot)
It wasn't fully utilised before, but wouldn't we still want to retrieve the URL this way, instead of directly assigning it to a constant? Especially since some users will need to use non-standard URLs ("bybit-tr.com" or "bybit.kz" instead of "bybit.com")

And if we don't want to retrieve it this way, would we want to remove that functionality across the entire exchange?

2025-06-24 05:50 UTC, cranktakular commented on exchanges/bybit/bybit_wrapper.go
> +		GenerateSubscriptions: func() (subscription.List, error) { return by.generateSubscriptions() },
Any reason why this can't just be `by.generateSubscriptions`?

2025-06-24 05:50 UTC, cranktakular commented on exchanges/bybit/bybit_websocket.go
> -	if !by.Websocket.IsEnabled() || !by.IsEnabled() || !by.IsAssetWebsocketSupported(asset.Spot) {
Is it truly wise to remove these enabled checks?

2025-06-24 05:50 UTC, cranktakular commented on exchanges/bybit/bybit_websocket.go
> +	payloads, err := by.handleSubscriptions(conn, operation, channelsToSubscribe)
Are these appropriate function names? If handleSubscriptions() is only called through handleSpotSubscription(), then wouldn't either both or neither operate exclusively on Spot endpoints?

2025-06-24 05:50 UTC, cranktakular commented on exchanges/bybit/bybit_websocket.go
> +	tick := &ticker.Price{Pair: p, ExchangeName: by.Name, AssetType: assetType}
I prefer the old control flow. Always retrieving and setting this data, even when it would be overwritten later, doesn't seem worthwhile.

But a benchmark could easily prove that hunch wrong.

2025-06-24 05:50 UTC, cranktakular commented on exchanges/bybit/bybit_websocket.go
> +// LinearUnsubscribe sends an unsubscription messages through linear public channels.
The function names in these two subscribe/unsubscribe comments are incorrect

2025-06-24 05:50 UTC, cranktakular commented on exchanges/bybit/bybit_websocket.go
> +			authArg.Arguments = append(authArg.Arguments, s.Channel)
Is DCP fine with a subscription being performed without the asset? [The documentation](https://bybit-exchange.github.io/docs/v5/websocket/private/dcp) kind of implies it won't, but I can't test it myself.

2025-06-24 05:50 UTC, cranktakular commented on exchanges/bybit/bybit_websocket.go
> +		if len(arg.Arguments) >= 10 {
This limit [appears to be for spot only](https://bybit-exchange.github.io/docs/v5/ws/connect#public-channel---args-limits). You may not want to bother handling that right now since this will be supplanted by templating stuff anyway, but there will be some efficiency improvements for options/futures possible.

2025-06-24 05:50 UTC, cranktakular commented on exchanges/bybit/bybit_inverse_websocket.go
>  // InverseUnsubscribe sends an unsubscription messages through linear public channels.
It seems odd for these comments to say they're sending messages through *linear* public channels.

2025-06-24 05:50 UTC, cranktakular commented on exchanges/bybit/bybit_linear_websocket.go
> +	return by.submitDirectSubscription(ctx, conn, asset.USDTMarginedFutures, "unsubscribe", channelSubscriptions)
This mandates the use of USDT, while Linear on this exchange could also be USDC. Could you find a way to properly accommodate both here?

2025-06-24 05:50 UTC, cranktakular commented on exchanges/bybit/testdata/wsAuth.json
> +{"id": "59232430b58efe-5fc5-4470-9337-4ce293b68edd", "topic": "position", "creationTime": 1672364174455, "data": [ { "positionIdx": 0, "tradeMode": 0, "riskId": 41, "riskLimitValue": "200000", "symbo
OOS but these are missing some fields that the exchange now sends.

2025-06-24 05:50 UTC, cranktakular commented on exchanges/bybit/bybit_websocket.go
> +func (by *Bybit) wsHandleData(_ context.Context, assetType asset.Item, respRaw []byte) error {
You can just remove the context.Context from the function signature. Everything still compiles and runs fine.

2025-06-24 06:12 UTC, shazbert commented on exchanges/bybit/bybit_wrapper.go
> +		GenerateSubscriptions: func() (subscription.List, error) { return by.generateSubscriptions() },
nice catch!

2025-06-24 06:38 UTC, shazbert commented on exchanges/bybit/bybit_websocket.go
> +		if len(arg.Arguments) >= 10 {
Can defer this to https://github.com/thrasher-corp/gocryptotrader/pull/1672 if there are any issues when trading on it. But yeah it should be removed entirely as soon as possible.

2025-06-24 06:49 UTC, shazbert commented on exchanges/bybit/bybit_websocket.go
> +			authArg.Arguments = append(authArg.Arguments, s.Channel)
Doesn't look like we handle DCP at all in `generateAuthSubscriptions`, added a TODO for implementation maybe for https://github.com/thrasher-corp/gocryptotrader/pull/1672 or when full template pass comes in.

2025-06-24 06:52 UTC, shazbert commented on exchanges/bybit/bybit_websocket.go
> +	payloads, err := by.handleSubscriptions(conn, operation, channelsToSubscribe)
I was assuming it would be used across templates when that upgrade occurs. Suggest a better name I could implement.

2025-06-24 06:54 UTC, shazbert commented on exchanges/bybit/bybit_websocket.go
> -	if !by.Websocket.IsEnabled() || !by.IsEnabled() || !by.IsAssetWebsocketSupported(asset.Spot) {
Have you found it connects with the asset turned off? Most of this is handled by the websocket manager.

2025-06-24 22:07 UTC, shazbert commented on exchanges/bybit/bybit_wrapper.go
> -	wsRunningEndpoint, err := by.API.Endpoints.GetURL(exchange.WebsocketSpot)
Good catch will re-implement

2025-06-24 22:16 UTC, shazbert commented on exchanges/bybit/bybit_websocket.go
> +	tick := &ticker.Price{Pair: p, ExchangeName: by.Name, AssetType: assetType}
I might defer this, I think that @thrasher- has an update incoming for this on one of his PR's

2025-06-24 22:38 UTC, shazbert commented on exchanges/bybit/testdata/wsAuth.json
> +{"id": "59232430b58efe-5fc5-4470-9337-4ce293b68edd", "topic": "position", "creationTime": 1672364174455, "data": [ { "positionIdx": 0, "tradeMode": 0, "riskId": 41, "riskLimitValue": "200000", "symbo
Defer to #1672 I can't get concrete values from the position data example.

2025-06-24 22:39 UTC, shazbert commented
@cranktakular most nits addressed thank you!

2025-06-30 00:21 UTC, shazbert commented
@cranktakular Still have more things to do but time constrained hold off on reviewing this just yet until I can get around to it.

2025-07-01 00:50 UTC, cranktakular commented on exchanges/bybit/bybit_websocket.go
> +	payloads, err := by.handleSubscriptions(conn, operation, channelsToSubscribe)
Ah, if it's pending that sort of thing then don't worry.

2025-07-02 21:55 UTC, shazbert commented
- [ ]  websocket reconnection is broken, need to investigate. Something to do with ping handlers not being cleaned up. 🪦

2025-07-02 23:03 UTC, shazbert commented
> * [ ]   websocket reconnection is broken, need to investigate. Something to do with ping handlers not being cleaned up. 🪦

nevermind that was bad code from me. 
![image](https://github.com/user-attachments/assets/789c8dc6-57e9-44e3-bce6-ae43628bfe19)

2025-07-24 10:46 UTC, shazbert commented
@cranktakular 

> * When running all exchange tests, I got an error in okx I didn't get on master (line 333, TestGetBlockTrade, "0 is not positive%!"). Find out whether that was caused by your changes, or if it's just intermittent.

This PR doesn't impact that. 

> * Potentially OOS, but consider writing detailed test functions to get more coverage out of GenerateInverseDefaultSubscriptions, InverseUnsubscribe, GenerateLinearDefaultSubscriptions, LinearUnsubscribe, GenerateOptionsDefaultSubscriptions, OptionUnsubscribe, Unsubscribe, and Setup.

Added minor coverage improvements

> * Potentially OOS, but I saw some room for more coverage in handleSubscriptions, handleSpotSubscription, wsHandleData, wsProcessWalletPushData, wsProcessOrder, wsProcessExecution, wsProcessLeverageTokenTicker, wsProcessPublicTicker, GetWalletBalance, and UpdateAccountInfo.

Added minor coverage to this

> * I also saw some coverage shortfalls that I think are in scope. Within the functions wsHandleAuthenticatedData, wsProcessOrder, wsProcessPublicTicker, submitDirectSubscription, directSubscriptionPayload, getPairFromCategory, WsConnect, and WebsocketAuthenticatedConnection.

Added minor coverage for these, there are some which are going to be removed in template pass, `getPairFromCategory` will only error on nil currency manager so not going to hit that

2025-07-27 21:21 UTC, samuael approved these changes
Just two optional code suggestion spotted

2025-07-27 21:21 UTC, samuael commented on exchanges/bybit/bybit_test.go
> +	require.ErrorIs(t, err, exp)
Could you use a mere string comparison instead?

2025-07-27 21:21 UTC, samuael commented on exchanges/bybit/spot_websocket.go
> +		if err := json.Unmarshal(response, &resp); err != nil {
You can remove this immediate assignment since there is a big scoped err variable above.

2025-07-29 08:12 UTC, cranktakular requested changes
Got some more changes I want.

In addition to those comments, I'm pretty sure these functions could get more test coverage: handleSpotSubscription, wsHandleAuthenticatedData, handleNoTopicWebsocketResponse, wsProcessOrder, getPairFromCategory, Setup.

And I think these functions have a slight chance of being able to get more test coverage: GenerateOptionsDefaultSubscriptions, GenerateLinearDefaultSubscriptions, GenerateInverseDefaultSubscriptions

2025-07-29 08:12 UTC, cranktakular commented on exchanges/bybit/bybit_websocket.go
> +	switch topicSplit[0] {
You could pull the stuff before this switch case into its own function, since it's shared with the non-auth version. Although this would add four lines, so might not be worthwhile, despite it de-duplicating code.

Actually, you wouldn't need to split off handleNoTopicWebsocketResponse that way, so it should ultimately save lines.

2025-07-29 08:12 UTC, cranktakular commented on exchanges/bybit/bybit_websocket.go
> +			if e.Websocket.Match.IncomingWithData(id, respRaw) {
Might be misunderstanding part of how this works, but it seems conceptually weird to pass through the entirety of respRaw here, if it's only attempting to match with the first order change in that data.

Seems like, at best, the extra data would be superfluous, and at worst, it could taint things by associating those other orders with the first one, if handled improperly.

2025-07-29 08:12 UTC, cranktakular commented on exchanges/bybit/bybit_websocket.go
> +		return currency.EMPTYPAIR, 0, fmt.Errorf("category %q not supported for incoming symbol %q", category, symbol)
Bit of a nit, but this currently says the category is unsupported *for that symbol*, while it's simply unsupported *in general*.

Maybe replace with something like "incoming symbol %q has unsupported category %q"?

2025-07-29 08:12 UTC, cranktakular commented on exchanges/bybit/bybit_websocket.go
>  	return err
This will always be nil regardless, this err was assigned by the return value of MatchSymbolWithAvailablePairs, which was already handled if not nil.

2025-07-29 08:12 UTC, cranktakular commented on exchanges/bybit/bybit_websocket.go
> +		snapshot, err := e.GetCachedTicker(p, assetType)
An err is already in scope and handled, why not change this to ticker, err = e.GetCachedTicker(p, assetType) so you don't need to re-assign?

2025-07-29 08:12 UTC, cranktakular commented on exchanges/bybit/bybit_wrapper.go
> +
Unnecessary added newline.

2025-07-29 08:12 UTC, cranktakular commented on exchanges/bybit/inverse_websocket_test.go
> +	e := new(Exchange) //nolint:govet // Intentional shadow
Weird that the declarations in this file are the only ones which need this comment. Seems like a bug with the linter, honestly.

2025-07-29 08:12 UTC, cranktakular commented on exchanges/bybit/spot_websocket_test.go
> +	require.NoError(t, testexch.Setup(e), "Test instance Setup must not error")
Consider placing these two lines in their own function, like `e := newExchangeWithSetup(t)`, would save some lines across the tests in this package.

2025-07-29 08:12 UTC, cranktakular commented on exchanges/bybit/bybit_test.go
> +			assert.Equal(t, 1.0, v[0].ExecutedAmount, "Cum exec qty should be correct")
Failure message doesn't match variable name

2025-07-29 08:12 UTC, cranktakular commented on exchanges/bybit/bybit_test.go
> +			assert.Equal(t, 0.358635, v[0].Fee, "Cum exec fee should be correct")
Failure message doesn't match variable name

2025-07-29 08:12 UTC, cranktakular commented on exchanges/bybit/bybit_test.go
> +	for data := range e.Websocket.DataHandler {
This data validation here feels like overkill, do we want to test that this many parameters are being set?

2025-07-29 08:12 UTC, cranktakular commented on exchanges/bybit/bybit_test.go
> +	require.NoError(t, testexch.Setup(e))
I can't tell how you decide whether or not to include comments explaining the error. They generally feel superfluous to me, so I don't mind them being removed, but it seems inconsistent for only this one to be.

2025-07-29 08:12 UTC, cranktakular commented on exchanges/bybit/bybit_websocket.go
> -	if !by.Websocket.IsEnabled() || !by.IsEnabled() || !by.IsAssetWebsocketSupported(asset.Spot) {
I have not looked into that, I just want to ensure the checks are done _somewhere_ if they're being removed here.

2025-07-29 08:12 UTC, cranktakular commented on exchanges/bybit/bybit_websocket.go
> +			authArg.Arguments = append(authArg.Arguments, s.Channel)
Seems a bit missable as-is, due to this section having some handling for DCP already, even if we don't invoke it just yet.

2025-07-29 23:50 UTC, shazbert commented on exchanges/bybit/bybit_websocket.go
> +	switch topicSplit[0] {
Will pass on this due to time constraints. You can open a PR against this merged state if it bugs you.

2025-07-29 23:52 UTC, shazbert commented on exchanges/bybit/bybit_websocket.go
> +			if e.Websocket.Match.IncomingWithData(id, respRaw) {
Will be RM'd for the appropriate PR #1672

2025-07-30 00:03 UTC, shazbert commented on exchanges/bybit/inverse_websocket_test.go
> +	e := new(Exchange) //nolint:govet // Intentional shadow
Yeah it will probably resolve itself when they update upstream. Until then.

2025-07-30 00:03 UTC, shazbert commented on exchanges/bybit/spot_websocket_test.go
> +	require.NoError(t, testexch.Setup(e), "Test instance Setup must not error")
Pass

2025-07-30 00:06 UTC, shazbert commented on exchanges/bybit/bybit_test.go
> +	for data := range e.Websocket.DataHandler {
I agree but there can be regressions especially for order management account level stuff that are pretty critical.

2025-07-30 00:07 UTC, shazbert commented on exchanges/bybit/bybit_test.go
> +	require.NoError(t, testexch.Setup(e))
Yeah I generally do not include them because it has a line failure number. But you make a good point.

2025-07-30 00:09 UTC, shazbert commented on exchanges/bybit/bybit_websocket.go
> -	if !by.Websocket.IsEnabled() || !by.IsEnabled() || !by.IsAssetWebsocketSupported(asset.Spot) {
Yeah they won't generate subs, and having no subs means that no connection will be spawned and this function won't be called.

2025-07-30 00:12 UTC, shazbert commented on exchanges/bybit/bybit_websocket.go
> +			authArg.Arguments = append(authArg.Arguments, s.Channel)
What would you like me to do, that is in scope for this PR?

2025-07-30 00:34 UTC, shazbert commented
> Got some more changes I want.
> 
> In addition to those comments, I'm pretty sure these functions could get more test coverage: handleSpotSubscription, wsHandleAuthenticatedData, handleNoTopicWebsocketResponse, wsProcessOrder, getPairFromCategory, Setup.
> 
> And I think these functions have a slight chance of being able to get more test coverage: GenerateOptionsDefaultSubscriptions, GenerateLinearDefaultSubscriptions, GenerateInverseDefaultSubscriptions

Will pass on this due to time constraints. You can open a PR against this merged state if it bugs you. These generally have sufficient coverage and this need to be merged sooner rather than later.

2025-07-30 00:35 UTC, shazbert commented on exchanges/bybit/spot_websocket.go
> +		if err := json.Unmarshal(response, &resp); err != nil {
prefer if short, won't resolve so people can yell at me.

2025-07-30 01:13 UTC, gloriousCode commented on exchanges/bybit/spot_websocket.go
> +		if err := json.Unmarshal(response, &resp); err != nil {
@shazbert I PREFER HOW YOU'VE DONE IT 
<img src="https://art.pixilart.com/f04cfe2876d9ff4.gif" width="40px" />

2025-08-05 01:18 UTC, cranktakular approved these changes
Just got one suggested change left, other than that I can tACK this.

2025-08-05 01:18 UTC, cranktakular commented on exchanges/bybit/bybit_websocket.go
> +			authArg.Arguments = append(authArg.Arguments, s.Channel)
Remove (or comment out obviously correct) invocations of DCP, since it's currently unsupported, and that would require future implementations to make sure it adheres to the documentation in all relevant places.

2025-08-05 02:59 UTC, gloriousCode commented on exchanges/bybit/bybit_websocket.go
> +	// Authenticated channels are currently being managed by the `generateAuthSubscriptions` method for the private connection
Just to be clear about the removal here. Is this a change where authenticated subscriptions that are currently in user config subscriptions will cease working? Or is it that they do not work already? 

If the former, I think the user deserves a warning that you are removing support. I understand that there is an issue about sub propagation, but I think my suggestion will suffice.

I've made a suggestion for you below

2025-08-05 03:05 UTC, shazbert commented on exchanges/bybit/bybit_websocket.go
> +			authArg.Arguments = append(authArg.Arguments, s.Channel)
Removed https://github.com/thrasher-corp/gocryptotrader/pull/1670/commits/b5b082a27174cff28eaf1ef74b9728f1d0b51ea9

2025-08-05 03:34 UTC, gloriousCode commented on exchanges/bybit/bybit_websocket.go
> +	var subscriptions subscription.List
```suggestion
        for _, configSub := range e.Config.Features.Subscriptions.Enabled() {
		if configSub.Authenticated {
			log.Warnf(log.WebsocketMgr, "%q has an authenticated subscription %q in config which is not supported. Please remove",
				e.Name, configSub.Channel)
		}
	}
	
	var subscriptions subscription.List
```

2025-08-05 03:42 UTC, gloriousCode commented on exchanges/exchange.go
> +	case WebsocketCoinMargined:
Thank you for expanding these. Its one of those things I get annoyed at and then forget about a second later

2025-08-05 04:04 UTC, gloriousCode commented on exchanges/bybit/bybit_test.go
> +func TestGetPairFromCategory(t *testing.T) {
`e.matchPairAssetFromResponse(...)` I think is a better name for this and would like the rename

2025-08-05 05:17 UTC, gloriousCode commented on exchanges/bybit/bybit_websocket.go
> +			authArg.Arguments = append(authArg.Arguments, s.Channel)
This broke tests 🐝

2025-08-06 00:53 UTC, shazbert commented on exchanges/exchange.go
> +	case WebsocketCoinMargined:
You are welcome, but thank mr @cranktakular for kicking my butt on this. I originally just purged this completely.

2025-08-06 00:55 UTC, shazbert commented on exchanges/bybit/bybit_websocket.go
> +	// Authenticated channels are currently being managed by the `generateAuthSubscriptions` method for the private connection
They will silently cease working, I have applied your suggestion thank you ser. 🖖

2025-08-06 00:59 UTC, shazbert commented on exchanges/bybit/bybit_websocket.go
> +	// Authenticated channels are currently being managed by the `generateAuthSubscriptions` method for the private connection
```console
[WARN]  | WEBSOCKET | 06/08/2025 10:58:52 | "Bybit" has an authenticated subscription "myOrders" in config which is not supported. Please remove
[WARN]  | WEBSOCKET | 06/08/2025 10:58:52 | "Bybit" has an authenticated subscription "myWallet" in config which is not supported. Please remove
[WARN]  | WEBSOCKET | 06/08/2025 10:58:52 | "Bybit" has an authenticated subscription "myTrades" in config which is not supported. Please remove
```

2025-08-06 21:46 UTC, gloriousCode commented on exchanges/bybit/bybit_websocket.go
> +	subscription.MyTradesChannel:  chanExecution,
[ERROR] | WEBSOCKET | 07/08/2025 07:41:11 | Bybit Error subscribing subscribe with request ID 2 msg: Invalid topic :[execution.spot]

I've been getting this using both subscriptions from master and generated ones on this branch

2025-08-06 23:02 UTC, gloriousCode requested changes
I think once the bug is addressed I'm happy with the work

2025-08-06 23:02 UTC, gloriousCode commented on exchanges/bybit/bybit_websocket.go
> +			// adding the channel to selected channels so that we will not visit it again.
```suggestion
			// add channel name to map so we only subscribe to channel once
```

2025-08-06 23:57 UTC, gloriousCode requested changes
This should fix your issues

2025-08-06 23:57 UTC, gloriousCode commented on exchanges/bybit/bybit_websocket.go
> +			log.Warnf(log.WebsocketMgr, "%q has an authenticated subscription %q in config which is not supported. Please remove", e.Name, configSub.Channel)
```suggestion
			log.Warnf(log.WebsocketMgr, "%q has an authenticated subscription %q in config which is not supported. Please remove", e.Name, configSub.Channel)
			configSub.Enabled = false
```

2025-08-06 23:57 UTC, gloriousCode commented on exchanges/bybit/bybit_websocket.go
>  	return true
Update `subTplText` to not process auth endpoints:
```
{{ with $name := channelName $.S }}
	{{- range $asset, $pairs := $.AssetPairs }}
		{{- if isSymbolChannel $name }}
			{{- range $p := $pairs }}
				{{- $name -}} .
				{{- if eq $name "orderbook" -}} {{- $.S.Levels -}} . {{- end }}
				{{- if eq $name "kline" -}} {{- intervalToString $.S.Interval -}} . {{- end }}
				{{- $p }}
				{{- $.PairSeparator }}
			{{- end }}
		{{- end }}
	{{- end }}
	{{- $.AssetSeparator }}
{{- end }}
```

2025-08-07 00:01 UTC, shazbert commented on exchanges/bybit/bybit_websocket.go
>  	return true
https://github.com/thrasher-corp/gocryptotrader/pull/1670/commits/80a5edb11e8b8d4093df7c3d133def5dc2b45b60

2025-08-07 00:32 UTC, gloriousCode approved these changes
i am pleased. tACK

2025-08-07 06:15 UTC, thrasher- commented on exchanges/bybit/bybit_websocket.go
> +			log.Warnf(log.WebsocketMgr, "%q has an authenticated subscription %q in config which is not supported. Please remove", e.Name, configSub.Channel)
```suggestion
			log.Warnf(log.WebsocketMgr, "%s has an authenticated subscription %q in config which is not supported. Please remove.", e.Name, configSub.Channel)
```

Just a consistency nit since we generally use the exchange name without quotes

2025-08-07 06:32 UTC, thrasher- commented on common/common.go
> +	n atomic.Int64 // privatised so you can't use counter as a value type
A wise man once said:

"This realignment due to the requirement for assignment alignment brings no excitement, only chastisement that my review indictment brought defilement"

Howver this change rids the need for such things 😆

2025-08-08 02:18 UTC, gbjk requested changes
Thanks for the updates. 

Just a few change requests and nitpicks.

2025-08-08 02:18 UTC, gbjk commented on common/common.go
> +	n atomic.Int64 // privatised so you can't use counter as a value type
🦍 
```suggestion
	n atomic.Int64 // private so you can't use counter as a value type
```

2025-08-08 02:18 UTC, gbjk commented on common/common.go
>  	// Handle overflow by resetting the counter to 1 if it becomes negative
If this is a straight up counter, why don't we just use `atomic.Uint64` ?

We'd still need to handle overflow it it's already `math.MaxUint64`, but we'd have more available positive values

2025-08-08 02:18 UTC, gbjk commented on common/common_test.go
>  	require.Equal(t, int64(1), c.IncrementAndGet())
Since this test is checking boundary behaviour, it should have a comment.
And if we change to Uint64 the same applies.
```suggestion
	require.Equal(t, int64(1), c.IncrementAndGet(), "Adding to a negative Counter must reset to zero and then increment")
```

2025-08-08 02:18 UTC, gbjk commented on exchanges/bybit/bybit_test.go
> +type DummyConnection struct {
🦍 Just a preference for naming [test fixtures](https://en.wikipedia.org/wiki/Test_fixture).
```suggestion
type FixtureConnection struct {
```

2025-08-08 02:18 UTC, gbjk commented on exchanges/bybit/bybit_test.go
> +		assert.ErrorIsf(t, e.wsHandleData(nil, asset.Spot, []byte(pushDataMap[keys[x]])), expErrFn(keys[x]), "wsHandleData should not error for %s", keys[x])
🚧 The test message here is not correct.
🐒 Additionally this felt less clear and I think we should avoid ErrorIs `nil` where possible
```suggestion
	for x := range keys {
		err := e.wsHandleData(t.Context(), asset.Spot, []byte(pushDataMap[keys[x]]))
		if keys[x] == "unhandled" {
			assert.ErrorIs(t, err, errUnhandledStreamData, "wsHandleData should error correctly for unhandled topics")
		} else {
			assert.NoError(t, err, "wsHandleData should not error")
		}
	}
```

2025-08-08 02:18 UTC, gbjk commented on exchanges/bybit/bybit_websocket.go
> +
🦍 
```suggestion
```

2025-08-08 02:18 UTC, gbjk commented on exchanges/bybit/bybit_websocket.go
> -			{{- if and (isCategorisedChannel $name) ($categoryName := getCategoryName $asset) -}} . {{- $categoryName -}} {{- end }}
🚧 I think this means we should be removing `isCategorisedChannel`.
I can't see it used anywhere. Sorry if I've missed it.

2025-08-08 02:18 UTC, gbjk commented on exchanges/bybit/bybit_websocket.go
> +		return currency.EMPTYPAIR, 0, fmt.Errorf("incoming symbol %q %w: %q", symbol, errUnsupportedCategory, category)
🐒 This error feels back to front
```suggestion
		return currency.EMPTYPAIR, 0, fmt.Errorf("%w %q for symbol %q %w: %q", errUnsupportedCategory, category, symbol)
```

2025-08-08 02:35 UTC, shazbert commented on common/common.go
>  	// Handle overflow by resetting the counter to 1 if it becomes negative
That is a great point! 🔥

2025-08-08 02:53 UTC, shazbert commented on common/common.go
>  	// Handle overflow by resetting the counter to 1 if it becomes negative
Going to defer this as it impacts quite a few things in websocket manager. But your future idea of turning ID's to strings and going towards uuid v7 for default might be better as a complementary update.

2025-08-08 02:54 UTC, shazbert commented on exchanges/bybit/bybit_test.go
> +		assert.ErrorIsf(t, e.wsHandleData(nil, asset.Spot, []byte(pushDataMap[keys[x]])), expErrFn(keys[x]), "wsHandleData should not error for %s", keys[x])
much better

2025-08-08 04:02 UTC, gbjk commented on common/common.go
>  	// Handle overflow by resetting the counter to 1 if it becomes negative
Agreed

2025-08-08 04:07 UTC, gbjk approved these changes
Thanks for addressing those. I'm happy.

2025-08-08 04:22 UTC, thrasher- approved these changes
Changes ACK

2025-08-08 04:22 UTC, merged