bybit: Add websocket trading functionality across all assets
thrasher-corp/gocryptotrader pull request #1672
Opened 2024-10-10 02:05 UTC by shazbert

# PR Description

* Implement trading functions through specific dedicated websocket connection
* Expands IBotExchange wrapper functions to include websocket order operations
* Adds validation methods on PlaceOrderParams, AmendOrderParams, CancelOrderParams to be used across websocket and rest.

#1670 Requires dependency 

Fixes # (issue)

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration and
also consider improving test coverage whilst working on a certain feature or package.

- [ ] go test ./... -race
- [ ] golangci-lint run
- [ ] Test X

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally and on Github Actions with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2025-07-02 21:15 UTC, shazbert commented on exchange/websocket/manager.go
> +		if !m.connectionManager[i].setup.SubscriptionsNotRequired {
NOTE 4 ME: Flush subscriptions now panic will need to fix that.

2025-07-24 23:33 UTC, shazbert commented on exchange/websocket/manager.go
> +		if !m.connectionManager[i].setup.SubscriptionsNotRequired {
FIXED

2025-08-04 00:11 UTC, gloriousCode commented on exchanges/bybit/bybit_types.go
> +	if p.WhetherToBorrow {
`WhetherOrNotShouldBorrowMaybe`

2025-08-12 04:45 UTC, cranktakular commented on exchange/websocket/connection.go
> +func (c *connection) IncomingWithData(signature any, data []byte) bool {
What's the point of this function? Both this and the function it's calling are exported, no data's being added, it's just a slightly less verbose way to call it.

Is that worth it?

2025-08-12 04:55 UTC, cranktakular commented on exchanges/bybit/bybit_types.go
> +	EnableBorrow           bool          `json:"-"`                          // '0' for default spot, '1' for Margin trading.
Comment seems a bit odd, I don't think we need to be told implementation requirements here. As far as the user's concerned, they just need to set this to true/false, which the variable name/type explains sufficiently.

2025-08-12 05:07 UTC, cranktakular commented on exchanges/bybit/bybit_types.go
> +func (p *PlaceOrderParams) Validate() error {
I would like us to have some overarching idea on whether there should be functions in type files or not.

2025-08-12 05:22 UTC, cranktakular commented on exchanges/bybit/bybit_types.go
> +	switch p.TriggerPriceType {
I find it odd how some of these checks are done through switches to check against a list of valid values, but some which seem like they'd have a short list (such as OrderType) just have an if statement checking whether they're empty.

2025-08-12 05:24 UTC, cranktakular commented on exchanges/bybit/bybit_types.go
> +	OrderID     string        `json:"orderId,omitempty"`     // This Required or orderLinkID required
Grammar: "This or orderLinkID required"

2025-08-12 05:30 UTC, cranktakular commented on exchanges/bybit/bybit_types.go
> +	if p.OrderFilter != "" && p.Category == cSpot {
There's a similar check to this in another Validate function, but that time, if the p.Category is not cSpot, it errors out, while here it just ignores that. I'd like some consistency on this.

2025-08-12 05:35 UTC, cranktakular commented on exchanges/bybit/bybit.go
> -	if arg == nil {
With this nil check being removed, if this function's called with a nil arg, it panics. Also applies to other similar cases below.

2025-08-12 06:53 UTC, cranktakular commented on exchanges/bybit/bybit_websocket_requests.go
> +type WebsocketOrderDetails struct {
I'm similarly unsure about including multiple beefy type declarations in a non-types file.

2025-08-12 07:00 UTC, cranktakular commented on exchanges/bybit/bybit_websocket.go
> +func (e *Exchange) WebsocketAuthenticatePrivateConnection(ctx context.Context, conn websocket.Connection) error {
I think this function deserves a different name. Both WebsocketAuthenticatePrivateConnection and WebsocketAuthenticateTradeConnection are handling private data.

How about WebsocketAuthenticateReadConnection and WebsocketAuthenticateWriteConnection? Not great, but they're the best I can come up with.

2025-08-12 07:15 UTC, cranktakular commented on exchanges/bybit/bybit_websocket.go
> +			if conn.IncomingWithData(id, respRaw) {
Seems conceptually weird to send the entire respRaw through, if it's only being matched with the first element. Smells like there's a risk of additional data getting swept in there and matched incorrectly.

2025-08-12 07:22 UTC, cranktakular commented on exchanges/bybit/bybit_websocket_requests.go
> +	Symbol               string        `json:"symbol"` // Undelimitered so inbuilt string used.
Grammar nit: Should be "Undelimited"

2025-08-12 07:25 UTC, cranktakular commented on exchanges/bybit/bybit_websocket_requests.go
> +	ClosedPnl            types.Number  `json:"closedPnl"`
[GK has said](https://github.com/thrasher-corp/gocryptotrader/pull/1480#discussion_r2266802788) acrnoyms and the like should all be in the same case. That hits a few variable names here, Pnl > PNL, Oco > OCO, Tpsl > TPSL, etc.

2025-08-13 00:27 UTC, shazbert commented on exchanges/bybit/bybit_types.go
> +func (p *PlaceOrderParams) Validate() error {
I generally hug validation, marshal, unmarshal methods to types because I am trying to quickly implement, and its easier for me to reference and doesn't pollute the API.go file. If you want me to move it I can.

2025-08-13 00:29 UTC, shazbert commented on exchanges/bybit/bybit_types.go
> +	switch p.TriggerPriceType {
Is there a change request here? Most of this stuff I pulled from existing code, I didn't refactor just added tests.

2025-08-13 00:32 UTC, shazbert commented on exchange/websocket/connection.go
> +func (c *connection) IncomingWithData(signature any, data []byte) bool {
It's for fall back, exchanges send requestIDs or similar but we don't need to match back to a caller if not present and the data can be handled sent through the data handler. That is the only difference. Probably can be refactored but OOS.

2025-08-13 00:44 UTC, shazbert commented on exchanges/bybit/bybit.go
> -	if arg == nil {
I am not too worried about panicking here when this is called, passing in nil value for the param should panic.

2025-08-13 00:47 UTC, shazbert commented on exchanges/bybit/bybit_websocket_requests.go
> +type WebsocketOrderDetails struct {
I can shove them in `bybit_websocket_requests_types.go` file?

2025-08-13 00:48 UTC, shazbert commented on exchanges/bybit/bybit_websocket.go
> +func (e *Exchange) WebsocketAuthenticatePrivateConnection(ctx context.Context, conn websocket.Connection) error {
I am just mapping the functions with bybit's API terminology for connection name.

2025-08-13 00:50 UTC, shazbert commented on exchanges/bybit/bybit_websocket.go
> +			if conn.IncomingWithData(id, respRaw) {
If it does it will error. Then we can fix it.

2025-08-13 01:02 UTC, shazbert commented on exchanges/bybit/bybit_websocket_requests.go
> +	ClosedPnl            types.Number  `json:"closedPnl"`
I think because we aren't consistent with this across the codebase unlike ID; this is unnecessary pedantry. We can get an AI to standardise this and add in a misc linter for it if anybody cares, but I don't.

2025-08-13 01:27 UTC, gloriousCode commented on exchanges/bybit/bybit_websocket_requests.go
> +	ClosedPnl            types.Number  `json:"closedPnl"`
It would have taken you less keyboard presses to change it than to reply 😭

2025-08-13 01:28 UTC, shazbert commented on exchanges/bybit/bybit_websocket_requests.go
> +	ClosedPnl            types.Number  `json:"closedPnl"`
Shh you

2025-08-15 00:57 UTC, gbjk commented on exchanges/bybit/bybit_websocket_requests.go
> +	ClosedPnl            types.Number  `json:"closedPnl"`
🥃  @cranktakular
Sorry; I was a bit lazy on your review, and didn't add citations.

Initialisms and casing is part of the [go style guide](https://google.github.io/styleguide/go/decisions.html#initialisms) which [GCT now references explicitly](https://github.com/thrasher-corp/gocryptotrader/blob/master/docs/CODING_GUIDELINES.md#general-standards)

So, yes, I did say that - but I was just highlighting an existing rule for us.

2025-08-19 00:45 UTC, cranktakular commented on exchanges/bybit/bybit_types.go
> +	switch p.TriggerPriceType {
Ah, in that case we can ignore this for now.

2025-08-19 00:46 UTC, cranktakular commented on exchanges/bybit/bybit_types.go
> +func (p *PlaceOrderParams) Validate() error {
I think that would be nice 🕊️

2025-08-19 00:47 UTC, cranktakular commented on exchanges/bybit/bybit_websocket_requests.go
> +type WebsocketOrderDetails struct {
Sounds nice 🕊️

2025-09-02 02:25 UTC, gloriousCode requested changes
Nice work shazbert. Just a code quality review pass tyty

2025-09-02 02:25 UTC, gloriousCode commented on exchange/websocket/connection.go
> +	MatchReturnResponses(ctx context.Context, signature any, expected int) (<-chan MatchedResponse, error)
If I'm understanding things correctly: `MatchSignatureAcrossConnections`

2025-09-02 02:25 UTC, gloriousCode commented on exchange/websocket/connection.go
> +	connectionListen, err := c.Match.Set(signature, expected)
Just because its a bit obfuscated through interfaces and implementations, how does this work for bybit? You have changed `Match` to be unique per connection, is there a factor I'm missing?  I would like to understand 🌞

2025-09-02 02:25 UTC, gloriousCode commented on exchange/websocket/connection.go
> +	out := make(chan MatchedResponse, 1) // buffered so routine below doesn't leak
Baby brain perhaps, but why would it leak?  I would like to understand 🌞

2025-09-02 02:25 UTC, gloriousCode commented on exchange/websocket/connection.go
> +func (c *connection) IncomingWithData(signature any, data []byte) bool {
Is the purpose of this to allow overriding eg `fixtureConnection`?
Its a little odd only because most places call c.Match. c.IncomingWithData directly eg Binance instead of c.IncomingWithData
Neither your comment or discussion with crank above help me understand it sorry. I would like to understand 🌞

2025-09-02 02:25 UTC, gloriousCode commented on exchanges/bybit/bybit.go
> -	if arg == nil {
@cranktakular Perhaps this needs to be an addition to coding guidelines or add_new_exchange.
Nil checks on API call args is decided we do not worry about and put onus on the caller.
On things above the API implementation, eg wrapper or engine we become a bit more protective

2025-09-02 02:25 UTC, gloriousCode commented on exchanges/bybit/bybit_websocket.go
> +	intNonce := time.Now().Add(time.Hour * 6).UnixMilli()
Please add a comment about why this is a thing

2025-09-02 02:25 UTC, gloriousCode commented on exchanges/bybit/bybit_websocket.go
> +			if conn.IncomingWithData(id, respRaw) {
I don't think there would be an error @shazbert, just that it would get missed... But

That being said @cranktakular, the only places that can utilise this are functions that make requests to the websocket, and those can only make single requests with one orderid.

I would not worry about it since its about matching. If the requests can ever be done in batches we can _force_ shazbert to change 💪

2025-09-02 02:25 UTC, gloriousCode commented on exchanges/bybit/bybit_websocket_requests.go
> +	requestID := strconv.FormatInt(outbound.GenerateMessageID(false), 10)
I know this pr is as old as butts, but have your sensibilities on unique id changed since? Is common.Counter more appropriate? Is @gbjk's uuidv7 more appropriate? This just seems both slow and with a chance of collisions 

```
func BenchmarkButts(b *testing.B) {
	for i := 0; i < b.N; i++ {
		tn := time.Now()
		_ = strconv.FormatInt(tn.UnixNano(), 10) + "hi"
	}
}

func BenchmarkButts2(b *testing.B) {
	cc := common.Counter{}
	for i := 0; i < b.N; i++ {
		_ = strconv.FormatInt(cc.IncrementAndGet(), 10) + "hi"
	}
}
```

```
BenchmarkButts
BenchmarkButts-10     	12789336	        81.96 ns/op	      24 B/op	       1 allocs/op
BenchmarkButts2
BenchmarkButts2-10    	39763627	        30.55 ns/op	       7 B/op	       0 allocs/op
```

2025-09-02 02:31 UTC, gloriousCode commented on exchanges/bybit/bybit_websocket_requests.go
> +	requestID := strconv.FormatInt(outbound.GenerateMessageID(false), 10)
I meant to comment on the line
`argumentID := argument.LoadID(strconv.FormatInt(tn.UnixNano(), 10) + requestID) // UnixNano is used to ensure the ID is unique.`
SOZ

2025-09-02 02:42 UTC, shazbert commented on exchange/websocket/connection.go
> +	MatchReturnResponses(ctx context.Context, signature any, expected int) (<-chan MatchedResponse, error)
The signature is just for the specific expected responses associated with that connection. Doesn't listen to any other connection responses. I will drop `This is used for when a request is sent and a response is expected in a different connection.` because it doesn't really matter what it is used for at this level. 

I can rename to `MatchReturnResponses` -> `PipeResponses` if that is more clearer? Or if you have another suggestion.

2025-09-02 02:44 UTC, gloriousCode commented on exchange/websocket/connection.go
> +	MatchReturnResponses(ctx context.Context, signature any, expected int) (<-chan MatchedResponse, error)
Its current naming is fine based on what you just told me, but the comment update will be appreciated. I think my next review will need to be deeper to better understand what you've done in this PR 🌈

2025-09-02 02:54 UTC, shazbert commented on exchange/websocket/connection.go
> +	connectionListen, err := c.Match.Set(signature, expected)
> Just because its a bit obfuscated through interfaces and implementations, how does this work for bybit?

Just say we have an incoming data and outgoing trade request connection, before sending outbound traffic you can use the messagefilter to get the connection, then set up a pipe to expected incoming data. Then send your outbound trade and then wait on that channel when the data comes back. 

> You have changed Match to be unique per connection, is there a factor I'm missing? 
The match system is specific for that connection now, which may be an issue when we spawn multiple connections for the same endpoint. That may be a future GK's problem. @gbjk

2025-09-02 02:56 UTC, shazbert commented on exchange/websocket/connection.go
> +	out := make(chan MatchedResponse, 1) // buffered so routine below doesn't leak
If there was no receiver because of maybe it errored after it got the channel when sending a message and/or disconnection. the routine below would block.

2025-09-02 03:00 UTC, shazbert commented on exchange/websocket/connection.go
> +func (c *connection) IncomingWithData(signature any, data []byte) bool {
Purpose just shadows the `c.Match` method for multi connection when the connection is available. If `c.Match.IncomingWithData` is used it would fail in `bybit` and `Gateio` as the connection has segregation for multiconnection.

2025-09-02 03:04 UTC, shazbert commented on exchanges/bybit/bybit_websocket.go
> +	intNonce := time.Now().Add(time.Hour * 6).UnixMilli()
Looks strange, but no idea; it's just been copied from previous versions and it works. 🤷

2025-09-02 03:19 UTC, shazbert commented on exchanges/bybit/bybit_websocket_requests.go
> +	requestID := strconv.FormatInt(outbound.GenerateMessageID(false), 10)
Regarding ClientOrderID's:

For the top benchmark there is collisions with pure unix nano because it doesn't provide uniqueness by itself, the clock can be very sticky.

For the bottom just using a common counter can provide uniqueness but only for the first session if you close the program and start trading again it gets reset to zero. 

Probably opt for a UUIDv7 instead for searchability but you are looking at 200ns+ for that. 

What I have done "shouldn't" collide because it uses the requestID (common.Counter) and combines it with a unix nano timestamp. But searchability is bad. 

That was my reasoning which could also be BAD.

2025-09-02 03:27 UTC, shazbert commented on exchange/websocket/connection.go
> +	MatchReturnResponses(ctx context.Context, signature any, expected int) (<-chan MatchedResponse, error)
https://github.com/thrasher-corp/gocryptotrader/pull/1672/commits/2a533a1681eda57e0f998528d20de18584cfc9c1

2025-09-02 04:35 UTC, gloriousCode commented on exchanges/bybit/bybit_wrapper.go
> +		TradingRequirements: protocol.TradingRequirements{
test!

2025-09-02 04:36 UTC, gloriousCode commented on exchanges/bybit/bybit_wrapper.go
> +		TradingRequirements: protocol.TradingRequirements{
success!

2025-09-02 05:03 UTC, gbjk requested changes
Great work 💪 

Partial review, and enough to start on. Will re-review daily for a while.

2025-09-02 05:03 UTC, gbjk commented on exchange/websocket/connection.go
> +// that will receive a MatchedResponse containing the collected responses or an error.
🚧 
* Clarify the use of `but` and `can`, and must:
`These responses must not originate from the same connection as the request, and must come from an alternative connection`
* Remove comment that says what the method signature says
* `sets up` is irrelevant, but that's just a 🦍 

* I think the comment here is really important, which means the method is probably misnamed; It's very counter-intuitive to say that you call `Match` a connection and it actually means _Match on any other connection_
* It's also really messy, and I don't even know how it's working, yet, but: How/Why are we getting to other connections from *this* connection? Surely this method should be on manager?
Do we mean to say "Call this function on other connections" ?
If so, then the comment from earlier becomes different.
```suggestion
// MatchReturnResponses returns channel of exactly expected matched responses
// Must be called on a different connection from the original request
```

2025-09-02 05:03 UTC, gbjk commented on exchange/websocket/connection.go
> +	out := make(chan MatchedResponse, 1) // buffered so routine below doesn't leak
🚧 
```suggestion
	out := make(chan MatchedResponse, 1) // buffered so routine below doesn't block if no receiver
```

2025-09-02 05:03 UTC, gbjk commented on exchange/websocket/subscriptions.go
> +				log.Debugf(log.WebsocketMgr, "%s websocket: skipping connection %s while flushing channels, subscriptions not required", m.exchangeName, m.connectionManager[x].setup.URL)
🥃 I'm perplexed why we need `SubscriptionsNotRequired` ... hope to work it out soon

2025-09-02 05:03 UTC, gbjk commented on exchanges/bybit/bybit_websocket.go
> +// data
🤷 Is this comment true. It feels like it's been copied and should be talking about trade connection

2025-09-02 05:03 UTC, gbjk commented on exchanges/bybit/bybit_websocket.go
> +	intNonce := time.Now().Add(time.Hour * 6).UnixMilli()
Honestly, that's a valid comment on it's own.
Otherwise people think it's authorative.

2025-09-02 05:03 UTC, gbjk commented on exchanges/bybit/bybit_websocket.go
> +	resp, err := conn.SendMessageReturnResponse(ctx, wsSubscriptionEPL, req.RequestID, req)
🚧 If I'm understanding correctly, why are we sending `req.RequestID` if that's not going to be returned, and how does this matcher even work?
I'd expect this:
```suggestion
	resp, err := conn.SendMessageReturnResponse(ctx, wsSubscriptionEPL, "tradeAuth", req)
```
I'm minded to use `tradeAuth` to make thing simpler, even though it's called on `conn`, because it'll work with (inevitable) global matches later.

1️⃣ Global matchers are inevitable because of spawn on demand connections, reversing the current pattern.

2025-09-02 05:03 UTC, gbjk commented on exchanges/bybit/bybit_websocket.go
> +		return conn.RequireMatchWithData(response.Operation, respRaw)
🤷‍♂️ Don't get it; How would this match the RequestID that we sent earlier?
I think we should be sending this as `"tradeAuth:"+response.Operation`
```suggestion
		return conn.RequireMatchWithData("tradeAuth", respRaw)
```

2025-09-02 05:03 UTC, gbjk commented on exchanges/bybit/bybit_websocket_requests.go
> +	WsCancel = "order.cancel"
🚧 I don't think these should be public?
```suggestion
	wsCreateOp = "order.create"
	wsAmendOp  = "order.amend"
	wsCancelOp = "order.cancel"
```

2025-09-02 05:03 UTC, gbjk commented on exchanges/bybit/bybit_websocket_requests_types.go
> +}
🚧 
* I think load is an idiosyncratic term for set
* I don't think this should be a public interface or method
* I think interface implementation details don't need to be stated in the interface; so the comment becomes:
```
// orderLinkIDSetter is an interface to set an order Link ID if not already set
```
* But then ... if it's not public, and it's self-explanatory, probably can remove
* But might want to add `Default` to make it clear it's setting it only if not populated
```suggestion
type orderLinkIDSetter interface {
	setOrderLinkID(string) (string)
}
```

2025-09-02 05:03 UTC, gbjk commented on exchanges/bybit/bybit_websocket_requests.go
> +}
🚧 Matching suggestion that `Load` is an idiosyncratic term, and simplifying comment.
🌴 This change exists in many implementations of this interface
```suggestion
// setID sets the order link ID if not already populated
func (r *PlaceOrderRequest) setOrderLinkID(id string) string {
	if r.OrderLinkID == "" {
		r.OrderLinkID = id
	}
	return r.OrderLinkID
}
```

2025-09-02 05:33 UTC, shazbert commented on exchange/websocket/connection.go
> +// that will receive a MatchedResponse containing the collected responses or an error.
Will just use this; 
// MatchReturnResponses returns channel of exactly expected matched responses

I don't really know why I added in that commentary. It makes no sense. It has nothing to do with any other connection🤷

2025-09-02 05:37 UTC, shazbert commented on exchange/websocket/subscriptions.go
> +				log.Debugf(log.WebsocketMgr, "%s websocket: skipping connection %s while flushing channels, subscriptions not required", m.exchangeName, m.connectionManager[x].setup.URL)
Currently it drops a connection when flush channels is called when there are no subscriptions. Also on start-up it doesn't establish a connection without subscriptions.

2025-09-02 05:51 UTC, shazbert commented on exchanges/bybit/bybit_websocket.go
> +	resp, err := conn.SendMessageReturnResponse(ctx, wsSubscriptionEPL, req.RequestID, req)
> why are we sending req.RequestID if that's not going to be returned

It is returned in the authenticated response, it just gets handled as an "auth" operation in `handleNoTopicWebsocketResponse` :289 in bybit_websocket.go

2025-09-02 05:54 UTC, shazbert commented on exchanges/bybit/bybit_websocket.go
> +		return conn.RequireMatchWithData(response.Operation, respRaw)
This one is for trade connection `WebsocketAuthenticateTradeConnection` and the request id is "auth"

2025-09-02 05:55 UTC, thrasher- commented on exchanges/bybit/bybit_websocket.go
> +	intNonce := time.Now().Add(time.Hour * 6).UnixMilli()
Looks like this is used for the expiration timestamp for auth ws connections: https://bybit-exchange.github.io/docs/v5/ws/connect#authentication so could be renamed to reflect that or commented about

2025-09-02 05:56 UTC, shazbert commented on exchanges/bybit/bybit_websocket_requests.go
> +	WsCancel = "order.cancel"
Will remove them completely

2025-09-02 06:06 UTC, shazbert commented on exchanges/bybit/bybit_websocket.go
> +	intNonce := time.Now().Add(time.Hour * 6).UnixMilli()
Will change variable to expires

2025-09-02 06:15 UTC, samuael commented on exchanges/bybit/bybit_websocket.go
> +	intNonce := time.Now().Add(time.Hour * 6).UnixMilli()
In the code example, they extended the timestamp by 1 second and it doesn't seem the duration the connection stays authenticated. Instead, It looks like the duration this request to get the authenticated connection ID should expire

2025-09-02 06:17 UTC, samuael commented on exchanges/bybit/bybit_websocket.go
> +	intNonce := time.Now().Add(time.Hour * 6).UnixMilli()
I think it is me who named it like this. But it could also be renamed to 'expires' like in the documentation

2025-09-02 06:47 UTC, samuael commented on exchanges/interfaces.go
> +	WebsocketModifyOrder(ctx context.Context, action *order.Modify) (*order.ModifyResponse, error)
(Optional) Since you are half way to it ... you could add the CLI support for these methods.

2025-09-02 07:02 UTC, samuael commented on exchanges/bybit/bybit_wrapper.go
> +	err := s.Validate(e.GetTradingRequirements())
This is called inside the `DeriveSubmitOrderArguments` method and no need to repeat it here

2025-09-02 07:23 UTC, samuael commented on exchanges/bybit/bybit_wrapper.go
> +	switch orderDetails.TimeInForce {
You could use the `order.StringToTimeInForce` method call wherever this happen instead of hard-coding it here

2025-09-02 08:08 UTC, cranktakular commented on exchanges/bybit/bybit.go
> -	if arg == nil {
That sounds like a glorious idea.

2025-09-02 08:53 UTC, cranktakular requested changes
Exchange-wide test is hitting an error:
```
--- FAIL: TestAllExchangeWrappers (0.62s)
    --- FAIL: TestAllExchangeWrappers/bybit_wrapper_tests (3.14s)
        --- FAIL: TestAllExchangeWrappers/bybit_wrapper_tests/WebsocketSubmitOrder-options-ETH-TEST-DELIM-26jun26-7400-p-usdt (0.00s)
            exchange_wrapper_standards_test.go:232: Bybit Func 'WebsocketSubmitOrder' Error: 'invalid category, orderFilter is valid for 'spot' only'. Inputs: [<context> {bybit LIMIT BUY ETH-TEST-DELIM-26jun26-7400-p-usdt options IOC false 1 150 1 0 0 LastPrice 1337 13371337 false  false 0s { {false LastPrice 0 0 UNKNOWN} {false LastPrice 0 0 UNKNOWN} {false LastPrice 0 0 UNKNOWN}} false false  0}].
```
Alongside 7 other nigh-identical fails.

Other than that, the specific changes I pointed out were adequately addressed (aside from filling out the checklist), but I haven't had the time to investigate all the other changes, so I may come back with more concerns later.

2025-09-02 23:39 UTC, gloriousCode commented on exchanges/bybit/bybit_websocket.go
> +	intNonce := time.Now().Add(time.Hour * 6).UnixMilli()
Yeah if it could be confirmed as the expiry, then please rename to that tyty

2025-09-03 00:33 UTC, shazbert commented on exchanges/bybit/bybit_websocket.go
> +	intNonce := time.Now().Add(time.Hour * 6).UnixMilli()
It's already been done my dudes.

2025-09-03 00:35 UTC, shazbert commented on exchanges/interfaces.go
> +	WebsocketModifyOrder(ctx context.Context, action *order.Modify) (*order.ModifyResponse, error)
defer this for merge, can be integrated in your PR: https://github.com/thrasher-corp/gocryptotrader/pull/1965 if you so choose.

2025-09-03 00:36 UTC, shazbert commented on exchanges/bybit/bybit_wrapper.go
> +	err := s.Validate(e.GetTradingRequirements())
Nice catch!

2025-09-03 01:04 UTC, gloriousCode commented on exchanges/bybit/bybit_websocket.go
> +	intNonce := time.Now().Add(time.Hour * 6).UnixMilli()
how dare you

2025-09-03 10:50 UTC, samuael commented on exchange/websocket/connection_test.go
> +	require.Equal(t, exp, (<-ch).Responses[0])
You could just use `assert` for this one

2025-09-05 02:30 UTC, gbjk commented on exchange/websocket/subscriptions.go
> +				log.Debugf(log.WebsocketMgr, "%s websocket: skipping connection %s while flushing channels, subscriptions not required", m.exchangeName, m.connectionManager[x].setup.URL)
If debugging that really helps you, after initial development, great 👍 
Consider if it does and remove if it's just a vestigial tail.

2025-09-05 02:32 UTC, shazbert commented on exchange/websocket/subscriptions.go
> +				log.Debugf(log.WebsocketMgr, "%s websocket: skipping connection %s while flushing channels, subscriptions not required", m.exchangeName, m.connectionManager[x].setup.URL)
Yeah I will probably remove that,.

2025-09-05 02:37 UTC, gbjk commented on exchanges/bybit/bybit_websocket.go
> +	resp, err := conn.SendMessageReturnResponse(ctx, wsSubscriptionEPL, req.RequestID, req)
🚧 ~Sorry, then can you read your comment at L126-127 ?~
~I think they need removing. I'll comment again there.~

I get it. I'll comment on the comment to make the comment clearer.

2025-09-05 02:47 UTC, gbjk commented on exchanges/bybit/bybit_websocket.go
> +	resp, err := conn.SendMessageReturnResponse(ctx, wsSubscriptionEPL, req.RequestID, req)
Nope. Don't get it.

Your comment says we don't use the RequestID in WebsocketAuthenticateTradeConnection L126-127 , so we use auth as the RequestID.
But then we're expecting responses.
wsHandleAuthenticatedData throws the ball to handleNoTopicWebsocketResponse like you say, and then we do case auth on the Operation...
...
But then ... we send a response to the waiting handler using result.RequestID ?
So ... did we get auth back in the RequestID field?
If we didn't, shouldn't that line be using the Operation as the RequireMatchWithData ?
Is this definitely working and integrating the response?

2025-09-05 03:53 UTC, gbjk commented on exchanges/bybit/bybit_websocket.go
> +		// so the first element will be used to match the order link ID.
🚧 
Where you say "there is no batch support", do you mean we're just sending one order at a time, receiving one response, and matching?
Or is it as I'm thinking, and we send a single request with n+ and we match the response based on just the first one?
In either case: ~Below provides a way~
```suggestion
		// Use first order's orderLinkId to match with an entire batch of order change request
```

2025-09-05 04:17 UTC, gbjk commented on exchanges/bybit/bybit_websocket_requests.go
> +	argumentID := argument.setOrderLinkID(strconv.FormatInt(tn.UnixNano(), 10) + requestID) // UnixNano is used to ensure the ID is unique.
🚧 
* I think that's doubling the job of the ID generator
* I also don't think it ensures the ID is unique
* I also think it's orderLinkId
* Could we use UUID v7 for this?
```suggestion
	orderLinkID := argument.setOrderLinkID(strconv.FormatInt(tn.UnixNano(), 10) + requestID) // UnixNano is used to reduce the chance of an ID clash
```

2025-09-05 04:20 UTC, gbjk commented on exchanges/bybit/bybit_websocket_requests.go
> +func (e *Exchange) SendWebsocketRequest(ctx context.Context, op string, argument orderLinkIDSetter, limit request.EndpointLimit) (*WebsocketOrderDetails, error) {
🚧 I see that they call it Argument. But it confused the reader until that point.
It's the payload, or request, or something.
```suggestion
func (e *Exchange) SendWebsocketRequest(ctx context.Context, op string, payload orderLinkIDSetter, limit request.EndpointLimit) (*WebsocketOrderDetails, error) {
```

2025-09-05 04:26 UTC, gbjk commented on exchanges/bybit/bybit_websocket_requests.go
> +	inResp := <-wait
🐒 
```suggestion
	inResp := <-wait // Blocking read okay; wait channel has a built in timeout already
```

2025-09-05 04:28 UTC, gbjk commented on exchanges/bybit/bybit_websocket_requests.go
> +	10019: "ws trade service is restarting, do not accept new request, but the request in the process is not affected. You can build new connection to be routed to normal service",
🐒 Feels like we shouldn't be accepting their messages here.
```suggestion
	10404: "either op type is not found or category is not correct/supported",
	10429: "request exceeds rate limit",
	20006: "reqId is duplicated",
	10016: "internal server error",
	10019: "ws trade service is restarting, please reconnect",
```

2025-09-05 04:31 UTC, gbjk commented on exchanges/bybit/bybit_websocket_requests_test.go
> +// This restricts the pairs to a single pair per asset type to reduce test time.
🤷  Is this not something we could do in `./testdata/configtest.json` ?
Just checking. Answer can be no.

2025-09-05 04:34 UTC, gbjk commented on exchanges/bybit/bybit_websocket_requests_test.go
> +	cpy.CurrencyPairs.Load(&e.CurrencyPairs)
🚧 Think this is the only thing we're using.
I think I'd like to use `e` instead of `cpy` to reduce risk of copy/paste or hitting the wrong instance.
In this function, `cpy` is the new and only `Exchange` we want to touch.
So:
```suggestion
	pairs := &e.CurrencyPairs
	[...]
	e := new(Exchange)
	e.CurrencyPairs.Load(pairs)
```

2025-09-05 04:35 UTC, gbjk commented on exchanges/bybit/bybit_websocket_test.go
> +		require.ErrorIs(t, e.wsHandleTradeData(conn, tc.input), tc.err)
🚧 Same as normal - Don't want to do `ErrorIs` on `nil` please.

2025-09-05 06:53 UTC, shazbert commented on exchanges/bybit/bybit_websocket.go
> +		// so the first element will be used to match the order link ID.
This is a better comment. Thanks!

2025-09-05 06:57 UTC, shazbert commented on exchanges/bybit/bybit_websocket_requests.go
> +	argumentID := argument.setOrderLinkID(strconv.FormatInt(tn.UnixNano(), 10) + requestID) // UnixNano is used to ensure the ID is unique.
Will change it over to UUID and test externally

2025-09-05 07:23 UTC, shazbert commented on exchanges/bybit/bybit_websocket_requests_test.go
> +	cpy.CurrencyPairs.Load(&e.CurrencyPairs)
Yeah good idea!

2025-09-05 07:28 UTC, shazbert commented on exchanges/bybit/bybit_websocket_requests_test.go
> +// This restricts the pairs to a single pair per asset type to reduce test time.
Yeah it should work; but if its resized later for any reason then it could slow everything down 🦐. Up to you if you want me to try to change.

2025-09-05 09:19 UTC, samuael commented on exchange/websocket/manager.go
> +		if c.Unsubscriber == nil && m.features.Unsubscribe && !c.SubscriptionsNotRequired {
Why are we using this `m.features.Unsubscribe` here but not `m.features.Subscribe` in the above if statement?

2025-09-05 09:23 UTC, samuael commented on exchange/websocket/manager.go
> +		if c.Subscriber == nil && !c.SubscriptionsNotRequired {
if we are going to use this `c.SubscriptionNotRequired` boolean variable, why do we still have the `m.features.Subscribe`? I may be mistakened but I don't see the advantage of having both `features.Subscribe` and `c.SubscriptionNotRequired` fields at the same time.

2025-09-05 09:40 UTC, samuael commented on exchanges/bybit/bybit.go
> +	validCategory       = []string{"spot", "linear", "inverse", "option"}
```suggestion
	validCategory       = []string{cSpot, cLinear, cOption, cInverse}
```

2025-09-05 09:41 UTC, samuael commented on exchanges/bybit/bybit.go
>  	if arg.Category == "spot" {
OOS but you can replace such occurances with the constant declarations like cSpot, cLinear ..

2025-09-05 09:42 UTC, samuael commented on exchanges/bybit/bybit.go
> +	var resp OrderResponse
```suggestion
	var resp *OrderResponse
```
just for consistency.

2025-09-05 09:50 UTC, samuael commented on exchanges/bybit/bybit_types.go
> +var errAmendArgumentsRequired = errors.New("at least one of the following fields is required: orderIv, triggerPrice, qty, price, takeProfit, stopLoss")
You can move this error variable to the list of declarations in the _bybit.go_

2025-09-05 10:08 UTC, samuael commented on exchanges/bybit/validate_test.go
> +func TestValidateCancelOrderRequest(t *testing.T) {
no code coverage for "options", and "inverse" orders?

2025-09-05 10:11 UTC, samuael commented on exchanges/interfaces.go
> +	WebsocketModifyOrder(ctx context.Context, action *order.Modify) (*order.ModifyResponse, error)
That's a good alternative 🫡 . 👍

2025-09-05 10:15 UTC, samuael commented on exchanges/request/limit.go
> +var RateLimitNotRequired *RateLimiterWithWeight
Why is this variable declared here since it is not used anywhere in the codebase to bypass the ratelimit? I couldn't find a place where this is used. Including in **_connection.go_** file.

2025-09-06 04:56 UTC, gbjk commented on exchanges/bybit/bybit_websocket_requests_test.go
> +// This restricts the pairs to a single pair per asset type to reduce test time.
Yeah, please try. It just simplifies everything.
I found myself massaging the test config sometimes instead of changing it. It's a deferred ownership problem.
If you want can make it a test failure if someone resizes it, so they have to engage in the problem. `require.Len(t, len(pairs), 1)`.
But also, if they embedded the entire Doom game into the pairs that'd slow things down too.
Can probably worry about these problems if they arrise.

2025-09-06 05:16 UTC, gbjk commented on exchanges/bybit/bybit_websocket_requests.go
> +	orderLinkID := payload.setOrderLinkID(func() string { return uuid.Must(uuid.NewV7()).String() })
🚧 Whoa there 🤠; This definitely is starting to feel over-complicated when we're closuring like this.
I'm sensing that you're doing this to avoid generating a UUID if we're not going to use it. Understandable.

However you just hit gold, pardner.

The link ID you're using is *either* a new UUID, OR it's what's already there, right?
So we don't need to do the generation here.
We can do it inside the function.

But then... all this boilerplate ... and we're only calling this from 3 places.

So this seems like a much better pattern. Simpler, cleaner and more direct.

gbjk@658cff18f

2025-09-06 05:50 UTC, gbjk requested changes
Partial review
24 / 30

2025-09-06 05:50 UTC, gbjk commented on exchanges/bybit/bybit_wrapper.go
> +			SpotMarketOrderAmountPurchaseQuotationOnly: true,
👀  Erm. Okay then.
🥃 This feels like `Quotation: true` 😂

2025-09-06 05:50 UTC, gbjk commented on exchanges/bybit/bybit_wrapper.go
> +		MessageFilter:         InboundPrivateConnection,
🥃 Interesting. This will be compatible with the `websocket.MessageFilter` interface I'm working on, and isn't an asset. Excellent.

2025-09-06 05:50 UTC, gbjk commented on exchanges/bybit/bybit_wrapper.go
> +// ModifyOrder will allow of changing orderbook placement and limit to market conversion
🐒 I think "orderbook placement" is a complex way of saying "changing the price" ?
```suggestion
// ModifyOrder modifies an existing order, including price and order type
```
or just
```suggestion
// ModifyOrder modifies an existing order
```

2025-09-06 05:50 UTC, gbjk commented on exchanges/bybit/bybit_wrapper.go
> +// connection.
🐒 As above

2025-09-06 05:50 UTC, gbjk commented on exchanges/bybit/bybit_wrapper.go
> +// WebsocketCancelOrder cancels an order by its corresponding ID number
🐒 
```suggestion
// WebsocketCancelOrder cancels an order by ID
```

2025-09-06 05:50 UTC, gbjk commented on exchanges/bybit/order_arguments.go
> +// DeriveSubmitOrderArguments returns a derived order arguments struct from an order.Submit for use in this package.
🚧 
* `for use in this package` is both incorrect (since it's exported) and not really useful. If you mean it should be private, then it should be private.
* `derived` loses meaning in the middle of this sentence
```suggestion
// DeriveSubmitOrderArguments returns a PlaceOrderRequest from an order.Submit
```

2025-09-06 05:50 UTC, gbjk commented on exchanges/bybit/order_arguments.go
> +// DeriveAmendOrderArguments returns a derived order arguments struct from an order.Modify for use in this package.
🐒 As above

2025-09-06 05:50 UTC, gbjk commented on exchanges/bybit/order_arguments.go
> +// DeriveCancelOrderArguments returns a derived order arguments struct from an order.Cancel for use in this package.
🐒 As above

2025-09-06 05:50 UTC, gbjk commented on exchanges/bybit/order_arguments_test.go
> +		require.ErrorIs(t, err, tc.err)
🚧 `ErrorIs` + `NoError` pattern please

2025-09-06 05:50 UTC, gbjk commented on exchanges/bybit/order_arguments_test.go
> +		require.ErrorIs(t, err, tc.err)
🐒 As above

2025-09-06 05:50 UTC, gbjk commented on exchanges/bybit/order_arguments_test.go
> +		require.ErrorIs(t, err, tc.err)
🐒 As above

2025-09-06 05:50 UTC, gbjk commented on exchanges/bybit/ratelimit.go
> +	defaultEPL:                               request.NewRateLimitWithWeight(time.Second*5 /* See: https://bybit-exchange.github.io/docs/v5/rate-limit */, 600, 1),
🚧 Definitely not okay to have a comment in the middle like this, IMO.
```suggestion
	defaultEPL:                               request.NewRateLimitWithWeight(time.Second*5, 600, 1),  // https://bybit-exchange.github.io/docs/v5/rate-limit
```

2025-09-06 05:50 UTC, gbjk commented on exchanges/bybit/ratelimit_test.go
> +			require.ErrorIs(t, err, tc.err)
🐒 As above

2025-09-06 05:50 UTC, gbjk commented on exchanges/bybit/unmarshal.go
> +}
🦍 Don't feel this is worth it's own file.
Only care because when I `/unmar` I'll get this.
Feel it could really live right next to the type, tbh.

2025-09-06 05:50 UTC, gbjk commented on exchanges/bybit/validate.go
> +		return errAmendArgumentsRequired
🤷‍♂️ Is this really a problem though?
Would the exchange error?
Feel like we don't need to handhold the consumers here.

2025-09-06 05:50 UTC, gbjk commented on exchanges/bybit/validate_test.go
> +		require.ErrorIs(t, tc.params.Validate(), tc.err)
🐒 As above

2025-09-06 05:50 UTC, gbjk commented on exchanges/bybit/validate_test.go
> +		require.ErrorIs(t, tc.params.Validate(), tc.err)
🌴

2025-09-06 05:50 UTC, gbjk commented on exchanges/bybit/validate_test.go
> +		require.ErrorIs(t, tc.params.Validate(), tc.err)
🌴

2025-09-07 22:40 UTC, shazbert commented on exchange/websocket/manager.go
> +		if c.Unsubscriber == nil && m.features.Unsubscribe && !c.SubscriptionsNotRequired {
All exchanges have subscribe functionality. In the past there were some that didn't have that functionality for unsubscribe

2025-09-07 22:43 UTC, shazbert commented on exchange/websocket/manager.go
> +		if c.Subscriber == nil && !c.SubscriptionsNotRequired {
This is for a specific connection; the exchange can support subscriptions in general. We could RM the field `features.Subscribe` but that can be done later with more thought. OOS.

2025-09-07 22:49 UTC, shazbert commented on exchanges/bybit/validate_test.go
> +func TestValidateCancelOrderRequest(t *testing.T) {
There are no divergent paths with those options, full coverage is maintained already

2025-09-07 22:50 UTC, shazbert commented on exchanges/request/limit.go
> +var RateLimitNotRequired *RateLimiterWithWeight
External usage and will be used in other places across exchanges

2025-09-07 23:07 UTC, shazbert commented on exchanges/bybit/bybit_websocket_requests.go
> +	orderLinkID := payload.setOrderLinkID(func() string { return uuid.Must(uuid.NewV7()).String() })
https://github.com/thrasher-corp/gocryptotrader/pull/1672/commits/e130ace9dc9e6de0825fbc8f588e468ff8096d72

Much better! 🔥

2025-09-07 23:13 UTC, shazbert commented on exchanges/bybit/bybit_wrapper.go
> +			SpotMarketOrderAmountPurchaseQuotationOnly: true,
Can you check this change out: https://github.com/thrasher-corp/gocryptotrader/pull/1672/commits/f583c04a131b4ed8366803ffa1900d50ea5f0595

2025-09-07 23:19 UTC, shazbert commented on exchanges/bybit/bybit_wrapper.go
> +// ModifyOrder will allow of changing orderbook placement and limit to market conversion
This will change across all exchanges; think we should defer this for a standardisation pass. The second option is good. 👍

2025-09-07 23:29 UTC, shazbert commented on exchanges/bybit/unmarshal.go
> +}
Got winged at by having funcs in types file, I prefer it hugged with the type as well. But I will be adding specific unmarshallers when #1957 gets merged so this will be more populated. So up to you.

2025-09-07 23:29 UTC, shazbert commented on exchanges/bybit/validate.go
> +		return errAmendArgumentsRequired
Don't know; but will rm it.

2025-09-08 00:03 UTC, shazbert commented on exchanges/bybit/bybit_websocket_requests_test.go
> +// This restricts the pairs to a single pair per asset type to reduce test time.
https://github.com/thrasher-corp/gocryptotrader/pull/1672/commits/f80ab342c56ab5cd9326e9f781131b4178baf5fa

Didn't add check because pairs could be added later for other tests and such, just be slow.

2025-09-08 00:05 UTC, shazbert commented on exchange/websocket/subscriptions.go
> +				log.Debugf(log.WebsocketMgr, "%s websocket: skipping connection %s while flushing channels, subscriptions not required", m.exchangeName, m.connectionManager[x].setup.URL)
https://github.com/thrasher-corp/gocryptotrader/pull/1672/commits/4d8abd9a4e0753ceb5d6d7b3e4eb7d4afcb70d55

2025-09-08 04:50 UTC, gbjk commented on exchanges/bybit/bybit_wrapper.go
> +			SpotMarketOrderAmountPurchaseQuotationOnly: true,
Smells good 👍

2025-09-08 04:52 UTC, gbjk commented on exchanges/bybit/bybit_wrapper.go
> +// ModifyOrder will allow of changing orderbook placement and limit to market conversion
Erm, yikes. Agreed.

2025-09-08 04:54 UTC, gbjk commented on exchanges/bybit/unmarshal.go
> +}
I agree. I don't even like having types files though.
Could stick it in the bottom of `bybit.go`

It was a 🦍 super nit, so you really don't have to action at all.

2025-09-08 07:18 UTC, thrasher- commented
@codex please review

2025-09-08 14:08 UTC, samuael approved these changes

2025-09-08 20:38 UTC, shazbert commented on exchanges/bybit/bybit_wrapper.go
>  	return err
Nice catch!

2025-09-08 20:41 UTC, shazbert commented on exchanges/bybit/bybit_websocket_requests_types.go
> +	OrderStatus                string        `json:"orderStatus"`
It has the `UnmarshalJSON` definition in the order package.

2025-09-08 22:11 UTC, shazbert commented on exchanges/bybit/bybit_wrapper.go
> +// ModifyOrder will allow of changing orderbook placement and limit to market conversion
@gbjk Added to #2044 can you please check this out and add more items you think need to be changed when you get a chance.

2025-09-09 05:24 UTC, cranktakular approved these changes
Insignificant grammar nit aside, I can tACK this.

2025-09-09 05:24 UTC, cranktakular commented on exchanges/bybit/bybit_websocket.go
> +		// Use first order's orderLinkId to match with an entire batch of order change request
Grammar nit: "request" > "requests"

2025-09-12 01:39 UTC, shazbert commented on exchanges/bybit/bybit_websocket.go
> +		// Use first order's orderLinkId to match with an entire batch of order change request
[done](https://github.com/thrasher-corp/gocryptotrader/pull/1672/commits/0aefe67b53292d059f3e5c817a1deb4b4c7ffe8e)

2025-09-16 01:47 UTC, cranktakular approved these changes
Looks good!

2025-09-16 02:32 UTC, gloriousCode commented on exchanges/bybit/bybit_websocket_requests.go
> +func (e *Exchange) SendWebsocketRequest(ctx context.Context, op, orderLinkID string, payload any, limit request.EndpointLimit) (*WebsocketOrderDetails, error) {
```suggestion
func (e *Exchange) SendWebsocketTradeRequest(ctx context.Context, op, orderLinkID string, payload any, limit request.EndpointLimit) (*WebsocketOrderDetails, error) {
```
Only because you have hardcoded its purpose

2025-09-16 02:33 UTC, gloriousCode commented on exchanges/bybit/bybit_websocket_requests.go
> +	wait, err := inbound.MatchReturnResponses(ctx, orderLinkID, 1)
```suggestion
	ch, err := inbound.MatchReturnResponses(ctx, orderLinkID, 1)
```
Not just a waiter since its also supplying data

2025-09-16 02:33 UTC, gloriousCode commented on exchanges/bybit/bybit_websocket_requests.go
> +	inResp := <-wait // Blocking read okay; wait channel has a built in timeout already
```suggestion
	inResp := <-wait // Blocking read is acceptable; wait channel has a built in timeout already
```
Otherwise you sound sassy

2025-09-16 02:49 UTC, gloriousCode commented on exchanges/bybit/bybit_websocket_requests.go
> +	10016: "internal server error",
> 20003	Too frequent requests under the same session

2025-09-16 02:54 UTC, gloriousCode commented on exchanges/bybit/bybit_websocket_requests_test.go
> +// This restricts the pairs to a single pair per asset type to reduce test time.
Now update comment 🌈

2025-09-16 02:57 UTC, gloriousCode commented on exchanges/bybit/bybit_wrapper.go
> +
```suggestion
```

2025-09-16 03:08 UTC, gloriousCode commented on exchanges/bybit/bybit.go
> +func (e *Exchange) CancelTradeOrder(ctx context.Context, arg *CancelOrderRequest) (*OrderResponse, error) {
Your removal of the nil check left un-run tests with nil scenarios to panic

2025-09-16 03:09 UTC, gloriousCode commented on exchanges/bybit/bybit.go
> +	if err := arg.Validate(); err != nil {
Your removal of the nil check left un-run tests with nil scenarios to panic

2025-09-16 03:10 UTC, gloriousCode commented on exchanges/bybit/bybit.go
> +	if err := arg.Validate(); err != nil {
Your removal of the nil check left un-run tests with nil scenarios to panic

2025-09-17 01:39 UTC, thrasher- requested changes
Nice fat PR! Bybit coverage increased by 2.4% 🚀 Tested websocket auth but didn't test orders aside from checking out the test coverage you've added. Just some basic nits:

An out of scope request would be to adjust this message to specify the exchange name in this log: https://github.com/thrasher-corp/gocryptotrader/blob/master/engine/websocketroutine_manager.go#L331 since ATM we have unhandled responses based on successful ws subs

2025-09-17 01:39 UTC, thrasher- commented on exchanges/bybit/bybit_websocket.go
> +		return fmt.Errorf("%s failed - code:%d [%v] msg:%s", response.Operation, response.ReturnCode, retCode[response.ReturnCode], response.ReturnMessage)
```suggestion
        c, ok := retCode[response.ReturnCode]
        if !ok {
                "unknown return error code"
        }
	return fmt.Errorf("%s failed - code:%d [%v] msg:%s", response.Operation, response.ReturnCode, c, response.ReturnMessage)
```

2025-09-17 01:39 UTC, thrasher- commented on exchanges/bybit/bybit_websocket_requests.go
> +var retCode = map[int64]string{
10403: exceed IP rate limit. 3000 requests per second per IP but see other comment for protection in case this changes

Then looks like we have all the codes covered for trades https://bybit-exchange.github.io/docs/v5/websocket/trade/guideline

2025-09-17 03:45 UTC, thrasher- approved these changes
Changes ACK, thank you!

2025-09-17 03:45 UTC, merged