stream/buffer: remove time.ticker publish limiter for websocket orderbook updates
thrasher-corp/gocryptotrader pull request #1681
Opened 2024-10-14 23:27 UTC by shazbert

# PR Description

* Removes intentional restriction of websocket orderbook publication of change through data handler as engine websocket routine handling couldn't keep up with updates. ~~This limits~~ Was limiting change detection through channel communication when using websocket incremental orderbook updates. 

Fixes # (issue)

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration and
also consider improving test coverage whilst working on a certain feature or package.

- [ ] go test ./... -race
- [ ] golangci-lint run
- [ ] Test X

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally and on Github Actions with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2025-02-03 00:26 UTC, gloriousCode approved these changes
tACK

2025-02-05 00:07 UTC, thrasher- requested changes
Just some minor grammar nitters and then looks GTG

2025-02-05 00:07 UTC, thrasher- commented on config/versions/v3.go
> +// UpgradeExchange will remove the orderbook and publishPeriod from the exchange config
```suggestion
// UpgradeExchange will remove the publishPeriod from the exchange's orderbook config
```

2025-02-05 00:07 UTC, thrasher- commented on config/versions/v3.go
> +// Version3 is an ExchangeVersion to remove the orderbook and publishPeriod from the exchange config
```suggestion
// Version3 is an ExchangeVersion to remove the publishPeriod from the exchange's orderbook config
```

2025-02-05 00:07 UTC, thrasher- commented on config/versions/v3.go
> +// DowngradeExchange will downgrade the exchange config with the default orderbook publish period
```suggestion
// DowngradeExchange will downgrade the exchange's config by setting the default orderbook publish period
```

2025-02-10 00:42 UTC, thrasher- requested changes
Two other minor things and then this looks GTG!

2025-02-10 00:42 UTC, thrasher- commented on config/versions/v3.go
> +type Version3 struct {
```suggestion
type Version3 struct {}
```

2025-02-10 00:42 UTC, thrasher- commented on config/versions/v3.go
> +var defaultOrderbookPublishPeriod = time.Second * 10
```suggestion
const defaultOrderbookPublishPeriod = time.Second * 10
```

2025-02-10 04:22 UTC, cranktakular approved these changes
tACK. Noticed a fail for lbank when testing this that I didn't find in master, but running it back it seems to be an intermittent issue. Given how it seemed unrelated to these changes, I believe it's fine.

2025-02-10 05:05 UTC, thrasher- approved these changes
Thanks for making those changes!

2025-02-10 05:15 UTC, merged