Bitmex: Fix handling index records in WS trade stream
thrasher-corp/gocryptotrader pull request #1685
Opened 2024-10-19 01:54 UTC by gbjk

Fixes handling for Size == 0 index records sent to trade stream

Fixes #1684 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How has this been tested

- [x] go test ./... -race
- [x] golangci-lint run
- [x] TestWsTrades

2024-10-23 00:33 UTC, gloriousCode approved these changes
I do appreciate the fix. Its just that we don't actually have support in place because [WS support was removed for index](https://github.com/thrasher-corp/gocryptotrader/blame/2232340d499b108a93f02d4447167bebce976542/exchanges/bitmex/bitmex_wrapper.go#L73)
In addition, I needed to add support for the "." prefix for index subscriptions.

After those I can confirm the fix works with real data
<img width="954" alt="image" src="https://github.com/user-attachments/assets/faf4e34f-e4c2-43c7-acad-2936a90e7053">

2024-10-23 23:00 UTC, shazbert requested changes
One thing from me and when you have time please rebase. Thanks!

2024-10-24 00:27 UTC, gbjk commented on exchanges/exchange.go
> +	ErrSymbolCannotBeMatched = errors.New("symbol cannot be matchedX")
Fixed [9ac5b93](https://github.com/thrasher-corp/gocryptotrader/pull/1685/commits/9ac5b9398cc48d852609b1c77499c008bdb6e359)

2024-10-24 00:29 UTC, gbjk commented
> One thing from me and when you have time please rebase. Thanks!

Had the stack ready for this. All done :)

2024-10-25 08:57 UTC, thrasher- approved these changes
Thanks for looking into this

2024-10-25 08:57 UTC, merged