types/time: filter string that cannot be a unix timestamp
thrasher-corp/gocryptotrader pull request #1715
Opened 2024-11-12 03:50 UTC by shazbert

# PR Description

Did not error when using incorrect type. So force check, more performant using time.Time type for that use case so not going to handle potential edge case.

Cherry-picked from #1670 

Fixes # (issue)

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration and
also consider improving test coverage whilst working on a certain feature or package.

- [ ] go test ./... -race
- [ ] golangci-lint run
- [ ] Test X

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally and on Github Actions with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-11-20 02:38 UTC, thrasher- requested changes

2024-11-20 02:38 UTC, thrasher- commented on types/time_test.go
> +	require.Error(t, json.Unmarshal([]byte(`"123456"`), &testTime))
```suggestion
	require.Error(t, json.Unmarshal([]byte(`123456`), &testTime))
```
Otherwise this is a duplicated test from above

2024-11-20 03:01 UTC, thrasher- approved these changes
Thanks for making those changes

2024-12-02 23:14 UTC, cranktakular approved these changes
With that newest change, everything looks good!

2024-12-02 23:40 UTC, gloriousCode requested changes

2024-12-02 23:40 UTC, gloriousCode commented on types/time.go
> +		return badSyntax // exit early
You have no choice but to return something at the end of the func with a return param. IndexFunc only returns early if the response is true.

rm comment

2024-12-02 23:40 UTC, gloriousCode commented on types/time.go
> +			return strconv.ErrSyntax
strconv standard errors such as the parseint below wrap the error and highlight the original string to demonstrate why it failed. You can wrap it here too

2024-12-02 23:40 UTC, gloriousCode commented on types/time.go
> +		// As a mistake this type can be used instead of time.Time and parse int below will not fail.
```suggestion
		// types.Time may only parse numbers. The below check ensures an error is thrown if time.Time should be used to parse the string instead
```

2024-12-03 21:53 UTC, gloriousCode approved these changes
tack

2024-12-03 23:00 UTC, merged