Config: Move OrderManager to version management
thrasher-corp/gocryptotrader pull request #1737
Opened 2024-12-04 03:41 UTC by gbjk

* Replaces `*bool` with a boolean in `orderManager.Enabled` and `orderManager.RespectOrderHistoryLimits`
* Replaces negative `FuturesTrackingSeekDuration` with positive
* Removes runtime default FuturesTrackingSeekDuration and replaces with an error

## Stacked Dependencies
- [ ] #1671
- [ ] #1735 ( Only due to version numbering )

## Type of change

- [x] New feature (non-breaking change which adds functionality)

2025-02-11 00:24 UTC, shazbert requested changes
Had a quick look over, I would like to make a recommendation to remove `convert.BoolPtr` completely and fix up the other bool pointers relating to config like logger. That way we can just do one version upgrade?

2025-02-14 04:32 UTC, gbjk commented
> Had a quick look over, I would like to make a recommendation to remove `convert.BoolPtr` completely and fix up the other bool pointers relating to config like logger. That way we can just do one version upgrade?

I considered this overnight. I'm always tempted to accept a challenge like this.
However the scope is already quite big, the features are unrelated, removing convert.BoolPtr completely sooner isn't enough to balance out mixing changes together, and more than one version upgrade isn't a problem.
I really prefer to keep changes discrete, so that rolling them back is cleaner, reviews are easier/faster.

I've got the others in my sights as well, they won't be forgotten.

So, I'd like to decline to do it in the same PR please 🙂 🙏

2025-02-14 04:38 UTC, shazbert commented
> > Had a quick look over, I would like to make a recommendation to remove `convert.BoolPtr` completely and fix up the other bool pointers relating to config like logger. That way we can just do one version upgrade?
> 
> I considered this overnight. I'm always tempted to accept a challenge like this. However the scope is already quite big, the features are unrelated, removing convert.BoolPtr completely sooner isn't enough to balance out mixing changes together, and more than one version upgrade isn't a problem. I really prefer to keep changes discrete, so that rolling them back is cleaner, reviews are easier/faster.
> 
> I've got the others in my sights as well, they won't be forgotten.
> 
> So, I'd like to decline to do it in the same PR please 🙂 🙏

Yeah that is fair, will review in depth once I get a chance Thanks.

2025-02-18 22:21 UTC, shazbert requested changes
Good stuff nice clean. Just some minor things I saw.

2025-02-18 22:21 UTC, shazbert commented on exchanges/binance/binance_wrapper.go
> +		ConfigFormat:  &currency.PairFormat{Uppercase: true, Delimiter: currency.UnderscoreDelimiter},
OOS musing: Is there anyway in future to just have one standard config format and do away with storing this for all assets.

2025-02-18 22:21 UTC, shazbert commented on exchanges/exchange.go
>  		for i := range a {
Could combine these

2025-02-18 22:21 UTC, shazbert commented on exchanges/exchange.go
>  	if a.String() == "" {
suggestion: !a.IsValid()

2025-02-21 00:43 UTC, gbjk commented on docs/ADD_NEW_EXCHANGE.md
>  		RequestFormat: &currency.PairFormat{
Fixed https://github.com/gbjk/gocryptotrader/commit/6e5187e545

2025-02-21 00:45 UTC, gbjk commented on engine/order_manager.go
> -			cfg.FuturesTrackingSeekDuration *= -1
That's not possible; Downgrade implies going back to "not these changes" 🙂 ◀️ ⏰

2025-02-21 00:50 UTC, gbjk commented on exchanges/binance/binance_wrapper.go
> +		ConfigFormat:  &currency.PairFormat{Uppercase: true, Delimiter: currency.UnderscoreDelimiter},
Yes, that's in our plans; Config formats don't need to be configurable.

2025-02-21 00:52 UTC, gbjk commented on exchanges/exchange.go
>  		for i := range a {
Fixed https://github.com/gbjk/gocryptotrader/commit/52d9f6c19d

2025-02-21 00:53 UTC, gbjk commented on exchanges/exchange.go
>  	if a.String() == "" {
Fixed https://github.com/gbjk/gocryptotrader/commit/01a5ea7df6

2025-02-21 00:54 UTC, gbjk commented
@shazbert When you're done again I'll rebase squash and filter-branch to move v3 to a new name.

2025-02-21 01:13 UTC, shazbert approved these changes
Nothing more from me! Thanks sir!

2025-02-23 22:27 UTC, shazbert requested changes
Tests need to be fixed then looks good to go, good stuff!

2025-02-24 06:39 UTC, gbjk commented
> Tests need to be fixed then looks good to go, good stuff!

Yep, sorry, wasn't actually done and got distracted.
Needed to add reconstructing or something for a day while I sniffed sonic.

Anyway; Done, rebased again so we don't fail sonic on arm, and pushed.

2025-02-25 01:48 UTC, gbjk commented
> One linter issue remaining then tACK. Thanks!

Fixed https://github.com/gbjk/gocryptotrader/commit/36178bb6a0

Rebased down immediately

2025-02-25 01:54 UTC, shazbert approved these changes
Nothing more from me thank you!

2025-03-17 01:58 UTC, gloriousCode approved these changes
Nice work, tACK! May have to relook after rebase post-v4, but happy with how you've handled it all

2025-03-17 01:58 UTC, gloriousCode commented on config/versions/versions.go
>  	errNoVersions          = errors.New("error retrieving latest config version: No config versions are registered")
Part of me dislikes that this _lying_ output that I upgraded v4 when `v4.go` does not exist. But it is a requiresDependency PR and as such, any config version upgrade requires a review to merge and so it is on them
```
go run . upgrade --edit
GoCryptoTrader: config-helper tool
2025/03/17 12:06:40 Running upgrade to config version 4
2025/03/17 12:06:40 Running upgrade to config version 5
```
You could check if one `cPatch, ok := patch.(ConfigVersion); ok `/ `ePatch, ok := patch.(ExchangeVersion); ok` passes before printing, but I think its being a bit much for me grumbling

2025-03-17 23:39 UTC, thrasher- requested changes
Nice! Just some minor nits

2025-03-17 23:39 UTC, thrasher- commented on engine/order_manager.go
> +					sd = time.Now().Add(0 - m.futuresPositionSeekDuration)
```suggestion
					sd = time.Now().Add(-m.futuresPositionSeekDuration)
```

2025-03-17 23:39 UTC, thrasher- commented on config/versions/v5.go
> +type Version5 struct {
```suggestion
type Version5 struct {}
```

This will trigger gofumpt for when you rebase

2025-03-17 23:39 UTC, thrasher- commented on config/versions/v5_test.go
> +	assert.Equal(t, expReversed, string(out), "Downgrade should leave an already negative futuresTrackingSeekDuration alone")
```suggestion
	assert.Equal(t, expReversed, string(out), "DowngradeConfig should leave an already negative futuresTrackingSeekDuration alone")
```

2025-03-17 23:39 UTC, thrasher- commented on config/versions/v5_test.go
> +	assert.Equal(t, expReversed, string(out), "Downgrade should just reverse the futuresTrackingSeekDuration")
```suggestion
	assert.Equal(t, expReversed, string(out), "DowngradeConfig should just reverse the futuresTrackingSeekDuration")
```

2025-03-17 23:39 UTC, thrasher- commented on config/versions/v5.go
> +		if e, err = jsonparser.Set(e, []byte(strconv.Itoa(0-int(i))), "orderManager", "futuresTrackingSeekDuration"); err != nil {
```suggestion
		if e, err = jsonparser.Set(e, []byte(strconv.FormatInt(-i, 10)), "orderManager", "futuresTrackingSeekDuration"); err != nil {
```

2025-03-17 23:39 UTC, thrasher- commented on config/versions/v5.go
> +		if e, err = jsonparser.Set(e, []byte(strconv.Itoa(0-int(i))), "orderManager", "futuresTrackingSeekDuration"); err != nil {
```suggestion
		if e, err = jsonparser.Set(e, []byte(strconv.FormatInt(-i, 10)), "orderManager", "futuresTrackingSeekDuration"); err != nil {
```

2025-03-17 23:39 UTC, thrasher- commented on config/versions/v5_test.go
> +	rOHLT    = `"respectOrderHistoryLimits":true,`
```suggestion
```
This is unused

2025-03-17 23:39 UTC, thrasher- commented on config/versions/v5_test.go
> +	rOHLN    = `"respectOrderHistoryLimits":null,`
```suggestion
```

Same for this

2025-03-19 01:36 UTC, gbjk commented on config/versions/versions.go
>  	errNoVersions          = errors.New("error retrieving latest config version: No config versions are registered")
Fixed https://github.com/gbjk/gocryptotrader/commit/b63781f

2025-03-19 01:59 UTC, gbjk commented on engine/order_manager.go
> +					sd = time.Now().Add(0 - m.futuresPositionSeekDuration)
Fixed https://github.com/gbjk/gocryptotrader/commit/4999a5635c

2025-03-19 02:03 UTC, gbjk commented on config/versions/v5_test.go
> +	assert.Equal(t, expReversed, string(out), "Downgrade should leave an already negative futuresTrackingSeekDuration alone")
Fixed https://github.com/gbjk/gocryptotrader/commit/db1b7ed5df

2025-03-19 02:03 UTC, gbjk commented on config/versions/v5_test.go
> +	assert.Equal(t, expReversed, string(out), "Downgrade should just reverse the futuresTrackingSeekDuration")
Fixed https://github.com/gbjk/gocryptotrader/commit/db1b7ed5df

2025-03-19 02:06 UTC, gbjk commented on config/versions/v5.go
> +		if e, err = jsonparser.Set(e, []byte(strconv.Itoa(0-int(i))), "orderManager", "futuresTrackingSeekDuration"); err != nil {
Fixed https://github.com/gbjk/gocryptotrader/commit/aa97a2d433

2025-03-19 02:26 UTC, gbjk commented on config/versions/v5_test.go
> +	rOHLT    = `"respectOrderHistoryLimits":true,`
Fixed https://github.com/gbjk/gocryptotrader/commit/9379a9df06

2025-03-19 02:26 UTC, gbjk commented on config/versions/v5_test.go
> +	rOHLN    = `"respectOrderHistoryLimits":null,`
Fixed https://github.com/gbjk/gocryptotrader/commit/9379a9df06

2025-03-19 02:30 UTC, gbjk commented
🔁 Rebased and 🔂 Squashed

2025-03-19 03:19 UTC, gbjk commented on config/versions/v5.go
> +		if e, err = jsonparser.Set(e, []byte(strconv.Itoa(0-int(i))), "orderManager", "futuresTrackingSeekDuration"); err != nil {
Fixed https://github.com/gbjk/gocryptotrader/commit/b67714be1f

2025-03-19 03:30 UTC, thrasher- approved these changes
Thanks for making those changes!

2025-03-19 03:46 UTC, gloriousCode commented on config/versions/versions.go
>  	errNoVersions          = errors.New("error retrieving latest config version: No config versions are registered")
It looked resolved, thanks! However, the check fails:
<img width="663" alt="image" src="https://github.com/user-attachments/assets/951767a7-f3f8-4004-9e47-0841d0085281" />
This appears to be the can't have nil for interface trap you've always tried to warn us about

2025-03-19 03:52 UTC, gloriousCode approved these changes
tACK!

2025-03-19 03:52 UTC, thrasher- requested changes
Actually, I rescind my approval: https://github.com/thrasher-corp/gocryptotrader/actions/runs/13938123394/job/39009875447?pr=1737#step:11:3599 👀

2025-03-19 04:18 UTC, gbjk commented
> Actually, I rescind my approval: https://github.com/thrasher-corp/gocryptotrader/actions/runs/13938123394/job/39009875447?pr=1737#step:11:3599 👀

Fixed https://github.com/gbjk/gocryptotrader/commit/b053c7ce25

2025-03-19 04:41 UTC, thrasher- approved these changes

2025-03-19 05:11 UTC, merged