bybit: Add protected sub type for account checking to reduce outbound requests
thrasher-corp/gocryptotrader pull request #1739
Opened 2024-12-06 20:52 UTC by shazbert

Fixes # (issue)

* Extra outbound call when updating accounts after first

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration and
also consider improving test coverage whilst working on a certain feature or package.

- [ ] go test ./... -race
- [ ] golangci-lint run
- [ ] Test X

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally and on Github Actions with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-12-11 01:13 UTC, gloriousCode requested changes
🌈

2024-12-11 01:13 UTC, gloriousCode commented on exchanges/bybit/bybit.go
> +func (by *Bybit) RequiresUnifiedAccount(ctx context.Context) error {
```suggestion
// RequiresUnifiedAccount checks account type and returns error if not unified
func (by *Bybit) RequiresUnifiedAccount(ctx context.Context) error {
```

2024-12-11 01:13 UTC, gloriousCode commented on exchanges/bybit/bybit_test.go
>  	}
Please update bybit_live_test.go

2024-12-11 01:13 UTC, gloriousCode commented on exchanges/bybit/bybit_types.go
> +type AccountTypeHolder struct {
Any need for the holder to be exported given no pointer funcs and no accessible properties?

2024-12-12 00:58 UTC, gloriousCode approved these changes
tACK!

2025-01-07 01:03 UTC, thrasher- approved these changes
Nice efficiency improvement!

2025-01-07 01:03 UTC, merged