BUGFIX: PSQL Migration syntax fix
thrasher-corp/gocryptotrader pull request #550
Opened 2020-09-09 03:07 UTC by gloriousCode

# PR Description
There was an issue migrating down using psql:
```
ERROR postgres.sql: failed to run SQL migration: failed to execute SQL query "ALTER TABLE withdrawal_history ALTER COLUMN exchange_name_id SET NULL;\n": pq: syntax error at or near "NULL"
```

Fixes a typo on migrations and also updates to use PSQL syntax

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## How has this been tested
`.\dbmigrate.exe -command=up`
`.\dbmigrate.exe -command=down`
Until it worked

2020-09-09 03:14 UTC, xtda approved these changes

2020-09-09 04:02 UTC, thrasher- approved these changes
tACK

On master:

`ERROR postgres.sql: failed to run SQL migration: failed to execute SQL query "ALTER TABLE candle ALTER COLUMN aseet SET NULL;\n": pq: syntax error at or near "NULL"`

PR:
`Connected to: localhost
2020/09/09 14:01:20 OK    20200814113829_update_withdrawal_history_add_not_null_to_exchange_name_id\postgres.sql`

2020-09-10 00:01 UTC, shazbert requested changes
Tested Approved. Nice work!
Goosed it all the way down and all the way up, no issues.... no tissues needed.

2020-09-10 00:02 UTC, shazbert approved these changes

2020-09-10 00:36 UTC, MadCozBadd approved these changes
tACKKKK

2020-09-10 00:51 UTC, merged