Binance websocket orderbook sync fix
thrasher-corp/gocryptotrader pull request #619
Opened 2021-01-11 21:49 UTC by vazha

# PR Description

As I wrote in Slack - PR #570 does not fixed issues with Binance websocket orderbook syncronisattion.
I came to the conclusion that the reason is that the subscription to the order book by websockets occurs after the getting snapshot of the orderbook received by the REST API. I mean The LastUpdateID (of smapshot) is less than the FirstUpdateID of the websocket updates. Thus, some of the updates are lost, which leads to freezing of prices in the order book.
I have moved part of code to different goroutine, to let websocket subscripton starts earlyer. I have tested this solution many times and it works fine.

Fixes # (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How has this been tested

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

2021-01-11 23:28 UTC, gloriousCode approved these changes
Thanks for this PR @vazha, This is an improvement given that we could only subscribe to websocket orderbook updates once all REST requests were done, which could be awhile one has many currencies enabled. I went back and tested and was able to get out of sync orderbooks and I have not since using your fix.

2021-01-12 05:58 UTC, thrasher- requested changes
Thanks for this PR! Only have a basic nit due to the ambiguity of having no exchange name associated with the error message when multiple exchanges are enabled

2021-01-12 05:58 UTC, thrasher- commented on exchanges/binance/binance_websocket.go
> +			log.Errorf(log.ExchangeSys, "orderBookProcess, SeedLocalCache error: %s", err)
```suggestion
		log.Errorf(log.ExchangeSys, "%s orderBookProcess, SeedLocalCache error: %s", b.Name, err)
```

2021-01-12 21:32 UTC, gloriousCode approved these changes
Thanks for making those changes!

2021-01-12 23:52 UTC, MadCozBadd approved these changes
tACK!!!!!

2021-01-12 23:55 UTC, thrasher- requested changes

2021-01-12 23:55 UTC, thrasher- commented on exchanges/binance/binance_websocket.go
> +		log.Errorf(log.ExchangeSys, "orderBookProcess, GetEnabledPairs error: %s", err)
Just missing one more b.Name here and then this is good to merge!

2021-01-13 19:37 UTC, MadCozBadd approved these changes

2021-01-13 22:05 UTC, gloriousCode approved these changes

2021-01-13 23:49 UTC, thrasher- approved these changes
Thanks @vazha !

2021-01-13 23:49 UTC, merged