Improvement: Binance Futures rate limits
thrasher-corp/gocryptotrader pull request #635
Opened 2021-02-25 00:18 UTC by gloriousCode

# PR Description
Adds rate limits for Binance futures endpoints.

## Type of change
- [x] New feature (non-breaking change which adds functionality)

## How has this been tested

- [x] go test ./... -race
- [x] golangci-lint run

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally and on Travis with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2021-02-26 00:39 UTC, shazbert requested changes
All spot pairs enabled on REST fetching:
[DEBUG]|ORDER| 26/02/2021 11:33:35 |Order manager: Processing orders for exchange Binance. - deadline would be exceeded by retry, status: 429 Too Many Requests

Out of Scope Issues: 
|TICKER| 26/02/2021 11:33:25 |Failed to get REST ticker. Error: no tickers associated with base currency DASH - There might be an issue with loading tickers in the ticker package?
[ERROR]|LOG| 26/02/2021 11:32:42 |Binance failed to get cryptocurrency deposit addresses. Err: -1021=Timestamp for this request is outside of the recvWindow.

2021-02-26 00:39 UTC, shazbert commented on exchanges/binance/binance_cfutures.go
>  // GetFuturesLiquidationOrders gets orderbook ticker for symbol
returns forced liquidations not orderbook

2021-03-02 23:53 UTC, shazbert requested changes
Actual in scope nit. Everything else seems to be working correctly.

2021-03-02 23:53 UTC, shazbert commented on exchanges/binance/ratelimit.go
> +	case uFuturesPairOrdersRate,
For some reason from our order manager calling (*Binance).UAllAccountOpenOrders we are getting a 429 error. I cannot seem to find the reason why the weighting seems correct. This is the only issue I have encountered between USDT and COIN futures with all currency pairs enabled. Spot disabled.

2021-03-03 00:27 UTC, MadCozBadd reviewed
Just 2 small oopsies, otherwise a great pr!

2021-03-03 00:27 UTC, MadCozBadd commented on exchanges/binance/ratelimit.go
> +	cFuturesOrderbook1000Rate
These have not been used

2021-03-03 00:27 UTC, MadCozBadd commented on exchanges/binance/ratelimit.go
> +	cFuturesDefaultRate
This hasn't been used either so it defaults to the spot rate instead

2021-03-03 23:44 UTC, gloriousCode commented
> Binance failed to get cryptocurrency deposit addresses. Err: -1021=Timestamp for this request is outside of the recvWindow.

I've added a larger `recvWindow` on retrieving deposit address.
For you other notes, I can enable all currencies and not experience 429s now

2021-03-04 02:29 UTC, MadCozBadd approved these changes
tested and works well!!!!!

2021-03-04 02:53 UTC, shazbert approved these changes
tACK! Thanks for addressing nits!

2021-03-04 03:57 UTC, thrasher- approved these changes
tACK, 2x ticker/orderbook sync runs with 2660 pairs and asset types enabled. Was not given a 418 / 429 error. Thanks for going through the tedious effort to add in rate limit for all API endpoints (spot/margin/futures)!

2021-03-04 03:58 UTC, merged