FTX: Add REST subaccount support
thrasher-corp/gocryptotrader pull request #653
Opened 2021-03-26 04:56 UTC by thrasher-

# PR Description

Adds REST API subaccount support. NOTE: There's currently a duplication issue for portfolio info introduced in https://github.com/thrasher-corp/gocryptotrader/pull/530. Will be addressing this in a separate PR.

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How has this been tested

- [x] go test ./... -race
- [x] golangci-lint run

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally and on Travis with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2021-03-28 21:43 UTC, gloriousCode requested changes
Not a fan of FTX telling me I'm  `"special":false` 👀 
But tested everything and it works, good stuff! Just some minor niterinos

2021-03-28 21:43 UTC, gloriousCode commented on exchanges/ftx/ftx_test.go
> +	}
Could you please add a successful scenario here?
```
_, err = f.CreateSubaccount("subzero")
	if err != nil {
		t.Fatal(err)
	}
	_, err = f.SubaccountBalances("subzero")
	if err != nil {
		t.Error(err)
	}
	if err := f.DeleteSubaccountName("subzero"); err != nil {
		t.Error(err)
	}
```

2021-03-28 21:43 UTC, gloriousCode commented on exchanges/ftx/ftx.go
> +func (f *FTX) DeleteSubaccountName(name string) error {
`DeleteSubAccountByName` or `DeleteSubAccount`? Since its actually deleting the account and not the name

2021-03-28 22:42 UTC, gloriousCode approved these changes
Thanks for making those changes! tACK!

2021-03-28 22:47 UTC, MadCozBadd reviewed
Just two little things. Everything else is perfect!

2021-03-28 22:47 UTC, MadCozBadd commented on exchanges/ftx/ftx_test.go
> +			t.Errorf("expected %s, but receieved: %s", tt[x].ErrExpected, err)
receieved -> received :D

2021-03-28 22:47 UTC, MadCozBadd commented on exchanges/ftx/ftx_types.go
> +	USDValue               float64 `json:"usdValue"`
Can't seem to find the 'usdValue' field in their api docs anymore. Maybe they mightve removed it

2021-03-28 22:52 UTC, MadCozBadd reviewed
Also one more thing since you have removed all the receieved spelling errors from other files too, could you remove the spelling mistake from currency/storage_types.go ln 49 please.

2021-03-28 23:27 UTC, shazbert requested changes
pedantic nit 😆 all I could find. Everything else is good and tested.

2021-03-29 03:58 UTC, gloriousCode reviewed
In the interest in squashing all the receivieiveieveds in our codebase, [ZB has also fixed their API typo](https://www.zb.com/api#suxpnkgwxunfwnv). Fix would be under `zb.go` line 439 😄 

I re-approve of existing changes though 🤙

2021-03-29 04:19 UTC, MadCozBadd approved these changes
tACK!!!!!!!

2021-03-29 05:01 UTC, shazbert approved these changes
tACK!

2021-03-29 05:05 UTC, gloriousCode approved these changes
Thanks for fixing ZB too :D retack

2021-03-29 05:06 UTC, merged