fixed typo in ftx_types
thrasher-corp/gocryptotrader pull request #694
Opened 2021-06-13 04:20 UTC by tk42

# PR Description

I found some typo in ftx_types.go. Those changes enable fetching some fields in private data again. These kind of method is generally supposed not to be tested by CI.

Correct name of fields are here
https://docs.ftx.com/

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested

These fields referred via private methods have to be manually tested, I suppose. To test the fields, I made some order on the web and rewrote my local ```ftx_test.go``` as follows set with my private key;

<img width="1278" alt="Screen Shot 2021-06-13 at 12 35 56" src="https://user-images.githubusercontent.com/8386849/121795106-71916e00-cc48-11eb-9aa9-aa328f58adf1.png">
<img width="412" alt="Screen Shot 2021-06-13 at 12 53 07" src="https://user-images.githubusercontent.com/8386849/121795110-73f3c800-cc48-11eb-9d8d-5ed8235443c2.png">

- [ ] go test ./... -race
- [ ] golangci-lint run
- [ ] Test X

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally and on Github Actions/AppVeyor with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2021-06-14 23:33 UTC, thrasher- requested changes
Thanks for the PR @tk42! Only have one change and then this looks good to go.

2021-06-14 23:33 UTC, thrasher- commented on exchanges/ftx/ftx_types.go
> +	UnrealizedPnL                float64 `json:"unrealizedPnL"`
Whilst you're at it, could you please add the "estimatedLiquidationPrice" and "collateralUsed" missing fields

2021-06-16 01:14 UTC, gloriousCode approved these changes
Thank you for your contribution tk42 and thank you for fixing those typos 😄

2021-06-16 01:33 UTC, shazbert requested changes
Thanks for opening this PR and fixing the issues!

2021-06-16 01:33 UTC, shazbert commented on exchanges/ftx/ftx_types.go
> +	CreatedSize   float64   `json:"createdSize"`
Out of scope: But if you can, Just noticed this ID should of type int64 and in the RequestTokenCreationData type below.

2021-06-17 04:27 UTC, tk42 commented
I confirmed the added fields as follows
<img width="764" alt="Screen Shot 2021-06-17 at 13 26 25" src="https://user-images.githubusercontent.com/8386849/122331429-c518fa00-cf6f-11eb-8d65-7cca31ca3e1a.png">


```
2021/06/17 13:13:39 EstimatedLiquidationPrice: 41501.473484257906
2021/06/17 13:13:40 CollateralUsed: 1947.844765
```

2021-06-17 04:29 UTC, thrasher- approved these changes
Thanks @tk42!

2021-06-17 04:47 UTC, gloriousCode approved these changes
Thanks for making those changes!

2021-06-17 05:24 UTC, shazbert approved these changes
Changes ACK! Thank you!

2021-06-17 05:29 UTC, merged