Account: Updates for rebalancing across accounts
thrasher-corp/gocryptotrader pull request #696
Opened 2021-06-17 07:11 UTC by shazbert

# PR Description

Add in account management synchronization agent to rebalance full account spectrum across enabled exchanges with supplied credentials and add in subsystem/strategy POC claim on balance ability so more than one strategy can be acting on the same currency pair for an exchange.

ALSO:
Adjust pair manager function 'GetAssetTypes' to take in a param to return either enabled or available assets. Reducing the need to check on every iteration if the asset is enabled.
Adjust param signature for mux publish to add variadic functionality and making it look gorgeous. 
Removed validating credentials on a wrapper level, just did it once on startup. **There is something in BTCMarkets I am looking at that's why there is some commented code**

**This is opened as a draft for initial feedback, I have removed some extra updates pertaining to withdrawals (Will be adding in a claim and wait for feature for pending updates on withdrawals and deposits between exchanges in a different PR) and portfolio because that was looking like it was going to be very hard to test and this is already impacting quite a few systems. **

Websocket implementation of updating of accounts can be added. 
This still needs to be tied in with the backtesting system, once I have done that I will slap a review-me on this. 

Fixes # (issue)

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration and
also consider improving test coverage whilst working on a certain feature or package.

- [ ] go test ./... -race
- [ ] golangci-lint run
- [ ] Test X

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally and on Github Actions/AppVeyor with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-06-24 00:09 UTC, gloriousCode requested changes
I've tried to limit nits on things like comments and tests as this is a draft. I'm interested to see how this continues but I've got a number of questions for you.

2021-06-24 00:29 UTC, shazbert commented on engine/engine.go
> +			return err
This is not a credentials issue this is an account loading issue. We should be getting an account here regardless due to pre-loading a main account or loading in a set of exchange-defined accounts at the setup(exchange.Config) level. But I see your point I will log an error and set everything to false.

2021-06-24 00:40 UTC, shazbert commented on engine/order_manager.go
> +	err = claim.ReleaseToPending()
Send, move ? 🤷

2021-06-24 00:40 UTC, shazbert commented on engine/order_manager.go
> +	err = claim.ReleaseToPending()
Maybe pending name can be changed as well, let me know.

2021-06-24 00:52 UTC, shazbert commented on engine/portfolio_manager.go
> +						if bal.Total <= 0 {
Yeah, I see your point. Will add.

2021-06-24 01:12 UTC, shazbert commented on exchanges/account/claim.go
> +	ident
Yeah I will remove it, I only added it if I needed to quickly add an internal struct without needed to rewrite the fields.

2021-06-24 01:30 UTC, shazbert commented on exchanges/account/claim.go
> +	t time.Time
Yeah, this is just POC, that functionality should definitely be included in the future. Right now, my goal is just simple segregation in this context, if it failed it will alert the caller of the fact then we can log the issue. We really need to test the meshed interaction with some external strategies to really build this out as a library. Maybe we can both go over what you want and what I want for the next stage of the upgrade.

2021-06-24 04:42 UTC, shazbert commented on exchanges/gateio/gateio_wrapper.go
> +		lockedBalances, _ := balance.Locked.(map[string]interface{})
Funnyness with endpoint: ```{"result":"true","available":[]}```
When data comes through it had allegedly has a map string interface type{} but I don't have any funds on the site so I can't verify.

2021-06-24 04:50 UTC, shazbert commented on exchanges/order/orders.go
> +	relationalAmount := s.Amount
wdym sir I am confused; sorry 😢 .

2021-06-24 04:54 UTC, shazbert commented on exchanges/order/orders.go
> +		deployable := amount / s.Price
I don't see anything wrong with dividing by zero? 🤷  😆  🦅

2021-06-24 04:56 UTC, gloriousCode commented on exchanges/order/orders.go
> +	relationalAmount := s.Amount
It actually doesn't make sense, its no wonder you're confused. I will resolve this in shame

2021-11-08 01:29 UTC, shazbert commented
Closed for now; will reopen when actively developed.

2021-11-08 01:29 UTC, closed without merging