engine: Set full state on settings struct.
thrasher-corp/gocryptotrader pull request #697
Opened 2021-06-22 02:59 UTC by shazbert

# PR Description

Just noticed a potential slight improvement in the engine. Let me know what you guys think or if there are any problems with this.

Fixes # (issue)

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration and
also consider improving test coverage whilst working on a certain feature or package.

- [ ] go test ./... -race
- [ ] golangci-lint run
- [ ] Test X

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally and on Github Actions/AppVeyor with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-06-22 05:31 UTC, gloriousCode approved these changes
tACK!

I've compared the two structs before and after to ensure no unintended settings are being messed with, and it all checks out.

_HOWEVER_, your PR has highlighted that we were never setting the following fields:
```
	EnableCurrencyConverter bool
	EnableCurrencyLayer     bool
	EnableFixer             bool
	EnableOpenExchangeRates bool
	EnableExchangeRateHost  bool
```

To demonstrate, you can run the following command on your branch and master branch.
`go run . --openexchangerates=true`

On master branch GCT output:
` Enable OpenExchangeRates: false`
Now on your branch GCT output:
`Enable OpenExchangeRates: true`

So thank you for fixing additional bugs, even if you didn't mean to 😄

2021-06-22 05:31 UTC, gloriousCode commented on engine/engine.go
> +	// Set full state from command line
I don't think this comment is needed

2021-06-22 05:36 UTC, thrasher- approved these changes
Nice simplification, tACK once Scott's comment nit is addressed 👍

2021-06-22 05:38 UTC, shazbert commented on engine/engine.go
> +	// Set full state from command line
done!

2021-06-22 05:39 UTC, MadCozBadd approved these changes
tACK!

2021-06-22 05:39 UTC, gloriousCode approved these changes
Thanks for making that change 
# 🎉

2021-06-22 05:44 UTC, gloriousCode commented on engine/engine.go
>  		if b.Settings.EventManagerDelay != time.Duration(0) && s.EventManagerDelay > 0 {
This makes a little less sense now actually. b.Settings is s now.

2021-06-22 05:48 UTC, gloriousCode requested changes
See my latest comment about the if statements. Its mostly harmless, but its a little weird logic to follow along with to set a value to itself

2021-06-22 21:56 UTC, gloriousCode requested changes
Thanks for making that change! One more!

2021-06-22 21:56 UTC, gloriousCode commented on engine/engine.go
>  	if flagSet["grpc"] {
Invert this `if` please.

2021-06-22 22:16 UTC, shazbert commented on engine/engine.go
>  	if flagSet["grpc"] {
🤭 okay

2021-06-22 23:53 UTC, gloriousCode approved these changes
tACK! Thank you for making that change!

2021-06-23 00:37 UTC, MadCozBadd approved these changes
Awesome stuff! New changes tested and approved!

2021-06-23 00:43 UTC, thrasher- approved these changes

2021-06-23 00:44 UTC, merged