gctcli: bump version
thrasher-corp/gocryptotrader pull request #698
Opened 2021-06-22 03:40 UTC by shazbert

# PR Description

Had a stale branch I found locally, opened if we want to merge. Seems like we were already ref: v2. 🤷 

Fixes # (issue)

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration and
also consider improving test coverage whilst working on a certain feature or package.

- [ ] go test ./... -race
- [ ] golangci-lint run
- [ ] Test X

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally and on Github Actions/AppVeyor with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-06-22 05:45 UTC, thrasher- requested changes
Just 1 nit plus addidtional request:

Could you please also add in the latest autocomplete templates as per https://github.com/urfave/cli/tree/v2.3.0/autocomplete since they contain some bug fixes

2021-06-22 05:45 UTC, thrasher- commented on cmd/gctcli/commands.go
>  			Name:        "start, s",
These will need to be adjusted as per https://github.com/urfave/cli/blob/master/docs/migrate-v1-to-v2.md#flag-aliases-are-done-differently

2021-06-23 00:03 UTC, gloriousCode reviewed
I can confirm that it all works, including aliases:
```
.\gctcli.exe trade getrecent -e=binance -pair=ETH-BTC -a=spot
{
 "exchange_name": "binance",
 "asset": "spot",
 "pair": {
  "delimiter": "-",
  "base": "ETH",
  "quote": "BTC"
 },
 "trades": [
  {
   "price": 0.057707,
   "amount": 1.6,
   "timestamp": "2021-06-22 23:56:37 UTC",
   "trade_id": "278791697"
  },
...
```

I'll check out the autocomplete once complete

2021-06-24 01:44 UTC, gloriousCode approved these changes
tACK!
![image](https://user-images.githubusercontent.com/9261323/123189450-306b4a80-d4e1-11eb-97f3-3f627441bfc8.png)
![image](https://user-images.githubusercontent.com/9261323/123189490-3d883980-d4e1-11eb-977b-358bfbec38e4.png)
![image](https://user-images.githubusercontent.com/9261323/123189524-4d078280-d4e1-11eb-9169-e6b41ae89286.png)

2021-06-24 02:15 UTC, MadCozBadd approved these changes
Tested and Approved! Nice changes

2021-06-24 05:01 UTC, thrasher- approved these changes
Thank you for addressing the nits!

2021-06-24 05:02 UTC, merged