BUGFIX: GateIO candle retrieval, backtester formatting
thrasher-corp/gocryptotrader pull request #715
Opened 2021-07-16 01:49 UTC by gloriousCode

# PR Description
A Slack user name Dave highlighted that there was an issue with the backtester regarding GateIO data retreival. I found the following issues:

- GateIO was unable to retrieve candle data if the end date wasn't the current date due to the API not having start/end support and so we were providing the wrong time. The backtester would yell MISSING DATA
- The backtester was having issues with GateIO and currency lookups due to formatting differences between default and request format, so I format currencies in the backtester to match their request format.
- I noticed that CaPiTaLiSaTiOn was impacting backtester settings lookup for exchanges such as "OKCOIN International", so its now loaded lowercase

## Something to consider
GateIO's API [has been updated to v4 which has better candle retrieval support](https://api.gateio.io/docs/apiv4/en/index.html#retrieve-market-trades). The v2 API [does not have start and end support and is limited to 1001 results](https://www.gate.io/api2#kline). So you cannot get 2019 candle data for 1m intervals as an example. This PR is a small fix, but a move to v4 will be good later 🤙 

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## How has this been tested
- Tested with existing exchanges and the problem exchanges in the backtester to ensure that the backtester still works.
- Tested candle retrieval on GateIO to ensure that data is being retrieved properly
- [x] go test ./... -race
- [x] golangci-lint run

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally and on Github Actions/AppVeyor with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2021-07-16 06:17 UTC, thrasher- requested changes
Only one suggestion, the rest looks good! 

master:

![image](https://user-images.githubusercontent.com/4685270/125901070-972b8723-9bde-4813-b817-d37f4ef56ed9.png)

PR:

![image](https://user-images.githubusercontent.com/4685270/125901114-3dd5e15a-6986-492c-a930-93f25468f571.png)

2021-07-16 06:17 UTC, thrasher- commented on backtester/backtest/backtest.go
> +		if b.CurrencyPairs.RequestFormat != nil {
```suggestion
		pFmt, err := b.GetPairFormat(a, true)
		if err != nil {
			return nil, err
		}
		curr = curr.Format(pFmt.Delimiter, pFmt.Uppercase)
```

2021-07-16 07:06 UTC, shazbert approved these changes
tACK!

2021-07-19 00:45 UTC, thrasher- requested changes

2021-07-19 00:45 UTC, thrasher- commented on backtester/backtest/backtest.go
> +			return nil, fmt.Errorf("could not fotmat currency %v, %w", curr, err)
```suggestion
			return nil, fmt.Errorf("could not format currency %v, %w", curr, err)
```

2021-07-19 01:08 UTC, MadCozBadd approved these changes
Awesome stuff!! Works perfectly! tACK

2021-07-19 01:48 UTC, thrasher- approved these changes
Thanks for fixing those issues! tACK

2021-07-19 01:48 UTC, merged