FTX cancellation improvement
thrasher-corp/gocryptotrader pull request #727
Opened 2021-07-28 13:21 UTC by ydm

# PR Description

This PR fixes an odd desynchronization that may occur if (1) an order is already "managed", (2) order is already canceled and (3) we try to cancel it from the bot side. What it does basically is it now considers a cancellation successful if the exchange returns one of the following two errors:
* `"Order already closed"`
* `"Order already queued for cancellation"`

Fixes # (issue)

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration and
also consider improving test coverage whilst working on a certain feature or package.

- [x] go test ./... -race
- [x] golangci-lint run
- [ ] Test X

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally and on Github Actions/AppVeyor with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2021-07-29 01:01 UTC, shazbert requested changes
Changes look good, I was wondering if it might be good to also add the changes to the method DeleteOrderByClientID as well, let me know what you think.

2021-07-29 01:12 UTC, gloriousCode requested changes
I like this. Just a question though, are you cancelling the orders via FTX front end and then cancelling them via GCT?

2021-07-29 01:12 UTC, gloriousCode commented on exchanges/request/request.go
> +		if p.Result != nil && len(contents) > 0 {
Wouldn't sending a non nil struct and then receiving no contents still be worthy of an error? Seems like the old way captures unexpected results

2021-07-29 07:24 UTC, ydm reviewed
> Changes look good, I was wondering if it might be good to also add the changes to the method DeleteOrderByClientID as well, let me know what you think.

I actually unified all delete methods. Please take a look and let me know if that's fine.

2021-07-29 07:25 UTC, ydm commented
> I like this. Just a question though, are you cancelling the orders via FTX front end and then cancelling them via GCT?

Actually we encountered this and a similar problem while playing around with orders, but canceling orders through the UI is the easiest way to reproduce it, yes.

2021-07-29 23:06 UTC, gloriousCode approved these changes
tACK! Thanks for making those changes!

2021-07-29 23:37 UTC, thrasher- approved these changes
tACK, great stuff @ydm !

2021-07-30 00:00 UTC, shazbert requested changes
Looking good just one request.

2021-07-30 00:00 UTC, shazbert commented on exchanges/ftx/ftx.go
> +func (f *FTX) DeleteOrder(orderID string) (string, error) {
Can we add an empty orderID check to the functions below it gives a vague 404 error if not supplied?

2021-07-30 10:30 UTC, shazbert approved these changes
changes ACK! Thank you very much!

2021-07-31 05:13 UTC, merged