exchanges/ftx: add support for ReduceOnly, ImmediateOrCancel and PostOnly orders
thrasher-corp/gocryptotrader pull request #741
Opened 2021-08-06 16:40 UTC by ydm

These Submit fields were ignored. This PR fixes that.

# PR Description

The following fields of the `order.Submit` structure are now taken into account by `FTX.SubmitOrder`
- ReduceOnly
- ImmediateOrCancel
- PostOnly 

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested

- [x] go test ./... -race
- [x] golangci-lint run
- [x] Test X

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally and on Github Actions/AppVeyor with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2021-08-07 15:16 UTC, ydm commented
Fixed something else in the same branch: ftx.WsFills was never parsed properly.

2021-08-08 17:12 UTC, ydm commented on exchanges/order/order_types.go
> +	AverageExecutedPrice float64
AverageExecutedPrice is the new field added here, the rest of the changes is just whitespace.

2021-08-08 22:51 UTC, gloriousCode requested changes
Nice, thank you for your contribution! Got a few minor things.

2021-08-08 22:51 UTC, gloriousCode commented on exchanges/ftx/ftx.go
> +	//
Please remove line

2021-08-08 22:51 UTC, gloriousCode commented on exchanges/ftx/ftx_websocket_test.go
> +package ftx
Please move over the other websocket tests from ftx_test.go eg `TestParsingWSOBData`

2021-08-08 22:51 UTC, gloriousCode commented on exchanges/ftx/ftx_websocket_test.go
> +	ticker := time.NewTicker(100 * time.Second)
Given the < 2 second execution time for me, I'd much prefer a more reasonable deadline to be defined in the event of a failure. <= 10 second maximum please

2021-08-08 22:54 UTC, gloriousCode commented on exchanges/ftx/ftx_websocket_test.go
> +		f.wsHandleData([]byte(input))
Given access to `t` here, it may be good to handle any error

2021-08-09 23:51 UTC, shazbert requested changes
These are some great improvements. Just some things I noticed in the test.

2021-08-09 23:51 UTC, shazbert commented on exchanges/ftx/ftx_websocket_test.go
> +	case ans = <-f.Websocket.DataHandler:
I think this needs to change f->x

2021-08-09 23:51 UTC, shazbert commented on exchanges/ftx/ftx_websocket_test.go
> +				DataHandler: make(chan interface{}),
we can buffer this and then we don't need to have wsHandleData in a go routine.

2021-08-09 23:51 UTC, shazbert commented on exchanges/ftx/ftx_websocket_test.go
> +	if err != nil {
after changes hug with ```err = x.wsHandleData([]byte(input))```

2021-08-09 23:51 UTC, shazbert commented on exchanges/ftx/ftx_websocket_test.go
> +		//
remove

2021-08-09 23:51 UTC, shazbert commented on exchanges/ftx/ftx_websocket_test.go
> +		//
remove

2021-08-10 23:31 UTC, gloriousCode approved these changes
tACK! Thanks for making those changes @ydm

2021-08-10 23:42 UTC, shazbert approved these changes
Thank you tACK. 🧇

2021-08-11 00:27 UTC, thrasher- approved these changes
Great stuff @ydm !

2021-08-11 00:27 UTC, thrasher- commented on exchanges/ftx/ftx.go
> +		case math.Abs(filledAmount-amount) > 1e-6:
NOTE: The smallest minProvideSize I could find is "minProvideSize":0.00001 so this looks good!

2021-08-11 00:28 UTC, merged