Binance websocket: set commission of order Detail
thrasher-corp/gocryptotrader pull request #750
Opened 2021-08-16 08:39 UTC by yangrq1018

# PR Description

Please include a summary of the change, feature or issue which this pull request addresses. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration and
also consider improving test coverage whilst working on a certain feature or package.

- [ ] go test ./... -race
- [ ] golangci-lint run
- [ ] Test X

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally and on Github Actions/AppVeyor with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-08-16 23:58 UTC, shazbert requested changes
@yangrq1018 Just one minor issue, thanks for opening this PR.

2021-08-16 23:58 UTC, shazbert commented on exchanges/order/order_types.go
> +	CostAsset            string
Can we change this type from string to currency.Code? This is just for differentiation purposes.

2021-08-17 02:32 UTC, gloriousCode requested changes
Thank you for your PR yangrq1018! 🎉 Just one thing from me

2021-08-17 02:32 UTC, gloriousCode commented on exchanges/binance/binance_websocket.go
> +					CostAsset:       currency.NewCode(data.Data.CommissionAsset),
This change has broken `TestWsOrderExecutionReport`. Please check whether `data.Data.CommissionAsset != ""` first before creating the currency code.
Could you please also update the test? The json has `"n":"0", "N": null,`. If you could update it to have values and compare them that would be much appreciated.

2021-08-17 03:46 UTC, gloriousCode approved these changes
tACK! Thanks for quickly making those changes!
# 🎉

2021-08-17 04:09 UTC, shazbert approved these changes
tACK! Thanks.

2021-08-17 04:31 UTC, thrasher- approved these changes
tACK, thanks @yangrq1018 !

2021-08-17 04:33 UTC, merged