Binance spot websocket fixes
thrasher-corp/gocryptotrader pull request #753
Opened 2021-08-17 19:26 UTC by ydm

# PR Description
With c38757a68990858aa989557d2cdfb8be1e7f932f a number of issues were introduced. Some of them are:
1. instead of reading the order status, which is pushes through the websocket, floating point numbers were compared for equality :)
2. there was no average price populated
3. incorrectly fee was assigned to cost
4. "m" was being overridden by "M" 

This PR fixes all of them and, on top of that:
1. orders fields of WsOrderUpdateData the way they are described in the latest version of Binance docs + that's the same order when they come out of the websocket
2. adds and populates order.Detail.FeeAsset
3. sorts out mixed := and var declarations
4. orders temporary variables by the order they are used

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested

- [x] go test ./... -race
- [x] golangci-lint run
- [x] Test X

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally and on Github Actions/AppVeyor with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2021-08-17 19:30 UTC, ydm commented
@yangrq1018 , tagging you since you might be interested in this PR.

2021-08-18 05:40 UTC, shazbert approved these changes
Tested execution front end, approved for Binance and FTX changes.

2021-08-18 06:02 UTC, gloriousCode requested changes
Thank you for the update and fix! Just one minor thing

2021-08-18 07:24 UTC, ydm commented on exchanges/binance/binance_websocket.go
> +				feeAsset := currency.NewCode(data.Data.CommissionAsset)
You're right. Just to make sure I added a check on the wsOrderUpdate handling side.

2021-08-18 07:56 UTC, gloriousCode approved these changes
tACK! Thanks for making those changes!

2021-08-18 08:30 UTC, thrasher- approved these changes
tACK, great work @ydm 👍

2021-08-18 08:31 UTC, merged