gctcli: remove all exchange name client-side validation
thrasher-corp/gocryptotrader pull request #758
Opened 2021-08-18 18:21 UTC by lrascao

Since now exchange names can be user-assigned we can no longer have
client-side validation, all exchange name validation must now occur
on the server (it was already doing that).

- [X] New feature (non-breaking change which adds functionality)

- [X] go test ./... -race
- [X] golangci-lint run

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [X] My changes generate no new warnings
- [X] New and existing unit tests pass locally and on Github Actions/AppVeyor with my changes
- [X] Any dependent changes have been merged and published in downstream modules

2021-08-19 00:24 UTC, shazbert approved these changes
tACK

2021-08-19 00:27 UTC, thrasher- requested changes
Can also rid the errInvalidExchange var as it is no longer needed, then this looks good to go

2021-08-19 01:11 UTC, gloriousCode requested changes
Thanks for this PR! Two minor comments

2021-08-19 01:11 UTC, gloriousCode commented on cmd/gctcli/commands.go
> -	if !validExchange(exchangeName) {
The only concern here is that rpc function `GetTickerStream` will return the error `fmt.Errorf("ticker item not found for %s %s %s",
			exchange,
			p,
			a)`
which is less clear than exchange not found. Would you be willing to add
 ```
exch := bot.GetExchangeByName(r.Exchange)
	if exch == nil {
		return nil, ErrExchangeNotFound
	}
``` 
to `GetExchangeTickerStream`?

2021-08-19 01:11 UTC, gloriousCode commented on cmd/gctcli/commands.go
Same with here. You'll receive a generic error `"exchange does not have a OTP secret stored"` which doesn't say its not loaded

2021-08-22 22:35 UTC, shazbert approved these changes
Changes ACK! Thank you. 

Only slight issues I found, I don't know if you want to improve these outputs?
```
❯ go run ./... getexchangeorderbookstream -exchange="xxx"
2021/08/23 08:27:46 rpc error: code = Unknown desc = cannot find orderbook(s) for xxx exchange

❯ go run ./... gettickerstream -exchange="xxx" -pair="btc-usdt" -asset=spot
2021/08/23 08:29:08 rpc error: code = Unknown desc = ticker item not found for xxx btcusdt spot
```

NOTE: Also maybe in future we can return an error in engine method getExchangeByName(r.Exchange). I may open a separate PR for that.

2021-08-22 23:11 UTC, gloriousCode approved these changes
tACK! Thanks for addressing that server side validation 🎉

2021-08-23 23:09 UTC, gloriousCode approved these changes
ACK changes!

2021-08-23 23:36 UTC, thrasher- approved these changes
Thanks for adding in the additional gRPC checks, tACK

2021-08-23 23:45 UTC, shazbert approved these changes
Changes ACK!

2021-08-23 23:45 UTC, merged