exchange manager documentation and Add() comment
thrasher-corp/gocryptotrader pull request #767
Opened 2021-08-27 02:13 UTC by romanornr

# PR Description

exchange manager documentation and Add() comment
Some extra comments might clear up and help new users trying to understand 

Fixes # (issue)

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration and
also consider improving test coverage whilst working on a certain feature or package.

- [ ] go test ./... -race
- [ ] golangci-lint run
- [ ] Test X

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [x ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally and on Github Actions/AppVeyor with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-08-29 22:42 UTC, shazbert commented on engine/exchange_manager.go
> +// If the exchange is not nil, the Lock function will be called, and when the Unlock function is called, the exchange has been accessed by a remote interface and is no longer nil.
From the logs It looks like you might have made a custom exchange manager instance without instantiating the map.  SetupExchangeManager() func is usually called first, but seeing as you are doing custom code, it's hard to make a determination and help you out.

2021-08-29 23:17 UTC, romanornr commented on engine/exchange_manager.go
> +// If the exchange is not nil, the Lock function will be called, and when the Unlock function is called, the exchange has been accessed by a remote interface and is no longer nil.
I found out a couple hours what I did wrong or missed! 

I had to do it like this within a struct ExchangeManager: *engine.SetupExchangeManager(),

2021-08-31 16:03 UTC, romanornr commented on engine/exchange_manager.go
> +// If the exchange is not nil, the Lock function will be called, and when the Unlock function is called, the exchange has been accessed by a remote interface and is no longer nil.
Added another commit
https://github.com/thrasher-corp/gocryptotrader/pull/767/commits/c0a1a4a0cdb23529c9d8350695f27edde9d0dc39

might review this as well 

Have another commit incoming but might get a little bit messy with 3 commits 
Have to check out how I can add it as a separate pull request

2021-08-31 23:29 UTC, shazbert requested changes
Appreciate the effort you have put into this PR, I do have some questions though. The comments are very verbose (1) and they exceed common line lengths (2). This is just my view though, am happy for more discussion and I understand there are some people that would appreciate this change.

2021-08-31 23:29 UTC, shazbert commented on engine/engine.go
> +				gctlog.Errorf(gctlog.ExchangeSys,
Just curious, what happened here that required this change?

2021-08-31 23:29 UTC, shazbert commented on engine/engine.go
> +// LoadExchange creates an exchange object for the loaded exchange by calling ExchangeManager.NewExchangeByName.
I prefer keeping comments concise, and the actual code be annotated instead.

2021-11-08 01:26 UTC, thrasher- commented
Closed due to inactivity

2021-11-08 01:26 UTC, closed without merging