Account: Add account.Balance.Available() method
thrasher-corp/gocryptotrader pull request #777
Opened 2021-09-07 10:39 UTC by ydm

# PR Description

When working with `account.Balance`s, getting the available amount of an asset is a very common thing to do, so such a method would be helpful.

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested

- [x] go test ./... -race
- [x] golangci-lint run
- [ ] Test X

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally and on Github Actions/AppVeyor with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-09-07 22:34 UTC, shazbert requested changes
Only one pedantic issue. Other than that looks good.

2021-09-07 22:34 UTC, shazbert commented on exchanges/account/account.go
> +func (b Balance) Available() float64 {
Sorry to be a pain but could you add a comment?

2021-09-07 22:37 UTC, gloriousCode approved these changes
tACK!

2021-09-08 03:08 UTC, thrasher- requested changes
Thanks for the PR @ydm and another pedantic comment, please add basic test coverage for this new method 😄

2021-09-08 22:19 UTC, gloriousCode approved these changes
Thank you for the updates! tACK!

2021-09-08 23:32 UTC, thrasher- approved these changes
tACK, thanks @ydm !

2021-09-08 23:33 UTC, shazbert approved these changes
Changes ACK. Thank you!

2021-09-08 23:35 UTC, merged