Backtester: USD tracking
thrasher-corp/gocryptotrader pull request #818
Opened 2021-10-28 22:28 UTC by gloriousCode

![USA USA](https://i.imgur.com/905aLaA.gif)

# PR Description

This PR adds USD tracking data to results, establishing a consistent comparison benchmark across exchanges, assets and backtesting results. You can read about the flag [here](https://github.com/gloriousCode/gocryptotrader/tree/totally-total-tracking/backtester/config#strategy-settings) and how tracking currencies are used [here](https://github.com/gloriousCode/gocryptotrader/tree/totally-total-tracking/backtester/funding/trackingcurrencies)
It removes the external API dependency too from the previous PR too.
The feature is enabled by default and can be disabled in strategy configs. It is not supported in live trading data type.

It allows for ratios and performance metrics to be calculated against the combined USD values as an additional way to measure performance:
![image](https://user-images.githubusercontent.com/9261323/139340988-f2133b52-9c1a-414f-8c1e-5d9f91f93083.png)

This also comes with the following cool changes:
- Removed Backtesting reliance on existing GoCryptoTrader config file
  - In order to ensure that all pairs are available, the Backtester will run `UpdateTradablePairs` for each exchange as it cannot rely on a config
- New chart provider: Highcharts
- New graphs in report HTML
- Ratio calculation on overall USD results, not just a pair's results
- The return of portfolio interface for strategy analysis. Added two new helper functions to assist:
  - `GetLatestOrderSnapshotForEvent` to retrieve orders for an event's exchange, asset and currency pair
  - `GetLatestOrderSnapshots` to return all orders from the latest snapshots

USD Totals charts:
![image](https://user-images.githubusercontent.com/9261323/139338363-4a078855-5432-4307-88bb-7f3c1842b63b.png)
Holdings over time chart:
![image](https://user-images.githubusercontent.com/9261323/139338742-0092d149-2f90-4b77-bab2-2969d002fac5.png)
New chart provider can add analysis (in this case RSI)
![image](https://user-images.githubusercontent.com/9261323/139339348-4a017c3c-c4b7-433f-b105-a971ec5d2e78.png)

### Things to consider
- The way USD tracking is performed is not 100% accurate as it treats the list of USD currencies [listed here](https://github.com/gloriousCode/gocryptotrader/tree/totally-total-tracking/backtester/funding/trackingcurrencies#what-if-the-exchange-does-not-support-usd) as 1:1 even though they all have minor variances. This is mostly to avoid retrieving significant amounts of data and calculating exchange rates for every candle in order to create a total.
  - This is only for USD total comparisons, a strategy for USDT/BUSD for minor fluctuations will not be converted to 1:1

## Type of change
- [x] New feature (non-breaking change which adds functionality)

## How has this been tested
- [x] Test coverage against all new features
- [x] go test ./... -race
- [x] golangci-lint run

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally and on Github Actions/AppVeyor with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2021-11-01 05:23 UTC, shazbert requested changes
Everything looks good and seems to work out! Just tried the default DCA strat only one issue I saw on that:

![image](https://user-images.githubusercontent.com/9391715/139625358-1ef371fd-13cd-48b3-b530-c64f9cfbe651.png)

Including something on the strategy movement with the same characters. 

Nice work only a few minor nits! 🚀

2021-11-01 05:23 UTC, shazbert commented on engine/order_manager.go
> +	log.Debugf(log.OrderMgr, msg)
revert?

2021-11-01 05:23 UTC, shazbert commented on exchanges/kline/kline.go
> +		return 0
add coverage

2021-11-01 05:37 UTC, gloriousCode commented on backtester/backtest/backtest.go
> +			continue
This map is used to ensure we only setup and call `UpdateTradablePairs(...)` once and added to the backtester's exchange manager per exchange. So when it is `ok`, we've loaded that exchange already and ensured we have all pairs loaded, there should be no errs hidden by this 

I could change it to two loops where I create a slice of exchange names, then the second loop runs  `UpdateTradablePairs(...)` which would be more clear

2021-11-01 22:24 UTC, gloriousCode commented on backtester/eventhandlers/exchange/exchange.go
> +	ords, _ := orderManager.GetOrdersSnapshot("")
No error, just a timestamp, but its unused and I'll remove it anyway

2021-11-01 22:26 UTC, gloriousCode commented on backtester/eventhandlers/portfolio/portfolio.go
> +	return latest.TotalValue
Yeah I removed the function

2021-11-01 23:05 UTC, shazbert commented on backtester/backtest/backtest.go
> +			continue
I am happy to keep it how it is, if that's the case.

2021-11-02 00:49 UTC, gloriousCode commented
In that screenshot you posted, its from your browser being unable to render `∞`, so I've updated the output to just say `Infinity%` 😄 Microsoft Edge can render it btw................

2021-11-02 02:27 UTC, shazbert requested changes
Chart dates are off, mentioned in DM.

2021-11-02 05:11 UTC, gloriousCode commented
Totals and holdings charts are now logarithmic per @shazbert's suggestion. Makes reading them a little easier:
![image](https://user-images.githubusercontent.com/9261323/139789997-251cf4bb-3f25-4120-82b6-b2874798c958.png)

![image](https://user-images.githubusercontent.com/9261323/139790021-fd5e5aff-fe0f-4f07-bfa4-3adcb656a81b.png)

2021-11-02 05:22 UTC, shazbert approved these changes
Tested ACK! Well done! 🚀 x 100. Everything is still deterministic which is lovely. 😆

2021-11-05 02:58 UTC, thrasher- requested changes
Awesome feature! First code pass. Now onto functionality testing 🚀

2021-11-05 02:58 UTC, thrasher- commented on backtester/funding/trackingcurrencies/trackingcurrencies_test.go
> +	for i := range tests {
```suggestion
	for i := range tests {
		tt := tests[i]
		t.Run(tt.description, func(t *testing.T) {
			t.Parallel()
			basePair, quotePair, err := findMatchingUSDPairs(tt.initialPair, tt.availablePairs)
			if !errors.Is(err, tt.expectedErr) {
				t.Fatalf("'%v' received '%v' expected '%v'", tt.description, err, tt.expectedErr)
			}
			if basePair != tt.basePair {
				t.Fatalf("'%v' received '%v' expected '%v'", tt.description, basePair, tt.basePair)
			}
			if quotePair != tt.quotePair {
				t.Fatalf("'%v' received '%v' expected '%v'", tt.description, quotePair, tt.quotePair)
			}
		})
	}
```

As individually testing this func does not provide coverage

2021-11-05 02:58 UTC, thrasher- commented on exchanges/kline/kline_test.go
> +		t.Errorf("received '%v' expectec '%v'", err, nil)
```suggestion
		t.Errorf("received '%v' expected '%v'", err, nil)
```
Seems like there's a few instances of these in this file 😄

2021-11-05 02:58 UTC, thrasher- commented on common/convert/convert.go
> +func FloatToCommaSeparatedString(number float64, decimals uint, decPoint, thousandsSep string) string {
This func name is technically incorrect as a user can supply whatever they want for the `thousandsSep` param. I think a better name would be "FloatToHumanFriendlyString" or you can drop the thousandsSep param and make it always a comma as the name suggests

2021-11-05 02:58 UTC, thrasher- commented on backtester/funding/funding.go
> +	ErrUSDTrackingDisabled        = errors.New("usd tracking disabled")
```suggestion
	ErrUSDTrackingDisabled        = errors.New("USD tracking disabled")
```

2021-11-05 04:04 UTC, thrasher- commented
Chart functionality is working great! Tested the default DCA as well as the `top2bottom2` strat

![image](https://user-images.githubusercontent.com/4685270/140456415-2c3f4be4-da3f-44e5-ac48-903dbe77998a.png)

I noticed an issue with some of the menu items on the chart for things like `save chart`:

![image](https://user-images.githubusercontent.com/4685270/140456214-330f5ae3-dc00-4f74-b0b7-de0b3771d610.png)

2021-11-05 04:58 UTC, gloriousCode commented
I've update it to only show working/helpful tools on the GUI:
Holdings charts:
![image](https://user-images.githubusercontent.com/9261323/140460490-150f540a-1867-4876-a7ce-15fc96f2c8da.png)

Candle charts:
![image](https://user-images.githubusercontent.com/9261323/140460044-2b17ad65-b03d-4f28-b46b-593c9101c691.png)

Also can now save charts:
![image](https://user-images.githubusercontent.com/9261323/140460562-a4791a3d-b724-4d83-abdb-9b26b90fe604.png)

2021-11-08 00:28 UTC, shazbert approved these changes
Changes tested ACK. 🚀

2021-11-08 00:48 UTC, thrasher- approved these changes
changes, tACK! Great stuff @gloriousCode

2021-11-08 01:10 UTC, merged