Backtester: Fix dividing by zero when missing data
thrasher-corp/gocryptotrader pull request #841
Opened 2021-11-18 05:04 UTC by gloriousCode

# PR Description

This PR fixes the issue raised by @MeanSquaredError where there would be a zero value being divided. The fix is to use a previous benchmark's data when a price is zero/missing. Its not accurate, but a warning is displayed and it skews data a lot less than calculating with zeroes.

I also noticed a couple of other issues during testing:
- Strategies such as `dca-api-candles-multiple-currencies.strat` would fail due to multiple instances of USDT funding Items and USD tracking candles not being appropriately set
- The initial valuation calculation in Holdings/the output report were _way_ off. The calculation is now based upon the initial closing price

Before:
![image](https://user-images.githubusercontent.com/9261323/142353688-f5212fd0-118f-4514-ae7d-bee67bc35489.png)

After:
![image](https://user-images.githubusercontent.com/9261323/142353963-2d7193a3-2029-4f3d-a550-47e0e68ac98a.png)

Verification that the strategy posted [here](https://github.com/thrasher-corp/gocryptotrader/issues/840) now works:
![image](https://user-images.githubusercontent.com/9261323/142353809-1108b669-1cf5-411e-97e1-814f63bff128.png)

Fixes # (issue)
https://github.com/thrasher-corp/gocryptotrader/issues/840

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How has this been tested
Updated testing
- [x] go test ./... -race
- [x] golangci-lint run

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally and on Github Actions/AppVeyor with my changes

2021-11-18 22:16 UTC, MeanSquaredError commented
I can confirm that this PR fixes #840
Thank you!

2021-11-18 23:00 UTC, shazbert requested changes
tested and looks good! Just one thing that might need to be checked out.

2021-11-18 23:00 UTC, shazbert commented on backtester/eventhandlers/statistics/currencystatistics.go
> +		if c.Events[i].DataEvent.GetClosePrice().IsZero() || c.Events[i-1].DataEvent.GetClosePrice().IsZero() {
This might break at [0-1]

2021-11-18 23:08 UTC, shazbert commented
@MeanSquaredError Thanks for testing!

2021-11-18 23:41 UTC, shazbert approved these changes
tested approved.

2021-11-19 01:59 UTC, thrasher- approved these changes
tACK, supplied strat file causes crash on master whereas works on this PR

![image](https://user-images.githubusercontent.com/4685270/142551783-8fabf357-b8cf-4113-ac98-da45cce84415.png)

2021-11-19 01:59 UTC, merged