ftx: add greek field support for GetFutureStats function
thrasher-corp/gocryptotrader pull request #864
Opened 2021-12-29 00:23 UTC by shazbert

# PR Description

Add additional greek information.

Fixes #863 

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration and
also consider improving test coverage whilst working on a certain feature or package.

- [ ] go test ./... -race
- [ ] golangci-lint run
- [ ] Test X

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally and on Github Actions/AppVeyor with my changes
- [x] Any dependent changes have been merged and published in downstream modules

2021-12-29 01:30 UTC, gloriousCode requested changes
# 🐎 💨 
Speedy!

2021-12-29 01:30 UTC, gloriousCode commented on exchanges/ftx/ftx_test.go
> +	}
I'm not sure this is worth the error. If they add it in future, is it worth updating tests for?

2021-12-29 01:30 UTC, gloriousCode commented on exchanges/ftx/ftx_test.go
> +	f, err := f.GetFutureStats(context.Background(), "BTC-MOVE-2021Q4")
`f` is the name of the FTX varaible, even though this is only a local var, please rn

2021-12-29 02:25 UTC, gloriousCode approved these changes
tACK! Thanks for making those changes

2021-12-31 04:17 UTC, thrasher- approved these changes
![image](https://user-images.githubusercontent.com/4685270/147803018-cc816bdb-7b06-41b9-97de-2c7260c0e68e.png)
tACK!

2021-12-31 04:18 UTC, merged