btcmarkets: update order submission
thrasher-corp/gocryptotrader pull request #908
Opened 2022-03-23 05:03 UTC by shazbert

# PR Description

* Adds formatting methods.
* Change target amount to quote amount to make it a little bit more obvious and add commentary.
* Remove price and post only from json request when not needed. 

Fixes # (issue)

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration and
also consider improving test coverage whilst working on a certain feature or package.

- [ ] go test ./... -race
- [ ] golangci-lint run
- [ ] Test X

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally and on Github Actions/AppVeyor with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-03-23 22:12 UTC, gloriousCode requested changes
Nice! Just some micro nits 🛩️

2022-03-23 22:12 UTC, gloriousCode commented on exchanges/btcmarkets/btcmarkets.go
> +}
Please add coverage  to these two🌟

2022-03-23 22:12 UTC, gloriousCode commented on exchanges/btcmarkets/btcmarkets_test.go
> +	_, err := b.formatOrderType(order.Type("SWOOON"))
Please add `t.Parallel()`

2022-03-24 22:45 UTC, gloriousCode requested changes
Thanks for making those changes! Just one thing

2022-03-24 22:45 UTC, gloriousCode commented on exchanges/btcmarkets/btcmarkets_test.go
> +func TestSubmitOrder(t *testing.T) {
To be a huge jerk, I appreciate this test, however this does remove the test on just the API function. Could you please re-add the test and keep this one?

2022-03-24 23:30 UTC, gloriousCode approved these changes
tACKeroo! Thanks for making those changes

2022-03-25 04:05 UTC, thrasher- approved these changes

2022-03-25 04:05 UTC, merged