currency: Add methods to pairs type.
thrasher-corp/gocryptotrader pull request #909
Opened 2022-03-23 05:47 UTC by shazbert

# PR Description

Adds a method to see if a code is contained in the currency pairs list. `Has()`
Adds a method to construct from a pairs list with a list of currencies. `GetPairsByCurrencies`

Fixes # (issue)

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration and
also consider improving test coverage whilst working on a certain feature or package.

- [ ] go test ./... -race
- [ ] golangci-lint run
- [ ] Test X

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally and on Github Actions/AppVeyor with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-03-23 21:43 UTC, gloriousCode requested changes
🎉 some nice little helpers

2022-03-23 21:43 UTC, gloriousCode commented on currency/pairs.go
> +func (p Pairs) GetPairsByCurrencies(enabled Currencies) Pairs {
`enabled` here bears no meaning, passing in a `Currencies` does not mean that they are enabled. Please rn to a more descriptive variable such as `currencies`

2022-03-23 21:43 UTC, gloriousCode commented on currency/pairs_test.go
> +	available := Pairs{
parallel

2022-03-23 21:43 UTC, gloriousCode commented on currency/pairs_test.go
> +	pairs := Pairs{
parallel

2022-03-23 22:44 UTC, shazbert commented on currency/pairs_test.go
> +	if !enabled.Contains(NewPair(USD, BTC), false) {
It was just a copy-paste situation. I will change to be more specific.

2022-03-23 22:46 UTC, shazbert commented on currency/pairs.go
> +func (p Pairs) Has(check Code) bool {
😭

2022-03-24 22:54 UTC, gloriousCode approved these changes
tACK! Thanks for making those changes

2022-03-24 23:58 UTC, thrasher- approved these changes
utACK 👍

2022-03-24 23:58 UTC, merged