exchange/wrapper: add GetServerTime() for exchange analytics
thrasher-corp/gocryptotrader pull request #938
Opened 2022-05-03 02:31 UTC by shazbert

# PR Description

Add GetServerTime() to exchange interface. 

Fixes/Starts #763 

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration and
also consider improving test coverage whilst working on a certain feature or package.

- [ ] go test ./... -race
- [ ] golangci-lint run
- [ ] Test X

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally and on Github Actions/AppVeyor with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-05-04 02:21 UTC, gloriousCode requested changes
This is one of the things I'm surprised we didn't already have. While I think more exchanges actually have this API feature, I'm fine with only adding the currently supported ones at present.

2022-05-04 02:21 UTC, gloriousCode commented on exchanges/interfaces.go
> +	GetServerTime(ctx context.Context, ai asset.Item) (time.Time, error)
I don't think this doesn't need its own section and commentary, please add to the main chunk of functions.

2022-05-04 02:21 UTC, gloriousCode commented on exchanges/binance/binance_wrapper.go
> +	return time.Time{}, common.ErrNotYetImplemented
Server time is returned with:
Spot:
`GetExchangeInfo(...)`
CoinMarginedFutures:
`FuturesExchangeInfo(...)`

2022-05-04 02:21 UTC, gloriousCode commented on exchanges/btcmarkets/btcmarkets_wrapper.go
> +	}
I don't think this is needed for any that don't distinguish between asset type

2022-05-04 02:21 UTC, gloriousCode commented on exchanges/kraken/kraken_wrapper.go
> +}
Please also include Yobit via `GetInfo(ctx context.Context) (Info, error) {`

2022-05-05 01:06 UTC, gloriousCode requested changes
Thanks for making those changes!

2022-05-05 01:06 UTC, gloriousCode commented on exchanges/coinbasepro/coinbasepro_wrapper.go
> +	}
rm

2022-05-05 01:06 UTC, gloriousCode commented on exchanges/coinbasepro/coinbasepro_test.go
> +	}
rm

2022-05-05 01:06 UTC, gloriousCode commented on exchanges/btse/btse_wrapper.go
> +	}
rm

2022-05-05 01:06 UTC, gloriousCode commented on exchanges/btse/btse_test.go
> +	}
rm

2022-05-05 02:42 UTC, thrasher- requested changes
Please add support for Huobi:

`h.GetTimestamp`

And support wrapper additional testing via exchange_wrapper_issues tool

2022-05-05 22:23 UTC, gloriousCode approved these changes
tA:CK

2022-05-06 01:38 UTC, thrasher- approved these changes
Thanks for making those changes!

2022-05-06 01:39 UTC, merged