orders: change SubmitOrder return type to *order.Detail
thrasher-corp/gocryptotrader pull request #955
Opened 2022-05-17 05:39 UTC by shazbert

# PR Description

* Construct detail from order.Submit struct

Fixes # (issue)

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration and
also consider improving test coverage whilst working on a certain feature or package.

- [ ] go test ./... -race
- [ ] golangci-lint run
- [ ] Test X

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally and on Github Actions/AppVeyor with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-05-18 01:04 UTC, gloriousCode requested changes
I'm not sure about this feature. At face value it seems like an improvement, but I think it comes across incorrectly. 

Many API's do not return full order details from a submit request and if it does, you are not taking in those details in the order.Detail response due to how limited `Derive` is. Some order API responses are even just an order ID or "success". Returning an order.Detail can give a false impression of how the order was handled since its made from an `order.Submit` and not from the exchange's details.

A `SubmitResponse` contains enough information to then get the full order details from the exchange without the impression its the order

Also, please fix your tests and linting

2022-05-27 02:14 UTC, gloriousCode requested changes
Thanks for making those changes! I'm glad the only place in GCT to `DeriveDetail` is with the order manager. The nits are now mostly minor, with exception to the backtester which you _destroyed_ 💥

2022-05-27 02:14 UTC, gloriousCode commented on exchanges/order/orders.go
> +// DeriveDetail will construct an order SubmitResponse when a successful
```suggestion
// DeriveSubmitResponse will construct an order SubmitResponse when a successful
```

2022-05-27 03:16 UTC, shazbert commented on exchanges/btse/btse_wrapper.go
> +	if len(r) > 0 {
Yeah Agreed, I don't have any keys or funds on that exchange to verify.

2022-05-30 00:12 UTC, gloriousCode requested changes
Two tiny nits and I think its all GEE

2022-05-30 00:12 UTC, gloriousCode commented on exchanges/order/order_test.go
> +	statusTests := map[int]struct {
t.Parallel()

2022-05-30 00:12 UTC, gloriousCode commented on exchanges/order/order_test.go
> +		if tt.o.WasOrderPlaced() != tt.expRes {
Parallel()

2022-05-30 02:40 UTC, gloriousCode approved these changes
Thank you for dealing with my requests! tACK!

2022-06-03 05:14 UTC, thrasher- commented on cmd/exchange_template/wrapper_file.tmpl
> -func ({{.Variable}} *{{.CapitalName}}) SubmitOrder(ctx context.Context, s *order.Submit) (order.SubmitResponse, error) {
var submitOrderResponse *order.SubmitResponse

2022-06-06 01:38 UTC, thrasher- commented on exchanges/btse/btse_wrapper.go
> +	if len(r) > 0 {
Can confirm that the current implementation is correct:

```
[{"status":2,"symbol":"BTC-USDT","orderType":76,"price":25000.0,"side":"BUY","size":1.0E-5,"orderID":"cfd6680d-ba2d-49e5-9b07-460f5758ced3","timestamp":1654479079883,"triggerPrice":0.0,"stopPrice":null,"trigger":false,"message":"","averageFillPrice":0.0,"fillSize":0.0,"clOrderID":null,"stealth":1.0,"deviation":1.0,"postOnly":false,"originalSize":1.0E-5,"remainingSize":1.0E-5,"time_in_force":"GTC"}]

{Exchange:BTSE Type:LIMIT Side:BUY Pair:BTCUSDT AssetType:spot ImmediateOrCancel:false FillOrKill:false PostOnly:false ReduceOnly:false Leverage:0 Price:25000 Amount:1e-05 QuoteAmount:0 TriggerPrice:0 ClientID: ClientOrderID: LastUpdated:2022-06-06 11:31:18.708066 +1000 AEST m=+1.690237201 Date:2022-06-06 11:31:18.708066 +1000 AEST m=+1.690237201 Status:NEW OrderID:cfd6680d-ba2d-49e5-9b07-460f5758ced3 Trades:[] Fee:0 Cost:0}
```

2022-06-06 01:52 UTC, thrasher- approved these changes
tACK! Thanks for fixing the exchange_template issue

2022-06-06 01:52 UTC, merged