grpc: add shutdown call for external management
thrasher-corp/gocryptotrader pull request #957
Opened 2022-05-18 01:36 UTC by shazbert

If not appropriate can close,  I will keep this branched.

Fixes # (issue)

## Type of change

Please delete options that are not relevant and add an `x` in `[]` as item is complete.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How has this been tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration and
also consider improving test coverage whilst working on a certain feature or package.

- [ ] go test ./... -race
- [ ] golangci-lint run
- [ ] Test X

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation and regenerated documentation via the documentation tool
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally and on Github Actions/AppVeyor with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-05-19 02:49 UTC, gloriousCode reviewed
I like it. It works well and you ensure that its disabled by default. My only though would be, would you want to add a config field for it under `remoteControl` -> `gRPC` ? If not, I'm happy with this.

2022-05-19 04:49 UTC, thrasher- requested changes
In favour of this change!

2022-05-19 04:49 UTC, thrasher- commented on engine/engine.go
> +	gctlog.Warnln(gctlog.Global, "Captured gRPC, shutdown requested.")
```suggestion
	gctlog.Warnln(gctlog.Global, "Captured gRPC shutdown request.")
```

2022-05-19 04:49 UTC, thrasher- commented on engine/rpcserver.go
> +	errGRPCShutdownSignalIsNil = errors.New("cannot shutdown, grpc shutdown channel is nil")
```suggestion
	errGRPCShutdownSignalIsNil = errors.New("cannot shutdown, gRPC shutdown channel is nil")
```

2022-05-19 04:49 UTC, thrasher- commented on main.go
> +	flag.BoolVar(&settings.EnableGRPCShutdown, "grpcshutdown", false, "enables the allowance of the grpc to terminate services")
```suggestion
	flag.BoolVar(&settings.EnableGRPCShutdown, "grpcshutdown", false, "enables gRPC bot instance shutdown functionality")
```

2022-05-20 00:35 UTC, gloriousCode requested changes
Minorino niterino shazerino

2022-05-20 00:35 UTC, gloriousCode commented on engine/rpcserver.go
> +	errShutdownNotAllowed      = errors.New("shutting down this bot instance is not allowed via gRPC, please enable by command line flag --grpcshutdown or config.json")
```suggestion
	errShutdownNotAllowed      = errors.New("shutting down this bot instance is not allowed via gRPC, please enable by command line flag --grpcshutdown or config.json field grpcAllowBotShutdown")
```

2022-05-20 01:02 UTC, gloriousCode approved these changes
tACK! Thanks for making those changes!

2022-05-20 01:20 UTC, thrasher- approved these changes
tACK, works well!

2022-05-20 01:20 UTC, merged